### ISSUE TITLE
[FEATURE} Setting up process tracker to schedule email

### ISSUE THREAD

**Issue by Chethan-rao** [juspay/hyperswitch#1095]
### Feature description - 
Since expiry of the api_key would start right from its creation, while creating an api_key, insert a db entry into process_tracker table with new process_tracker workflow `ApiKeyExpiryWorkflow` and write logic for sending email by fetching merchant details.

### Possible implementation - 
When a merchant creates an API key with a future expiry date, a new process can be added to the `process_tracker` table. This process includes `tracking_data` that contains the `key_id`, `merchant_id`, `api_key_expiry`, and `expiry_reminder_days`. The api_key_expiry represents the date and time when the API key expires, and `expiry_reminder_days` is a vector specifying the number of days before the expiry when reminder emails should be sent (currently set as [7, 3, 1]). `schedule_time` will be set to 1st reminder date, and after the 1st email is sent, we update the `schedule_time` as `tracking_data.expiry_reminder_days[retry]` where `retry` initially set to 0, acts as a counter. This results in emails being scheduled at the respective number of days before API key expiry. So during 1st time, `schedule_time` would be 7 days prior to api_key expiry and during 2nd time, it would be 3 days prior and so on. Hence, for a given api_key, only one process should reside in `process_tracker` whose `schedule_time` changes accordingly.
 
A new workflow `ApiKeyExpiryWorkflow` should be introduced on which `ProcessTrackerWorkflow` is implemented. The `execute_workflow()` function retrieves the merchant's email address and determines whether to send the email, schedule it for a later time, or finish the current process based on the retry count.

**Comment by jarnura** [comment]
@Chethan-rao Can you add a more description in the issue.
