### ISSUE TITLE
[FEATURE] Implement `MerchantConnectorAccountInterface` for `MockDb` 

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#1123]
Spin off from #172. Refer to the parent issue for more information

**Comment by Narayanbhat166** [comment]
Can someone take this up on priority? Need this for adding tests for session token flow. Thanks!

**Comment by Narayanbhat166** [comment]
Sure @jeevaprakashdr. I will assign this to you.

**Comment by jeevaprakashdr** [comment]
@Narayanbhat166 gentle note, PR has been created.
