### ISSUE TITLE
 Implement `DisputeInterface` for `MockDb`

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#1190]
Spin out from https://github.com/juspay/hyperswitch/issues/172. Please refer to that issue for more information.

**Comment by Exosyz** [comment]
Hi,
Can I take this one? 
This will be my first contribution, I will try to do my best.

**Comment by SanchithHegde** [comment]
Hey @Exosyz, sure! I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our Discord server, whichever you are comfortable with. In case you need to look into similar `MockDb` implementations, you can check out PRs #1101 and #968 that were merged recently.
