### ISSUE TITLE
Implement `MandateInterface` for `MockDb`

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#1256]
Spin out from https://github.com/juspay/hyperswitch/issues/172. Please refer to that issue for more information.

**Comment by nachiketkanore** [comment]
I would like to take this

**Comment by SanchithHegde** [comment]
I've assigned this to you @nachiketkanore. Just a heads up, the interface to be implemented was updated to be `MandateInterface` instead of `CardsInfoInterface`, since there was an issue for `CardsInfoInterface` already that we had overlooked.
