### ISSUE TITLE
[PERF] Remove redundant heap allocation present in the logging framework

### ISSUE THREAD

**Issue by NishantJoshi00** [juspay/hyperswitch#1293]
Use here, below, and in similar places, the`format_args!()` macro instead, to omit redundant allocations produced by the `format!()` macro (as it returns a new `String`).

## Code Snippets

- https://github.com/juspay/hyperswitch/blob/597ec16907a83ce228228b8c00e329495ade117b/crates/router_env/src/logger/formatter.rs#L208
- https://github.com/juspay/hyperswitch/blob/597ec16907a83ce228228b8c00e329495ade117b/crates/router_env/src/logger/formatter.rs#L214

### Steps for Resolution

While taking up this issue, please document the solution you are going forward with, also include benchmarks or evidence as to how extra heap allocations are avoided. (please use this issue itself for discussion and the approach documentation). 
(Optional) in-code documentation is always encouraged.

**Comment by jeevaprakashdr** [comment]
@NishantJoshi00  Correct me if I am wrong, but the author of the [117](https://github.com/juspay/hyperswitch/issues/117) had already mentioned the possible solution. 

As part of this issue, should we have to identify if there are other options?  
Out of curiosity how can I check how much heap memory is allocated in Rust?

**Comment by NishantJoshi00** [comment]
Hey @jeevaprakashdr, if you have any other inputs on a different approach on this problem, we should discuss this, whilst talking about the heap allocation. I came up with some interesting resource you might want to check out, I personally haven't tested them but they seem promising:
- https://crates.io/crates/peak_alloc
- https://rust-analyzer.github.io/blog/2020/12/04/measuring-memory-usage-in-rust.html

**Comment by jeevaprakashdr** [comment]
@NishantJoshi00  yup happy to have a look at it. please could you assign the issue to me.  Thanks

**Comment by NishantJoshi00** [comment]
Sure, let me know if you have any questions, or want to discuss any approach other than that which was suggested. Definitely open for any enhancement.

**Comment by jeevaprakashdr** [comment]
@NishantJoshi00 I spent quite a bit of time if we can have a declarative macro around. 
as my understanding we cannot compose format_ars! in another user define  macro_rule 
unless we actually write a proc macro which is not necessary at the moment.
