### ISSUE TITLE
[FEATURE] Adding recon dashboard in hyperswitch dashboard

### ISSUE THREAD

**Issue by anji-reddy-j** [juspay/hyperswitch#1314]
### Feature Description

*

### Possible Implementation

*

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by anji-reddy-j** [comment]
https://github.com/juspay/hyperswitch/pull/1713

**Comment by SanchithHegde** [comment]
Closing as completed in #1713
