### ISSUE TITLE
[REFACTOR] Define the Mapping between `ConnectorError` and `ApiErrorResponse` using the `ErrorSwitch` trait

### ISSUE THREAD

**Issue by vspecky** [juspay/hyperswitch#1326]
### Feature Description

Currently, we are mapping errors from `ConnectorError` to `ApiErrorResponse` using custom logic (can be found [here](https://github.com/juspay/hyperswitch/blob/cd0cf40fe29358700f92c1520475934752bb4b30/crates/router/src/core/webhooks/utils.rs#L52)).

We want to refactor this implementation to make use of the existing `ErrorSwitch` trait which satisfies the same usecase.

### Possible Implementation

We have a custom trait for conversion of error from `ConnectorError` to `ApiErrorResponse` as can be found using the link in the description above. The mapping has to be defined using the `ErrorSwitch` trait instead, and the custom trait can hence be deleted.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by PanGan21** [comment]
Hi @vspecky  I am trying to understand the issue and the related code. Are you suggesting to replace the implementation of `WebhookApiErrorSwitch` with an implementation for `ErrorSwitch`? Is this change going to happen in the same file or you are suggesting a restructuring as well?

**Comment by vspecky** [comment]
On second thought, it would be better to move the `ErrorSwitch` implementation in a `crates/router/src/core/errors/transformers.rs` module. We can then put the `ErrorSwitch` impl for `ApiErrorResponse` (shown below) in the same file, which currently resides in `crates/router/src/core/errors/api_error_response.rs`.
https://github.com/juspay/hyperswitch/blob/e4b95460ed54946e233a63f09027dd1dbfa2b0a7/crates/router/src/core/errors/api_error_response.rs#L265

@lsampras @SanchithHegde What do you think?

**Comment by PanGan21** [comment]
That sounds a bit more logical to me, because in a dry run I did locally I was getting errors that the types are defined outside of the current crate

**Comment by lsampras** [comment]
@vspecky I believe `ErrorSwitchFrom` should solve your use case, if you are facing problems with implementing the trait on foreign objects...

Also we intend to remove this `ApiErrorResponse` defined in the router & instead rely on the `common_utils::ApiErrorResponse`
https://github.com/juspay/hyperswitch/blob/e4b95460ed54946e233a63f09027dd1dbfa2b0a7/crates/router/src/core/errors/api_error_response.rs#L265

Ideally we should be implementing 
```
 impl common_utils::errors::ErrorSwitch<api_models::errors::types::ApiErrorResponse> for ConnectorError
```

**Comment by PanGan21** [comment]
What i understand from the explanation is something like this in `router/src/core/errors/transformers.rs`
```
impl ErrorSwitch<ApiErrorResponse> for ConnectorError {
    fn switch(&self) -> ApiErrorResponse {
        match self {
            ConnectorError::WebhookSourceVerificationFailed => {
                ApiErrorResponse::WebhookAuthenticationFailed
            }
            ConnectorError::WebhookSignatureNotFound
            | ConnectorError::WebhookReferenceIdNotFound
            | ConnectorError::WebhookResourceObjectNotFound
            | ConnectorError::WebhookBodyDecodingFailed
            | ConnectorError::WebhooksNotImplemented => ApiErrorResponse::WebhookBadRequest,
            ConnectorError::WebhookEventTypeNotFound => {
                ApiErrorResponse::WebhookUnprocessableEntity
            }
            _ => ApiErrorResponse::InternalServerError,
        }
    }
}
```

This implementation gives some errors in `webhooks.rs` that I am not sure how to resolve. 
For example in the line:
`let dispute_details = connector.get_dispute_details(request_details).switch()?;`
There is type error. 
I am wondering then is the usage of switch method meant to be changed?

**Comment by SanchithHegde** [comment]
@PanGan21 Could you include the error message/screenshot here? Just confirming, did you remove the `WebhookApiErrorSwitch` trait and its implementation?

**Comment by PanGan21** [comment]
I just linked a draft pr. Thanks for the help
