### ISSUE TITLE
[REFACTOR] remove redundant call to fetch payment method data

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#1327]
In case of `payments_start` operation, there is a call to fetch payment method data ( which makes a call to the locker to fetch payment method data ). This call is not necessary since we do not need payment method data in that flow. This would add additional latency to payments flow.

https://github.com/juspay/hyperswitch/blob/fa392c40a86b2589a55c3adf1de5b862a544dbe9/crates/router/src/core/payments/operations/payment_start.rs#L237

Here the call to 
https://github.com/juspay/hyperswitch/blob/fa392c40a86b2589a55c3adf1de5b862a544dbe9/crates/router/src/core/payments/operations/payment_start.rs#L246
Is not necessary and can be removed

**Comment by shreyash-Pandey-Katni** [comment]
May I take it? @Narayanbhat166

**Comment by Narayanbhat166** [comment]
Sure @shreyash-Pandey-Katni, I will assign it to you

**Comment by Narayanbhat166** [comment]
Hey @shreyash-Pandey-Katni, let me know if you need any help in this refactor.

**Comment by shreyash-Pandey-Katni** [comment]
Thank you @Narayanbhat166, i am struggling a little bit in testing using `cargo +nightly fmt --all`. i will push changes as soon as possible.

**Comment by Narayanbhat166** [comment]
Hey @shreyash-Pandey-Katni, Please do raise the PR if you have a compiling code. We can look into formatting and other checks later

**Comment by shreyash-Pandey-Katni** [comment]
Hello, I was under the weather so it took a while to finish it off. I have raised the PR. Have a look and let me know.
