### ISSUE TITLE
[REFACTOR] Use secrets for sensitive data handled in connector integration

### ISSUE THREAD

**Issue by NishantJoshi00** [juspay/hyperswitch#1348]
Noticed that this file didn't include changes related to masking of API keys.

Should we take up marking this field (and wherever it's being passed) `Secret` as part of this PR, or a separate one?

https://github.com/juspay/hyperswitch/blob/61bacd8c9590a78a6d5067e378bfed6301d64d07/crates/router/src/connector/nmi/transformers.rs#L27

_Originally posted by @SanchithHegde in https://github.com/juspay/hyperswitch/pull/1320#discussion_r1214888879_

**Comment by pixincreate** [comment]
If #1320 fixed the issue, I believe we can close this.

**Comment by SanchithHegde** [comment]
> If #1320 fixed the issue, I believe we can close this.

Nope, these two comments from #1320 involve sensitive data not being wrapped within `Secret` in cases where authentication data is not sent within headers:

https://github.com/juspay/hyperswitch/pull/1320#discussion_r1214888879

https://github.com/juspay/hyperswitch/pull/1320#discussion_r1214897154
