### ISSUE TITLE
[FEATURE] add domain type for client secret 

### ISSUE THREAD

**Issue by Abhicodes-crypto** [juspay/hyperswitch#1357]
### Feature Description

Create domain type for client secret

### Possible Implementation

Make type `ClietSecret(String)` and use it wherever applicable

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by slelyukh** [comment]
Hello, can you assign this issue to me?

**Comment by tusharv01** [comment]
Any suggestions where to make changes as Client Secret files are not there in the codebase.

**Comment by amankrx** [comment]
Can you assign me this issue?

**Comment by Abhicodes-crypto** [comment]
You can add the type in this file https://github.com/juspay/hyperswitch/blob/main/crates/api_models/src/payments.rs 
And you need to implement serialize and dezerialize for the type. You can refer this as an example https://github.com/juspay/hyperswitch/blob/379d1d1375783f2c35edbf4dda6bbb0eb9351a3c/crates/api_models/src/api_keys.rs#L191 

Also add test cases to make sure the serialize and deserialize work. For an idea of the format of client secret refer PR #1358

**Comment by VedantKhairnar** [comment]
Hello @tusharv01  , please let us know if you're still working on this issue or still interested in working on it. There hasn't been any recent activity on this thread, or any open PRs.
.
Meanwhile we would be un-assigning you from the issue and close the PR but if you still want to work on it, please let us know.

**Comment by cb-dhivyadandapani** [comment]
Can i pick this up?

**Comment by deepanshu-iiitu** [comment]
@cb-dhivyadandapani I have assigned 2 other issues to you. We can assign you more once you complete those 2.

**Comment by Sushank34** [comment]
Hello team, could you please assign this issue to me?

**Comment by deepanshu-iiitu** [comment]
Hey @cb-dhivyadandapani @Sushank34 
This issue is not a part of Hacktoberfest.
You can use the labels Hacktoberfest and S-awaiting-triage to look for unassigned issues that are part of Hacktoberfest 2023

**Comment by wowinter13** [comment]
@Abhicodes-crypto @VedantKhairnar hello there guys, could you assign this issue to me? 
I will rework the PR that was started by @tusharv01
Looks like it ain't much left

**Comment by SanchithHegde** [comment]
Sure @wowinter13, I've assigned this to you.

**Comment by wowinter13** [comment]
@SanchithHegde @deepanshu-iiitu @Abhicodes-crypto hello there guys
Could you check please if I am going in the right direction?
(the pr is mentioned above)
