### ISSUE TITLE
[FEATURE] Implement cache for MerchantKeyStore.

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#1381]
### Feature Description

Implement L1 and L2 cache (In memory and Redis) for MerchantKeyStore store for MerchantKeyStore Table

### Possible Implementation

There's already a static called `ACCOUNTS_CACHE`. You can use that and call `get_or_populate_in_memory` function to fetch from database if it's not either in redis or in memory cache. Refer https://github.com/juspay/hyperswitch/blob/d21fcc7bfc3bdf672b9cfbc5a234a3f3d03771c8/crates/router/src/db/merchant_account.rs#L99-L108.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by NavinShrinivas** [comment]
hey, im taking a look at this issue...It'd be helpful to know where the memory store for the cache is

**Comment by dracarys18** [comment]
Hey @NavinShrinivas the static for the in memory cache already exists as `ACCOUNTS_CACHE`. You just need to implement the get and store in redis and in memory logic for the table.

**Comment by NavinShrinivas** [comment]
I'd like to work on this, all we should be calling is the get_or_populate_redis function before the memory (right?), when do we decide to cache it in memory if present in redis?

**Comment by dracarys18** [comment]
I will be assigning it to you @NavinShrinivas. You have to just call `get_or_populate_in_memory`. About the caching it happens during a get call to database, suppose if you don't have the data in in-memory cache or redis we fetch the data from database and insert into them both otherwise we get it from either in-memory or redis wherever it's present. Suppose the data is not in in-memory cache but it's on redis we get it from redis and insert it into in-memory.

**Comment by NavinShrinivas** [comment]
```rust
pub async fn get_or_populate_in_memory<T, F, Fut>(
    store: &Store,
    key: &str,
    fun: F,
    cache: &cache::Cache,
) -> CustomResult<T, errors::StorageError>
where
    T: Cacheable + serde::Serialize + serde::de::DeserializeOwned + std::fmt::Debug + Clone,
    F: FnOnce() -> Fut + Send,
    Fut: futures::Future<Output = CustomResult<T, errors::StorageError>> + Send,
{
    let cache_val = cache.get_val::<T>(key);
    if let Some(val) = cache_val {
        Ok(val)
    } else {
        let val = get_or_populate_redis(store, key, fun).await?;
        cache.push(key.to_string(), val.clone()).await;
        Ok(val)
    }
}
```

This seems to be the current cahchng function for memory, I dont seem to have caught the gist of the issue yet as this function alredy checking and populates redis as needed. MerchantKeStore is calling this function for its cache checks.

**Comment by NavinShrinivas** [comment]
Oh my bad, this function is called in merchatn account rather than keyStore, got the gist..will try sending a PR in soon

**Comment by NavinShrinivas** [comment]
Hey @dracarys18 , I have some changes ready to be proposed as a PR, but cargo test is crashing my system. any fixes?

**Comment by NavinShrinivas** [comment]
@dracarys18 I just opened a PR, would like to iterate on it. This being the first PR in hyperswitch I'm not sure i covered everything, I'm still trying to under the code structure. Any recommendations is welcome!

**Comment by lsampras** [comment]
@dracarys18 Is this issue solved?
can we close it...
