### ISSUE TITLE
[BUG] Payments list doesn't work with pagination parameters

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#1439]
### Context
- Currently the API accepts payment_id as pagination parameters for e.g starting_after = `pay_Ajabdhakjhah`
- However the underlying code relies on the auto-increment characteristic of databases
- While we do some sort of conversion here our pagination filters are based on `id` whereas the sort is `modified_at`
- This causes the response list to be not actually be paginated but return inconsistent & wrong results

#### Possible Solutions

- Either we can update the pagination filters to use `modified_at` (which can cause inconsistencies with data lists since `modified_at` can be changed)
- We can also try to sort out the list by incremental id

**Comment by Abhicodes-crypto** [comment]
It was sorted by `id` before it is changed in this PR - https://github.com/juspay/hyperswitch/pull/317 
The same thing has been repeated for disputes and refunds as well.

**Comment by NavinShrinivas** [comment]
Hey @lsampras I'd like to work on this, can I be assigned to it?

**Comment by lsampras** [comment]
Ideally we would want it sorted by the `modified_at` column in payment_intent.

Also we use `futures::stream::iter` when getting the associated [payment_attempts](https://github.com/juspay/hyperswitch/blob/2b71d4d8c40c3697e902398fc76bc1256d5b25ee/crates/router/src/core/payments.rs#L1154),
If possible you can try to make this concurrent as well for extra challenge/brownie points

**Comment by NavinShrinivas** [comment]
Just as a clarification, we want the payments_list to be sorted by create_at in DESC ordered as possibly the front-end pagination depends on it being sorted that way?

**Comment by NavinShrinivas** [comment]
Update : I have some code waiting for this issue, it implements async db fetches and uses a map, this has some considerable changes and would like to test before I open a PR.

**Comment by NavinShrinivas** [comment]
![image](https://github.com/juspay/hyperswitch/assets/42774281/c343f09f-2679-483f-aa72-7e4b69e768fa)
This is despite havbing created an API key and it beign stored to variables, any idea?

**Comment by NavinShrinivas** [comment]
@lsampras if the above commit seems fine, I'll open a p.  I've tested in local and it returns payment lists from most recent to oldest payments.

**Comment by SanchithHegde** [comment]
Closing as completed in #1556.
