### ISSUE TITLE
[BUG] Pass attempt id and payment id as reference in trustpay

### ISSUE THREAD

**Issue by Abhicodes-crypto** [juspay/hyperswitch#1443]
### Bug Description

Currently we pass payment_id as reference in trust pay. Webhooks processing will fail because of this as webhooks require attempt id

### Expected Behavior

This needs to be fixed by passing both payment id and attempt id.

### Actual Behavior

Payment id is being passed

### Steps To Reproduce

NA

### Environment

Any env

### Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by SanchithHegde** [comment]
Closing as completed in #1444
