### ISSUE TITLE
[DOC]: Add CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by devWonderkind** [juspay/hyperswitch#1570]
heyy @SanchithHegde @prasunna09  I want to work on this issue.
Please assign this issue to me under GSSoC'23.

**Comment by SanchithHegde** [comment]
Hey @devWonderkind, we already have a [Code of Conduct](https://github.com/juspay/hyperswitch/blob/main/docs/CODE_OF_CONDUCT.md) in our repository. Is there anything specific that you want to add to that document?

**Comment by devWonderkind** [comment]
Yes we can change the template of code of conduct.

**Comment by SanchithHegde** [comment]
Closing this as won't fix.
