### ISSUE TITLE
[enhancement]:Add scoped error enum for customer error

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#1580]
tracked in #1579 

We wanna use scoped errors + Errorswitch for customer API's

Currently customer API's returns the common errors enum...
It uses 
```
CustomerRedacted
CustomerNotFound
MandateNotFound
& a lot of InternalServerError's
```

instead we need to figure the errors raised here & add the corresponding variants...

**Comment by jeevaprakashdr** [comment]
@lsampras please can you assign this issue to me? Also please can you update the description if there is anything changed since the issue is written
