### ISSUE TITLE
Add logs for customer routes & functions

### ISSUE THREAD

**Issue by tinu-hareesswar** [juspay/hyperswitch#1598]
Add API logs for customer routes & functions

**Comment by nix-rs** [comment]
hey i'm interested to contribute can you guide me ? as i'm new to rust and programming. thanks,

**Comment by lsampras** [comment]
Hey @nix-rs unfortunately there's some other issues that need to be resolved before this can be picked up,

This is the parent tracking issue #1579 

For instance you can look at related issue #1580 which is available to work for,

You can also join our discord/slack for rust programming or project setup related doubts
