### ISSUE TITLE
[BUG] update `api_key_expiry_workflow` to validate the expiry before scheduling the task

### ISSUE THREAD

**Issue by Chethan-rao** [juspay/hyperswitch#1625]
### Bug Description

We have a `process_tracker` which schedules the task to future date, and executes it whenever the time is up. We have a feature to schedule a reminder email to notify the merchants when their api_key is about to expire.
Currently, when the api_key is created with some expiry set, process tracker schedules the 1st email, 7 days prior to api_key expiry. But just in case merchant sets the expiry to next day, process tracker will schedule the email to past day which won't be executed by process tracker. 

### Expected Behavior

During the api_key expiry if the merchant sets the expiry to next day or any other day before 7 days, we need to perform a validation something like - calculate the schedule_time of 1st email during api_key creation. if it is before the current_time, don't create an entry in process_tracker.

file to include the change - 
https://github.com/juspay/hyperswitch/blob/e913bfc4958da613cd352eca9bc38b23ab7ac38e/crates/router/src/core/api_keys.rs#L193C1-L193C1

### Steps To Reproduce

1. Run below commands in 3 diff terminals
    - cargo r --features email (application)
    - SCHEDULER_FLOW=producer cargo r --bin scheduler (producer binary)
    - SCHEDULER_FLOW=consumer cargo r --bin scheduler (consumer binary)
2. Create an api_key with expiry set to next day in postman.
3. Check the process_tracker table in db which will contain the schedule_time field set to past day.

### Context For The Bug

Just to cover the edge case

### Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by trfdeer** [comment]
Hi
Can I work on this?

**Comment by Chethan-rao** [comment]
Hi,
Absolutely! thank you for showing interest in working on this issue. If you encounter any questions or need guidance, don't hesitate to ask.

**Comment by trfdeer** [comment]
I'd like to know more about how to do this.
1. Should I update [`add_api_key_expiry_task`](https://github.com/juspay/hyperswitch/blob/1afc54837d5988eaf41f434474c30ec511681bbe/crates/router/src/core/api_keys.rs#L205) to return an error? [`update_api_key_expiry_task`](https://github.com/juspay/hyperswitch/blob/1afc54837d5988eaf41f434474c30ec511681bbe/crates/router/src/core/api_keys.rs#L361) should also be updated?
2. Or should I add checks to [`create_api_key`](https://github.com/juspay/hyperswitch/blob/1afc54837d5988eaf41f434474c30ec511681bbe/crates/router/src/core/api_keys.rs#L187) and avoid calling `add_api_key_expiry_task` ? `update_api_key` ([1](https://github.com/juspay/hyperswitch/blob/1afc54837d5988eaf41f434474c30ec511681bbe/crates/router/src/core/api_keys.rs#L319), [2](https://github.com/juspay/hyperswitch/blob/1afc54837d5988eaf41f434474c30ec511681bbe/crates/router/src/core/api_keys.rs#L344)) should also be updated in this case?

**Comment by Chethan-rao** [comment]
We'd prefer not to create an entry in process_tracker itself, meaning don't call the `add_api_key_expiry_task` in that case.
Also add the checks in `add_api_key_expiry_task` and `update_api_key_expiry_task` as we are calculating the first schedule_time inside these functions itself. Move the part where we calculate the schedule_time to the top of the above mentioned functions and add validation there

**Comment by trfdeer** [comment]
Hi
I created a pull request for this.
Though I'm not sure how I'm exiting early if the expiry date is in the past is ok.

**Comment by Chethan-rao** [comment]
> Hi I created a pull request for this. Though I'm not sure how I'm exiting early if the expiry date is in the past is ok.

Ya it's fine to exit early
