### ISSUE TITLE
[FEATURE] Add optional path parameter - client_secret in the PaymentsRetrieve endpoint

### ISSUE THREAD

**Issue by kritikmodi** [juspay/hyperswitch#1630]
### Feature Description

Stripe supports passing `client_secret` as a path parameter when `publishable_key` is used. Our Stripe Compatibility Layer doesn't support it yet. Therefore, we need to add this option.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by Abhicodes-crypto** [comment]
https://github.com/juspay/hyperswitch/pull/1663
