### ISSUE TITLE
Feat: add github action to lock new issues

### ISSUE THREAD

**Issue by harmeetsingh11** [juspay/hyperswitch#1662]
**Is your feature request related to a problem? Please describe.**
This repository has 170+ opened issues.
Issues receive more comments as a whole. As a result, the number of desktop and mobile notifications rises, making their management challenging for repository maintainers, admins. 

**Describe the solution you'd like**
I will add the github action workflow, which will lock new new issues. This means that, when the new issue is created, it will be locked. The issue will be unlocked when the maintainer/admin will add `status: ready for dev` label to it. The admins and maintainers would greatly benefit from this, and it would also reduce notifications.

**Record**
- [x] I agree to follow project's contribution guidelines and code of conduct.
- [x] I'm a GSSoC'23 contributor.
- [x] I want to work on this issue.

Thanks

**Comment by SanchithHegde** [comment]
> I will add the github action workflow, which will lock new new issues. This means that, when the new issue is created, it will be locked. The issue will be unlocked when the maintainer/admin will add `status: ready for dev` label to it.

On the contrary, most of the issues we open are open for discussion and locking them on creation will require unnecessary effort on the maintainers' end.

Will be closing this issue as won't fix.
