### ISSUE TITLE
[FEATURE] Implement `MerchantKeyStoreInterface` for `MockDb`

### ISSUE THREAD

**Issue by ThisIsMani** [juspay/hyperswitch#1697]
### Feature Description

Currently the MerchantKeyStoreInterface is not implemented for MockDb. It is required for merchant account functions. And without this implementation, we cannot write tests for them.

### Possible Implementation

Checkout #172 for more details.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by SanchithHegde** [comment]
I'll be taking this up as this is one of the `MockDb` implementations that would enable us to add tests.
