### ISSUE TITLE
feat(core): Change Currency Enum to text string

### ISSUE THREAD

**Issue by SamraatBansal** [juspay/hyperswitch#1705]
### Feature Description

The currency column in the database can be modified to accept string, rather than enum of currencies, as any time we have to update the currency field like add a new currency a new migration is required to run.

### Possible Implementation

Rather than putting a check at DB level, we can have a check at application level, keep a enum for currencies which gets transformed to string before pushing to DB.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by NoBugsBunny** [comment]
I would like to pick this issue.

**Comment by ketpals** [comment]
Please assign this issue to me.

**Comment by tusharxoxoxo** [comment]
![Screenshot 2023-07-24 at 10 52 18 AM](https://github.com/juspay/hyperswitch/assets/79051850/87d17d34-d8a1-422f-af86-0af00c6af2e0)

**Comment by tusharxoxoxo** [comment]
@SamraatBansal i think we need to create a new column of type text and then copy the current data of enum currency column to the new text currency column, and then delete the enum currency column after verify of proper replication of data, 

1. First, add a new TEXT column to the table.
2. Update the new column with the values from the ENUM column.
3. Drop the old ENUM column.
4. Rename the new TEXT column to the original ENUM column name (optional).

**Comment by tusharxoxoxo** [comment]
ALTER TABLE your_table ADD COLUMN new_text_column TEXT;

UPDATE your_table SET new_text_column = your_enum_column::text;

ALTER TABLE your_table DROP COLUMN your_enum_column;

ALTER TABLE your_table RENAME COLUMN new_text_column TO your_enum_column;

**Comment by tusharxoxoxo** [comment]
@SamraatBansal 
[2023-07-19-081050_add_zero_decimal_currencies](https://github.com/juspay/hyperswitch/tree/4df67adb9bb110f1c5f3fc094fe21bf4741cda46/migrations/2023-07-19-081050_add_zero_decimal_currencies) 
I was going through this section of postgresql code that u recently included, i didn't understood what u r trying to do with this section of code, like whatever work is done by up.sql is being reverted back to original by down.sql, i didn't get what it is, can u please explain what is being done here

**Comment by tusharxoxoxo** [comment]
@SamraatBansal 
Am I going in the right direction or not, can u please confirm, and can u please tell me where can i found documentation about the hyper switch code like i looked for it but was unable to find any

**Comment by prasunna09** [comment]
hey @tusharxoxoxo, thanks for your interest, just wanted to let you know that after a recent product review, we are going with alternative method which is mentioned in this [issue](https://github.com/juspay/hyperswitch/issues/1814). Feel free to contribute there.

**Comment by tusharxoxoxo** [comment]
ok
