### ISSUE TITLE
[BUG] Stripe - Sending credit card numbers directly to the Stripe API is generally unsafe

### ISSUE THREAD

**Issue by kielerdotdev** [juspay/hyperswitch#1723]
### Bug Description

Hyperswitch sends raw payment card details on create payment to the stripe api which is disabled on some newer accounts. Causing payments not to work

### Expected Behavior

Would expect Hyperswitch to create a payment token from the card info, and use that in all payment api's.
https://stripe.com/docs/api/tokens/create_card

### Actual Behavior

Api Request
```
json
{"client_secret":"pay_xxx","return_url":"https://app.hyperswitch.io/home","payment_method":"card","payment_method_data":{"card":{"card_number":"4242424242424242","card_exp_month":"04","card_exp_year":"2024","card_holder_name":"","card_cvc":"424","card_issuer":"","card_network":"Visa"}},"browser_info":{"user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","accept_header":"text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,image\\/webp,image\\/apng,*\\/*;q=0.8","language":"en-US","color_depth":24,"screen_height":1331,"screen_width":2564,"time_zone":-120,"java_enabled":true,"java_script_enabled":true}}```

Api response
```json
{
    "error": {
        "type": "connector",
        "message": "No error code: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.",
        "code": "CE_00",
        "connector": "stripe"
    }
}```

![image](https://github.com/juspay/hyperswitch/assets/36795828/2e8faeea-7745-42aa-a06c-c6afb79861d6)


### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Add stripe as a connector in a sandbox env
2. Test payment using unified payments
3. Use stripe 4242 4242 4242 4242 as card number

### Context For The Bug

_No response_

### Environment

Are you using hyperswitch hosted version? Yes
If yes, please provide the value of the `x-request-id` response header for helping us debug your issue.

x-request-id: 35018b79-db3a-45d2-a935-b4531f103b73

### Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, I don't have time to work on this right now

**Comment by Abhicodes-crypto** [comment]
Hi @kielerdotdev , thank you for raising this issue. 
- Hyperswitch is PCI complaint so it is allowed to send raw card details to stripe. 
- However, an option should be enabled on the stripe dashboard. Please logon to you Stripe dashboard > Search for Integrations > Advanced Options > Handle card information directly.
- If you are not PCI complaint you can use Hyperswitch [frontend sdks](https://hyperswitch.io/docs/sdkIntegrations/unifiedCheckoutWeb/nodeBackendAndReactFrontend) to accept card information from customer and send to Hyperswitch directly.

**Comment by NarsGNA** [comment]
Hi @kielerdotdev!
Creating a payment token with Stripe means that the token can only be used with Stripe. This means that the end user would have to re-enter their card details for it to be processed by the other integrated payment processors creating a friction in the payment experience.
Hence enabling sending raw card data from the processor's end is a better approach because it is easier and is secure given that Hyperswitch is PCI compliant.

**Comment by Kamal-Moha** [comment]
Hi I'm having this similar issue when trying to make a test payment in hyperswitch dashboard. I have successfully connected stripe to hyperswitch, and then attempted to make a test payment with the test cards. I get the error "Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using".

Tried to do the suggestion by @Abhicodes-crypto of enabling the "Handling of card information" in stripe settings;
![image](https://github.com/user-attachments/assets/b976a1e8-53d3-4b64-8fb2-465e640e82fc)

But as you can see from above, stripe doesn't let me enable that.

Now I would like to try the suggestion by stripe of using test tokens. But know I don't know how to pass the test tokens in hyperswitch when making the test payment. Please help. Thanks!
