### ISSUE TITLE
[FEATURE]  Readme file is missing Gssoc template

### ISSUE THREAD

**Issue by HimanshuNarware** [juspay/hyperswitch#1729]
### Feature Description

Readme file is missing Gssoc template

### Possible Implementation

I want to improve the readme file by adding the title of
This Open-Source project is a part of GSSOC
![788](https://github.com/juspay/hyperswitch/assets/83147410/79ae3c90-6583-476a-bb38-fb3421c42467)

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by VedantKhairnar** [comment]
Thank you for your interest in contributing to Hyperswitch during GirlScript Summer of Code (GSSOC). We really appreciate your effort and dedication to improving our project.

Regarding the inclusion of the GSSOC logo in our product readme, we want to maintain a consistent and professional appearance for our corporate project. While we fully support and acknowledge your participation in GSSOC, adding the logo to our product readme may not align with our project's guidelines and goals.

We are open to code as well as doc contributions which are product specific.
Looking forward to your contributions ahead! Thanks.
