### ISSUE TITLE
[REFACTOR]: Include Currency Conversion utility functions to `Currency` Trait implementation

### ISSUE THREAD

**Issue by SamraatBansal** [juspay/hyperswitch#1750]
### Feature Description

Implement `to_currency_base_unit` and `to_currency_base_unit_asf64` written in `router/src/utils.rs` in Currency trait implemented in `crates/common_enums/enums.rs`.  

Also remove `to_currency_base_unit` and `to_currency_base_unit_asf64`  from `router/src/connector/utils.rs` as they won't be required anymore

### Possible Implementation

```
impl Currency {
   pub fn to_currency_base_unit(&self, amount: i64) -> &'static str {...............}
   pub fn to_currency_base_unit_asf64(&self, amount: i64) -> &'static str {...............}
   pub fn iso_4217(&self) ............
}
```
Subsequently call these functions wherever `utils::to_currency_base_unit` or `utils::to_currency_base_unit_asf64` is called.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by uddhavdave** [comment]
Hi! I'm new to Hyperswitch and would like to pick this up. 

Actually, I already implement half of the ask here.

> Also remove to_currency_base_unit and to_currency_base_unit_asf64 from router/src/connector/utils.rs as they won't be required anymore
In my opinion, its not worth removing these functions, since if we do, we would have to add `change_context` method in all the transformer instances. Ideally, we would implement the `From` trait to avoid this, but in this case we are blocked due to orphan rule as the error is wrapped in a `Report` struct.

**Comment by SamraatBansal** [comment]
Hey @uddhavdave , Welcome to Hyperswitch Community!

Not entirely sure what you mean here.
Ideally, the output of the functions defined in `common_enums/enums.rs` would be a `Result<T, E>` as opposed to a `Result<T, error_stack::Report<E>>`. We would convert it to a `Result<T, error_stack::Report<E>>` in the main `router` crate, in the connector `transformers.rs` files by calling `.into_report()` on them. If you're trying to say that the `.into_report().change_context()` invocations in the `transformers.rs` are redundant, then no, they aren't redundant. Their presence aligns with our design principles.

**Comment by uddhavdave** [comment]
That's fair, I see a lot of instances where we call `change_context` method to replace the usually returned validation error.

Thanks for the explanation.

**Comment by uddhavdave** [comment]
Just to follow up on this, should I wait till this issue is assigned to me?
