### ISSUE TITLE
[BUG] Add Create Merchant and Create Merchant Key Store in a DB transaction

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#1793]
Currently MerchantAccount and MerchantKeyStore are getting inserted seperately. Since both of them are interdependent we need to make sure both are consistent with each other. If one of them fails  other shouldn't get inserted. 

We need to add this in a db_transaction
https://github.com/juspay/hyperswitch/blob/4805a94ab905da520edacdddab41e9e74bd3a956/crates/router/src/core/admin.rs#L133-L186

For reference of how to do it in a db transaction
```rust
  pool.transaction_async(|conn| async move {
        diesel::update(dsl::users)
            .filter(dsl::id.eq(0))
            .set(dsl::name.eq("Let's change the name again"))
            .execute_async(&conn)
            .await
            .map_err(|e| PoolError::Connection(e))
})
```

**Comment by artech-git** [comment]
Hi @dracarys18  gonna take a look into this issue, also how can you tell me how should the `conn.transaction_async()` be performed should it be done under`create_merchant_account` itself, or should I modify the previous method `insert_merchant_key_store` under the trait `MerchantKeyStoreInterface`

I was experimenting with the logic and made changes in the following sections

```rust
impl MerchantKeyStoreInterface for Store {

    async fn insert_merchant_and_key_store(
        &self,
        merchant_account: domain::MerchantAccount,
        merchant_key_store: domain::MerchantKeyStore,
        key: &Secret<Vec<u8>>,
    ) -> CustomResult<domain::MerchantAccount, errors::StorageError> {
        let conn = connection::pg_connection_write(self).await?;
        
        let val = conn.transaction_async(|e| async move {
    
            merchant_key_store
                .construct_new()
                .await
                .change_context(errors::StorageError::EncryptionError)?
                .insert(&e)
                .await
                .map_err(Into::into)
                .into_report()?
                .convert(key)
                .await
                .change_context(errors::StorageError::DecryptionError);

            merchant_account
                .construct_new()
                .await
                .change_context(errors::StorageError::EncryptionError)?
                .insert(&e)
                .await
                .map_err(Into::into)
                .into_report()?
                .convert(merchant_key_store.key.get_inner())
                .await
                .change_context(errors::StorageError::DecryptionError)
        
        }).await;

        val
    }
    ```
    do let me know your thoughts or anything else related which I can revise.

**Comment by dracarys18** [comment]
Hey @artech-git I would prefer keeping the Store interface seperate for MerchantKeyStore and MerchantAccount. i.e Store impl of MerchantKeystore will only insert into merchant_key_store table. So it would be better to do it in `admin.rs` as I mentioned in the issue.

**Comment by dracarys18** [comment]
Hey @artech-git , Please let me know if you need any help in this

**Comment by dracarys18** [comment]
Opening this issue for contributions because of inactivity.

**Comment by Azanul** [comment]
May I take this up?

**Comment by SanchithHegde** [comment]
Sure @Azanul, I'll assign this to you.

**Comment by Azanul** [comment]
To do this in admin.rs, I think we would need access to the connection to underlying Store. 
Is it exposed via a trait/method? I couldn't find it.

**Comment by dracarys18** [comment]
Hey @Azanul in that case add it in `MerchantAccountInterface` in `insert_merchant_account` function. Since we don't want to insert MerchantAccount without inserting KeyStore.

**Comment by gorakhnathy7** [comment]
Closing this, as per inputs of @dracarys18
