### ISSUE TITLE
[FEATURE] add fields in payments list response

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#1967]
### Feature Description

The `payments_list` endpoint currently has the following fields
- payment_id
- merchant_id
- status
- amount
- amount_capturable
- client_secret
- created
- currency
- description
- metadata
- order_details
- customer_id
- connector
- payment_method
- payment_method_type

Apart from these fields, extra fields have to be added
- business_label
- business_country
- business_sub_label
- setup_future_usage
- capture_method
- authentication_type
- connector_transaction_id
- Email

### Possible Implementation

The fields have to be added in this `ForeignFrom` conversion https://github.com/juspay/hyperswitch/blob/d30fefb2c08d4a086f4d8c0519196d83fa228d45/crates/router/src/core/payments/transformers.rs#L661

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by harshapathuri86** [comment]
Hey, I want to take this up. Will do it by tonight or tomorrow morning.

**Comment by harshapathuri86** [comment]
hi, there is no email field in PaymentIntent or PaymentAttempt.

**Comment by Narayanbhat166** [comment]
Sure, I will be assigning this to you!

**Comment by Narayanbhat166** [comment]
> hi, there is no email field in PaymentIntent or PaymentAttempt.

So to get the email is a customer related information. This would be stored in the `customers` table. It would be an additional database call to fetch email for each customer. Now that I think of it, email is not a must have field in payments list.  You can go ahead with the fields that are available in `PaymentIntent` and `PaymentAttempt`.
