### ISSUE TITLE
[FEATURE] Use empty enums instead of unit structs for PII masking strategies

### ISSUE THREAD

**Issue by vspecky** [juspay/hyperswitch#1973]
### Feature Description

Currently, we make use of unit structs that implement the `masking::Strategy<T>` trait to represent PII masking strategies. We would like to replace these with empty enums instead (So `struct MyStrategy;` becomes `enum MyStrategy {}`).

The difference between the two is that you can still construct a value out of a unit struct, but you can never construct a value out of an empty enum (since it has no variants to construct). However, you can still use empty enums as type parameters to generic constructs like the `masking::Secret<Data, Strategy>` type.

The argument against this is that we wouldn't be able to construct a `dyn masking::Strategy<T>`, but ideally, owing to the current implementation of PII masking in Hyperswitch, we should never have the need to obtain a `dyn masking::Strategy<T>` trait object.

### Possible Implementation

For all unit structs that implement `masking::Strategy<T>`, convert them to unit enums.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Shounmay** [comment]
Can i work on this issue?

**Comment by SanchithHegde** [comment]
Sure @Shounmay, will assign this to you.

**Comment by nain-F49FF806** [comment]
The unconstructability of empty enum in safe code is pretty cool. And I see how they are a better fit here. Good stuff.

That did make me curious, though. Is there any clear disadvantage to using unit structs, other than the conceptual tidyness of empty enums. 

Unit structs are [zero sized](https://doc.rust-lang.org/nomicon/exotic-sizes.html#zero-sized-types-zsts), so thankfully won't be taking any memory. Would there be any other reason to avoid using units in practice that we should consider.

**Comment by vspecky** [comment]
@nain-F49FF806 I can't really think of any other disadvantages off the top of my head. And it's not necessarily wrong to continue using unit structs here, but like you mentioned, empty enums are just conceptually tidier and their unconstructability is conformant to how we like to think about masking strategies, as in, they're.. well.. *strategies*, as opposed to something tangible.
