### ISSUE TITLE
Implement `BusinessProfileInterface` for `MockDb`

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#2039]
Spin off of #172 

Implement the missing implementation of MockDb for business profiles.
https://github.com/juspay/hyperswitch/blob/b8501f6ae6c0af0804d7f1e7cf9f50ebd303bf94/crates/router/src/db/business_profile.rs#L114

**Comment by dalprahcd** [comment]
Hello @Narayanbhat166, can help with this issue? And if possible, could you provide more documentation about it?

**Comment by Narayanbhat166** [comment]
Sure. I have assigned this to you.

To implement the functions you will have to imititate the funcionalities of the database without actually using the database functions, but by using data structures like hashmap, vectors etc. You can look at how other mock db implementations are done and do the same for this.
