### ISSUE TITLE
[FEATURE] log "MERCHANT_ID_NOT_IN_FLOW" if merchant_id is not found

### ISSUE THREAD

**Issue by Abhicodes-crypto** [juspay/hyperswitch#2153]
### Feature Description

Here,
https://github.com/juspay/hyperswitch/blob/9b92d046de9fb794d67163582af4360d5e558037/crates/router/src/services/api.rs#L729

Instead of `unwrap_or("")`,  

### Possible Implementation

Change it to some const `MERCHANT_ID_NOT_FLOW`.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by anishrajan25** [comment]
This does not seem to be a big change. The only part is, that it would be good to discuss with one of the maintainers for this project what value should be used as the default value. For now, I believe `"MERCHANT_ID_NOT_FOUND"` would be good. I'll raise a PR for this
