### ISSUE TITLE
[BUG] merchant account delete does not delete the `merchant_key_store`

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#2154]
### Bug Description

When a merchant is created a `merchant_key_store` is created, which goes along with the `merchant_account`. But when the merchant account is deleted, the key store is not deleted. 

### Expected Behavior

Both merchant account and key store should be delted.

### Actual Behavior

The key store still exists. 

### Steps To Reproduce

- Create a merchant account.
- Delete the merchant account.

### Environment

Local

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by dalprahcd** [comment]
Hello @Narayanbhat166 I would like to help with this issue.

**Comment by Narayanbhat166** [comment]
Sure @dalprahcd I have assigned this to you. 
Try to do this in a transaction if possible. Refer to this issue for more information https://github.com/juspay/hyperswitch/issues/1793

**Comment by dalprahcd** [comment]
@Narayanbhat166 could you assist me further?

Should I create a `delete_merchant_key_store_by_merchant_id` function in the [crates/router/src/types/storage/merchant_key_store.rs](https://github.com/juspay/hyperswitch/blob/272f5e4c1f34710fe13b1ede1b938d2f0b76e251/crates/router/src/types/storage/merchant_key_store.rs#L1)

And then call it here:
https://github.com/juspay/hyperswitch/blob/272f5e4c1f34710fe13b1ede1b938d2f0b76e251/crates/router/src/core/admin.rs#L461C1-L474C2

**Comment by SanchithHegde** [comment]
> Should I create a `delete_merchant_key_store_by_merchant_id` function in the [crates/router/src/types/storage/merchant_key_store.rs](https://github.com/juspay/hyperswitch/blob/272f5e4c1f34710fe13b1ede1b938d2f0b76e251/crates/router/src/types/storage/merchant_key_store.rs#L1)

@dalprahcd A couple of corrections:

1. You can implement a `delete_by_merchant_id()` method on `MerchantKeyStore` in the `diesel_models` crate [here](https://github.com/juspay/hyperswitch/blob/d40fae87feb509718059ab2d72539f37f26a8251/crates/diesel_models/src/query/merchant_key_store.rs). You can make use of the [`generic_delete()`](https://github.com/juspay/hyperswitch/blob/d40fae87feb509718059ab2d72539f37f26a8251/crates/diesel_models/src/query/generics.rs#L276) function to delete the merchant key store entry. (Refer to usages of the `generic_delete()` function to understand how it can be called.)
2. You can then add `delete_merchant_key_store_by_merchant_id()` as a trait method on the `MerchantKeyStoreInterface` trait and implement it [here](https://github.com/juspay/hyperswitch/blob/d40fae87feb509718059ab2d72539f37f26a8251/crates/router/src/db/merchant_key_store.rs).

> And then call it here:
> 
> [`272f5e4`/crates/router/src/core/admin.rs#L461C1-L474C2](https://github.com/juspay/hyperswitch/blob/272f5e4c1f34710fe13b1ede1b938d2f0b76e251/crates/router/src/core/admin.rs#L461C1-L474C2)

Correct. We'd preferably want this to happen in a transaction, but we can take it up in a separate issue and PR, not a problem.
