### ISSUE TITLE
[FEATURE]: [ACI] Currency Unit Conversion

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2198]
### :memo: Feature Description

- Each currency can be described in terms of base or minor units. 
- For instance, when dealing with USD currency, the Cent is considered as the minor unit, while the Dollar is considered the base unit. 
- In Hyperswitch, the amount value is expected to be always provided in minor units. 
- For example: In USD, If the amount is 1 in base unit (Dollar), then it will be equivalent to 100 in minor units (Cent)
- Some of the connectors integrated require the amount to be converted to a desirable unit before being passed to them. 
- We have functions `to_currency_base_unit` and `to_currency_lower_unit` in place to convert the minor unit amount to its decimal equivalent and vice versa. These conversions are handled explicitly based on the connector.

### :hammer: Possible Implementation

- ConnectorCommon trait have been implemented for the connector. 
- This trait contains `get_currency_unit` method. This method needs to be implemented. 
- It will define what type of conversion needs to be done during `connector_router_data` creation. Concurrently handle the creation of `connector_router_data` to be passed for the connector request body creation.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2196

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by AyushK-101** [comment]
@Sakilmostak I would like to work on this.

**Comment by SanchithHegde** [comment]
Sure @AyushK-101, I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, our [Discord server](https://discord.com/invite/wJZ7DVW8mm), or our [Slack workspace](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with.

**Comment by VedantKhairnar** [comment]
Hey @AyushK-101  ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by swangi-kumari** [comment]
Hello @AyushK-101  , 
We didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by Himanshu-370** [comment]
Can I be assigned?

**Comment by Harshwardhan9431** [comment]
@SanchithHegde Can you assign me this issue want to contribute to my 3rd PR.

**Comment by deepanshu-iiitu** [comment]
Hey @Harshwardhan9431 , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with
