### ISSUE TITLE
[FEATURE]: [Cybersource] Currency Unit Conversion

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2222]
### :memo: Feature Description

- Each currency can be described in terms of base or minor units. 
- For instance, when dealing with USD currency, the Cent is considered as the minor unit, while the Dollar is considered the base unit. 
- In Hyperswitch, the amount value is expected to be always provided in minor units. 
- For example: In USD, If the amount is 1 in base unit (Dollar), then it will be equivalent to 100 in minor units (Cent)
- Some of the connectors integrated require the amount to be converted to a desirable unit before being passed to them. 
- We have functions `to_currency_base_unit` and `to_currency_lower_unit` in place to convert the minor unit amount to its decimal equivalent and vice versa. These conversions are handled explicitly based on the connector.

### :hammer: Possible Implementation

- ConnectorCommon trait have been implemented for the connector. 
- This trait contains `get_currency_unit` method. This method needs to be implemented. 
- It will define what type of conversion needs to be done during `connector_router_data` creation. Concurrently handle the creation of `connector_router_data` to be passed for the connector request body creation.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2196

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue! Could you please assign it to me?"

**Comment by AkshayaFoiger** [comment]
Hey @TechWizard9999  , I see that you're already assigned to #2352. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2352 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by mdrokz** [comment]
> Hey @TechWizard9999 , I see that you're already assigned to #2352. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2352 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

Hi can i work on this issue if it hasnt been assigned to anybody ?

**Comment by AkshayaFoiger** [comment]
Hey @mdrokz, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @mdrokz ,
Let us know if you face any issues. Happy to help! : )

**Comment by mdrokz** [comment]
> Hey @mdrokz ,
> Let us know if you face any issues. Happy to help! : )

Hey sure I'm still going through the codebase and trying to understand how everything works I will let you know if I encounter any issue. Thanks :)

**Comment by mdrokz** [comment]
> Hey @mdrokz , Let us know if you face any issues. Happy to help! : )

Hi i went through the codebase and set up my merchant account & connector for cybersource i made a payment request as well. There are few things i dont understand

1. i provided base unit USD for payment through the cybersource connector if cybersource requires the payments in minor unit which is cents shouldnt the payment fail ? in my case the payment was successful.
2. how do i test the currency unit for cybersource when making payments.

Thanks

**Comment by Sakilmostak** [comment]
Hello @mdrokz, Hyperswitch takes amount in minor unit, the payment shouldn't necessarily fail if you don't change the unit as desired by the connector since we are passing the amount anyways but by not handling the unit conversion, we would send wrong amount for the transaction. This can be checked through the response since they will display the same amount we provided to them in the connector's request, which will not be equal to the amount provided to Hyperswitch. Basically, in testing, you need to make sure, the amount we are receiving in the response should be equal to the amount send in the Hyperswitch's payment request under same unit.

**Comment by swangi-kumari** [comment]
Hello @mdrokz, Are you comparing Hyperswitch payment request amount request with connector (Cybersouce) payment request amount? 
Match the amount you are passing in Hyperswitch payment request with the response you are getting from connector. Both should be same.

**Comment by mdrokz** [comment]
> Hello @mdrokz, Are you comparing Hyperswitch payment request amount request with connector (Cybersouce) payment request amount? Match the amount you are passing in Hyperswitch payment request with the response you are getting from connector. Both should be same.



> Hello @mdrokz, Are you comparing Hyperswitch payment request amount request with connector (Cybersouce) payment request amount? Match the amount you are passing in Hyperswitch payment request with the response you are getting from connector. Both should be same.

Hello @swangi-kumari yes the amount is same i was confused because of that i re-visited the code again and now it makes sense. currently theres no router data implementation for cybersource correct ?

**Comment by mdrokz** [comment]
> Sure, @mdrokz 
> Yes currently theres no router data implementation for cybersource, you need to implement that.

Alright thanks for the help :)
