### ISSUE TITLE
[FEATURE]: [Multisafepay] Currency Unit Conversion

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2232]
### :memo: Feature Description

- Each currency can be described in terms of base or minor units. 
- For instance, when dealing with USD currency, the Cent is considered as the minor unit, while the Dollar is considered the base unit. 
- In Hyperswitch, the amount value is expected to be always provided in minor units. 
- For example: In USD, If the amount is 1 in base unit (Dollar), then it will be equivalent to 100 in minor units (Cent)
- Some of the connectors integrated require the amount to be converted to a desirable unit before being passed to them. 
- We have functions `to_currency_base_unit` and `to_currency_lower_unit` in place to convert the minor unit amount to its decimal equivalent and vice versa. These conversions are handled explicitly based on the connector.

### :hammer: Possible Implementation

- ConnectorCommon trait have been implemented for the connector. 
- This trait contains `get_currency_unit` method. This method needs to be implemented. 
- It will define what type of conversion needs to be done during `connector_router_data` creation. Concurrently handle the creation of `connector_router_data` to be passed for the connector request body creation.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2196

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by DostoevskyOnLinux** [comment]
I'll take this one, please!

**Comment by swangi-kumari** [comment]
Hey @DostoevskyOnLinux , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by DostoevskyOnLinux** [comment]
Hey, @swangi-kumari, I asked if I could have this one when I thought #2237 had been taken already. I should have deleted my comment. Can I be unassigned so someone else can have this one? I'll finish 2237.

**Comment by SanchithHegde** [comment]
Sure @DostoevskyOnLinux. Feel free to let us know if you're interested in taking this up once you close #2237.

**Comment by saikiranpatil** [comment]
@Sakilmostak @SanchithHegde @swangi-kumari can i work on this?

**Comment by shivam-jainn** [comment]
Hey , 
Can you please assign me this issue !

**Comment by zakhaev26** [comment]
Can you please assign me this issue @SanchithHegde

**Comment by SanchithHegde** [comment]
@shivam-jainn Sure, I'll assign this to you. You can reach out to us on this issue thread or on our Discord server in case of any queries.

@zakhaev26 We assign issues on a first come first serve basis, feel free to check out any of our other open issues.

**Comment by ArjunKarthik** [comment]
Resolved by [#2679](https://github.com/juspay/hyperswitch/pull/2679)
