### ISSUE TITLE
[FEATURE]: [Noon] Currency Unit Conversion

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2237]
### :memo: Feature Description

- Each currency can be described in terms of base or minor units. 
- For instance, when dealing with USD currency, the Cent is considered as the minor unit, while the Dollar is considered the base unit. 
- In Hyperswitch, the amount value is expected to be always provided in minor units. 
- For example: In USD, If the amount is 1 in base unit (Dollar), then it will be equivalent to 100 in minor units (Cent)
- Some of the connectors integrated require the amount to be converted to a desirable unit before being passed to them. 
- We have functions `to_currency_base_unit` and `to_currency_lower_unit` in place to convert the minor unit amount to its decimal equivalent and vice versa. These conversions are handled explicitly based on the connector.

### :hammer: Possible Implementation

- ConnectorCommon trait have been implemented for the connector. 
- This trait contains `get_currency_unit` method. This method needs to be implemented. 
- It will define what type of conversion needs to be done during `connector_router_data` creation. Concurrently handle the creation of `connector_router_data` to be passed for the connector request body creation.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2196

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by DostoevskyOnLinux** [comment]
Hello! I'd like to give this a shot. Would someone please assign it to me?

Thank you!

**Comment by Sakilmostak** [comment]
Hi @DostoevskyOnLinux , I have assigned this issue to you.

**Comment by heckarman** [comment]
Hey @Sakilmostak sir, I've already raised a PR that resolves this issue.
Thanks!

**Comment by DostoevskyOnLinux** [comment]
Hmm. I can find another one to fix, I guess...

**Comment by Sakilmostak** [comment]
Hey @DostoevskyOnLinux for any problem in regards to implementation you can hit to our official [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) or [discord](https://discord.gg/wJZ7DVW8mm) server. We will be glad to help : )

**Comment by swangi-kumari** [comment]
Hey @DostoevskyOnLinux ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by SagarDevAchar** [comment]
Hey, I'd like to work on this!
I have a PR waiting to be merged and would love to contribute my 10th PR to Hyperswitch!

**Comment by SanchithHegde** [comment]
Sure @SagarDevAchar, I'll assign this to you.

**Comment by Sakilmostak** [comment]
Closing because currency conversion implementation have changed
