### ISSUE TITLE
[FEATURE]: [Shift4] Currency Unit Conversion

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2245]
### :memo: Feature Description

- Each currency can be described in terms of base or minor units. 
- For instance, when dealing with USD currency, the Cent is considered as the minor unit, while the Dollar is considered the base unit. 
- In Hyperswitch, the amount value is expected to be always provided in minor units. 
- For example: In USD, If the amount is 1 in base unit (Dollar), then it will be equivalent to 100 in minor units (Cent)
- Some of the connectors integrated require the amount to be converted to a desirable unit before being passed to them. 
- We have functions `to_currency_base_unit` and `to_currency_lower_unit` in place to convert the minor unit amount to its decimal equivalent and vice versa. These conversions are handled explicitly based on the connector.

### :hammer: Possible Implementation

- ConnectorCommon trait have been implemented for the connector. 
- This trait contains `get_currency_unit` method. This method needs to be implemented. 
- It will define what type of conversion needs to be done during `connector_router_data` creation. Concurrently handle the creation of `connector_router_data` to be passed for the connector request body creation.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2196

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue! Could you please assign it to me?"

**Comment by AkshayaFoiger** [comment]
Hey @TechWizard9999  , I see that you're already assigned to #2352. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2352 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by sanketmp** [comment]
can I take this?

**Comment by Sakilmostak** [comment]
Hey @sanketmp , sure, I have assigned this issue to you.

**Comment by Sakilmostak** [comment]
Closing because currency conversion implementation have changed
