### ISSUE TITLE
[REFACTOR]: [Airwallex] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2262]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Vishalk91-4** [comment]
@VedantKhairnar, could you please assign this issue to me

**Comment by Sakilmostak** [comment]
Hello @Vishalk91-4 , I have assigned this issue to you👍

**Comment by Sakilmostak** [comment]
Hey @Vishalk91-4 it seems like you already have a [PR](https://github.com/juspay/hyperswitch/pull/2554) in review which you have not addressed (CI checks not passed). I would suggest to be atleast done with the reviewing of the PR to move on to next

**Comment by swangi-kumari** [comment]
Hello @Vishalk91-4 ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by Vishalk91-4** [comment]
@swangi-kumari, yes I'm working on it, I'll submit a PR also, a draft PR if you want can be submitted too, actually I was resolving the issue of my PR in hyperswitch in other PR also

**Comment by deepanshu-iiitu** [comment]
Hey @Vishalk91-4 
Just checking in - are you working on it? Do you need help from our side?

**Comment by deepanshu-iiitu** [comment]
Hello @Vishalk91-4  , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by Hangsaai** [comment]
Hey @deepanshu-iiitu ,
"Could you please assign this issue to me? My previous PR has been merged, and I want to work on it now."

**Comment by Vishalk91-4** [comment]
> Hello @Vishalk91-4 , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

Sorry, I'm resolving errors in the other issue in Hyperswitch
#2226

**Comment by HeetVekariya** [comment]
@deepanshu-iiitu i can also make PR for this issue, after generating the PR for the first one.
can you please let me know that for which of the below, i have to handle the default case ?

1.
![image](https://github.com/juspay/hyperswitch/assets/91054457/60856dda-5fde-4331-8315-cc7ece0bfb92)

2.
![image](https://github.com/juspay/hyperswitch/assets/91054457/c7934418-826a-4206-9b2f-48d0c7576d7f)

**Comment by swangi-kumari** [comment]
Completed in this [PR](https://github.com/juspay/hyperswitch/pull/2703)
