### ISSUE TITLE
[REFACTOR]: [CryptoPay] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2267]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by heysagnik** [comment]
I would like to work on this issue.

**Comment by Sakilmostak** [comment]
Sure @heysagnik , I have assigned this issue to you

**Comment by swangi-kumari** [comment]
Hey @heysagnik ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by ashutuptiwari** [comment]
assign it to me

**Comment by HeetVekariya** [comment]
- @ashutuptiwari I think that the issue asks to handle the default cases where error is generated.
 - You can just simply search for this ```errors::connectorerror::``` , and you may find the match case which you have to handle default cases.

**Comment by ashutuptiwari** [comment]
this?
![image](https://github.com/juspay/hyperswitch/assets/106370097/3f118218-41f2-435e-ae8b-e61586e37788)

**Comment by ashutuptiwari** [comment]
Also, assign this issue to me @swangi-kumari

**Comment by swangi-kumari** [comment]
Hello @ashutuptiwari , Sure I have assigned this issue to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by ashutuptiwari** [comment]
Can you clarify the doubts that I mentioned in the previous messages in this thread? @swangi-kumari

**Comment by swangi-kumari** [comment]
Sure @ashutuptiwari ,
For this issue you just have to handle for the Payment Methods default cases.  So handle each and every variant explicitly for that part.

**Comment by ashutuptiwari** [comment]
Alrighty

**Comment by ashutuptiwari** [comment]
> this?
> ![image](https://github.com/juspay/hyperswitch/assets/106370097/3f118218-41f2-435e-ae8b-e61586e37788)
> 

This one?

**Comment by swangi-kumari** [comment]
Yes @ashutuptiwari
