### ISSUE TITLE
[REFACTOR]: [Cybersource] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2268]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by KGoutham7214** [comment]
i want to work on this can you please describe more about the issue and assign it to me

**Comment by AkshayaFoiger** [comment]
Hey @KGoutham7214, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by swangi-kumari** [comment]
Hey @KGoutham7214 . Are you still working on this issue?
Let us know if you face any issues. Happy to help! : )

**Comment by HeetVekariya** [comment]
- I have work two issues, similar like this.
- I have already find the cases that should be added against the default case.

![image](https://github.com/juspay/hyperswitch/assets/91054457/4f0ea84d-c58e-4297-8d38-14ab6e1a1cbb)

- @KGoutham7214, if you are still working on this issue, then you can take the hint from the screenshort.
- If he doesn't continue to work on this issue, so @swangi-kumari can you please assign me this issue.

**Comment by KGoutham7214** [comment]
hey @HeetVekariya  let's connect and work on this together

**Comment by HeetVekariya** [comment]
@KGoutham7214 we can connect on discord, i have already joined the hyperswitch discord server.

**Comment by deepanshu-iiitu** [comment]
Hey @KGoutham7214 
Just checking in - are you working on it? Do you need help from our side?

**Comment by KGoutham7214** [comment]
No I'm not able to do it

**Comment by TejasMate** [comment]
@deepanshu-iiitu 
Could you please assign this issue to me?

**Comment by Rutam21** [comment]
Hello Team, I am clear about the changes and would like to work on this. Thanks.

cc: @VedantKhairnar

**Comment by deepanshu-iiitu** [comment]
Hey @TejasMate 
Just checking in - are you working on it? Do you need help from our side?

**Comment by TejasMate** [comment]
@deepanshu-iiitu i submitted PR #2705 for this issue

**Comment by VedantKhairnar** [comment]
@deepanshu-iiitu Will you pls check #2705 and get it merged.
@Rutam21 As Tejas is already working on it, we will give him preference. If it happens that the things aren't resolved till the end moment of hacktoberfest then we will assign it to you and will merge yours, before the end of hacktoberfest.
Thanks for understanding.
