### ISSUE TITLE
[REFACTOR]: [Nexi nets] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2275]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Harshwardhan9431** [comment]
Hey @Sakilmostak I would like to contribute to this.
Can you assign this to me?

**Comment by Sakilmostak** [comment]
Hello @Harshwardhan9431 , I have assigned this issue to you

**Comment by Harshwardhan9431** [comment]
Hey so while going through the file in `connector/nexinets/transformers.rs` there are many default cases so is it required to handle all the cases or only some specific ones.

**Comment by swangi-kumari** [comment]
Hey @Harshwardhan9431,
Yes there are many default cases, but for this issue you just have to handle for the Payment Methods and Payment Method type default cases. So handle each and every variant explicitly for that part.
Feel free to ask any doubt. 
Happy to help:)

**Comment by Harshwardhan9431** [comment]
Hey folks, can you please review the PR related to this issue?
https://github.com/juspay/hyperswitch/pull/2639

**Comment by swangi-kumari** [comment]
Sure @Harshwardhan9431
