### ISSUE TITLE
[REFACTOR]: [NMI] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2276]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Cioraz** [comment]
Hey, Im interested in taking up this issue

**Comment by AkshayaFoiger** [comment]
Hey @Cioraz, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Cioraz** [comment]
Just a follow up question,
The changes have to be made to line 120 in hyperswitch/crates/router/src/connector/nmi/transformer.rs in which I must match the errors for applepay and gpay.

![image](https://github.com/juspay/hyperswitch/assets/76161837/8744f376-9bd3-4f14-b32e-6f880c120866)




And these the error changes for abandoned,cancelled,in_progress... fin lines 657

![image](https://github.com/juspay/hyperswitch/assets/76161837/c98fead3-4b1e-4ee0-8ef6-c79e505be51c)

Am i right?

**Comment by AkshayaFoiger** [comment]
@Cioraz you are right! You have to make the changes  at line 120 and also line 115. You have to match errors for all unhandled variations of `api_models::payments::WalletData` and `api::PaymentMethodData`

**Comment by Cioraz** [comment]
So Something like this would fix right?
Please correct me if im wrong as im still a beginner at rust

![Screenshot from 2023-10-04 23-39-44](https://github.com/juspay/hyperswitch/assets/76161837/bc577129-b10d-4e73-bc19-e85eb287c687)

**Comment by AkshayaFoiger** [comment]
Hi @Cioraz,

You need to remove the default arm of the match statement and fill it with all possible values of WalletData. Your implementation is expected to be similar to 

<img width="1387" alt="Screenshot 2023-10-05 at 12 35 36 PM" src="https://github.com/juspay/hyperswitch/assets/131388445/568ccc52-1373-4357-84e1-8741f63bb78d">

Here I have included a match arm for `AliPayQr` and `AliPayRedirect`.  We expect you to fill all other match arms.
`Note:To check for variations, do a command click on WalletData `

Same implementation implies for line 120. Hope this answers you query.

**Comment by Cioraz** [comment]
Thanks a lot for the response will resolve it now

**Comment by srujanchikke** [comment]
Hey @Cioraz ,

We are glad you've raised a PR , May i know the reason why did you close the PR . We would be happy to help you out !

**Comment by Cioraz** [comment]
Sorry for the issue, i had forgotten to run cargo clippy to check so i just wanted to redo that, will soon raise another PR.

**Comment by Cioraz** [comment]
![image](https://github.com/juspay/hyperswitch/assets/76161837/2f458a28-38f5-4545-ba3e-830fab2da446)
Could you help me with this when cargo building.

**Comment by srujanchikke** [comment]
> Sorry for the issue, i had forgotten to run cargo clippy to check so i just wanted to redo that, will soon raise another PR.

You can reopen the same pr and push more commits with working code . 
Coming to the issue you're facing , use a double colon instead: `::` after `errors` in line 140 .
