### ISSUE TITLE
[REFACTOR]: [Noon] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2277]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by kaustubh1106** [comment]
Sir, please assign this issue to me!

**Comment by Sakilmostak** [comment]
Sure @kaustubh1106 , I have assigned this issue to you👍

**Comment by swangi-kumari** [comment]
Hello @kaustubh1106 ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by Hangsaai** [comment]
Hey can you assign This issue to me @swangi-kumari as I have already created one PR

**Comment by swangi-kumari** [comment]
> Hello @kaustubh1106 , Are you still working on this issue? Please let us know if you need any help:)

Hello @kaustubh1106  , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by SagarDevAchar** [comment]
Hey, I'd like to work on this!
I have PRs waiting to be merged

**Comment by Hangsaai** [comment]
Was this being served on a first come first basis or can anybody directly raise a PR to any issue?

**Comment by SagarDevAchar** [comment]
> Hey can you assign This issue to me @swangi-kumari as I have already created one PR

Did not see your comment @Hangsaai. Apologies!

**Comment by Hangsaai** [comment]
Hey @SagarDevAchar you can reopen your PR buddy. I have got another issue and anyway you have created the PR already that's why deleted the comment it's fine dude

**Comment by swangi-kumari** [comment]
Hey @SagarDevAchar ,
I have assigned this issue to you.
In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with.
