### ISSUE TITLE
[REFACTOR]: [Nuvei] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2278]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by HeetVekariya** [comment]
@Sakilmostak If i work on this issue, then i have to implement the same code as this https://github.com/juspay/hyperswitch/pull/1955/commits/4c035c932c760398b90fbc5967963041489eebdb , right ?

**Comment by Sakilmostak** [comment]
Hello @HeetVekariya , it is similar but you only need to take care of variant against fields which require explicit naming such as `payment_method_data` or `bank_names`. If you would like, I can assign you this issue

**Comment by HeetVekariya** [comment]
@Sakilmostak i can see that many issues (like: Use connector_request_reference_id as reference to the connector) were assigned one week ago and no response back to you.
They are easy to start with so i am thinking to start with one of them, if no one is working on that issues, if you can assign one of them to me.

**Comment by Sakilmostak** [comment]
Hey @HeetVekariya, currently we are still reviewing for what issue to claim so currently we are unable to assign those issues to you. You can take reference from #2463 for the implementations of this issue, and all the variants required to fill in the statement are present in the definition of the the enum variables itself. We encourage you to have a try since one can feel overwhelmed out of context but with proper help Im sure anything can be resolved.

**Comment by HeetVekariya** [comment]
Okay, so let's try it out. Can you please assign it to me.

**Comment by Sakilmostak** [comment]
Sure @HeetVekariya , I have assigned this to you. For any query you can raise it in this thread
