### ISSUE TITLE
[REFACTOR]: [Opayo] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2279]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Abhiramjampani** [comment]
@AkshayaFoiger @Sakilmostak @VedantKhairnar 
I would be delighted to work on this issue
so kindly assign me this issue
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Abhiramjampani , I see that you're already assigned to https://github.com/juspay/hyperswitch/issues/2346. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on https://github.com/juspay/hyperswitch/issues/2346 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by amaan14999** [comment]
Hi @AkshayaFoiger. I would be delighted to work on this issue. My previous PR is under review and in merging process.

**Comment by amaan14999** [comment]
Hey @Sakilmostak, thanks for the update but the issue has not yet been assigned to me.

**Comment by amaan14999** [comment]
@Sakilmostak @VedantKhairnar @AkshayaFoiger can this issue be please assigned to me?

**Comment by SanchithHegde** [comment]
@amaan14999 Done, sorry about the confusion.

**Comment by Hangsaai** [comment]
Hey @swangi-kumari can you assign this to me as I have alredy raised a PR and want to work on this

**Comment by amaan14999** [comment]
Hey @swangi-kumari, I tried but was not able to resolve the issue since I am new to Rust. Kindly unassign me.

**Comment by swangi-kumari** [comment]
> Hey @swangi-kumari, I tried but was not able to resolve the issue since I am new to Rust. Kindly unassign me.

Sure, Glad that you tried:)

**Comment by HeetVekariya** [comment]
@swangi-kumari can you please assign me this issue, as i have worked on the similar issues.

**Comment by deepanshu-iiitu** [comment]
Hey @Hangsaai , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by deepanshu-iiitu** [comment]
> @swangi-kumari can you please assign me this issue, as i have worked on the similar issues.

Actually we assign the issue on FCF basis. If you are interested you can pick some other open issues.

**Comment by HeetVekariya** [comment]
> > @swangi-kumari can you please assign me this issue, as i have worked on the similar issues.
> 
> Hey @HeetVekariya ,
> Actually we assign the issue on FCF basis. If you are interested you can pick some other open issues.

No worries, I haven't seen that comment
