### ISSUE TITLE
[REFACTOR]: [Payeezy] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2281]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Sakilmostak** [comment]
Hello @itsjustayaan , I have assigned this issue to you

**Comment by swangi-kumari** [comment]
Hey @itsjustayaan, are you still working on this issue?
Please let us know if you need any help.

**Comment by HeetVekariya** [comment]
- @swangi-kumari If no one is working on this issue, then i can work on this as i have already worked on the similar type issues.
- I think that the issue asks to handle the below default case,
![image](https://github.com/juspay/hyperswitch/assets/91054457/c5b135c0-d443-41a6-a375-ba7cea1e2c33)
![image](https://github.com/juspay/hyperswitch/assets/91054457/0fccc89d-927f-4bfe-a4b3-0cf5cee04969)

- @itsjustayaan if you are working on this issue, then you can take reference from above screenshots.

**Comment by itsjustayaan** [comment]
thank you for the screenshot, I will take a note

**Comment by itsjustayaan** [comment]
I would like to drop this issue. Please unassign.

**Comment by HeetVekariya** [comment]
@swangi-kumari I would like to work on this issue, as i have already worked on the similar type of issues.

**Comment by swangi-kumari** [comment]
Hey @HeetVekariya ,
sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by HeetVekariya** [comment]
@swangi-kumari I have submitted the PR for the issue
