### ISSUE TITLE
[REFACTOR]: [Payme] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2282]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Charuhas10** [comment]
@Sakilmostak Assign this to me. Thank you :)

**Comment by HarshJainofficial** [comment]
**@Sakilmostak**  **Right now** I am looking for this opportunity
so please provide me the opportunity to work on this

**Comment by Sakilmostak** [comment]
Hi @HarshJainofficial , we assign the issues on `first come first serve` basis, if you would like I can assign you other issues of your preference

**Comment by swangi-kumari** [comment]
Hello @Charuhas10 ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by Charuhas10** [comment]
Is this correct? @Sakilmostak

![image](https://github.com/juspay/hyperswitch/assets/72398218/982170a4-302c-40b2-aa04-01a1964f2c57)

**Comment by SanchithHegde** [comment]
@Charuhas10 You can verify that your code compiles by running the command `cargo clippy --all-features --all-targets`, and you can run `cargo +nightly fmt` to ensure that your code is properly formatted.

Please refer to the [Cargo Commands](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md#cargo-commands) section on our contributing guidelines for more information.

**Comment by Charuhas10** [comment]
@SanchithHegde Already done, what are the next steps?

**Comment by heckarman** [comment]
Raising a PR

**Comment by Hangsaai** [comment]
If no one has raised the PR for this issue.
Can I pick this up?

**Comment by Charuhas10** [comment]
@swangi-kumari I am waiting for some to check if the workings I have done are correct or not, before raising a PR

**Comment by SanchithHegde** [comment]
@Charuhas10 Waiting for maintainer approval after a sending a screenshot with your changes is not a good idea, it's difficult for us to review as well. Go ahead and open your PR, and ensure CI checks are passing before requesting reviews from maintainers.

**Comment by Rutam21** [comment]
Hello Team, I am clear about the changes and would like to work on this. Thanks.

cc: @VedantKhairnar

**Comment by Rutam21** [comment]
@swangi-kumari Please assign this issue to me. Thanks.
