### ISSUE TITLE
[REFACTOR]: [Square] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2286]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Harshal0902** [comment]
Hi @Sakilmostak, I would like to work on this issue if available.

**Comment by Sakilmostak** [comment]
Hello @Harshal0902 , I have assigned this issue to you 👍

**Comment by homosapien14** [comment]
hey @Harshal0902 , are you still working on this issue?

**Comment by Harshal0902** [comment]
Hi @homosapien14, yes I am still working on this issue.

**Comment by deepanshu-iiitu** [comment]
Hey @Harshal0902 
Just checking in - are you working on it? Do you need help from our side?

**Comment by deepanshu-iiitu** [comment]
Hello @Harshal0902 , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by HeetVekariya** [comment]
@deepanshu-iiitu i would like to work on this issue.

**Comment by deepanshu-iiitu** [comment]
Hey @HeetVekariya , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by HeetVekariya** [comment]
@deepanshu-iiitu I have found 3 cases where default cases exists, so any specific one or all are needed to handle ?

1.
![image](https://github.com/juspay/hyperswitch/assets/91054457/161f73f5-4986-43b2-8bfe-fa885448d2ec)

2.
![image](https://github.com/juspay/hyperswitch/assets/91054457/4da10073-f572-4f26-9a7f-019daf1e0b39)

3.
![image](https://github.com/juspay/hyperswitch/assets/91054457/20045a6d-8958-4b73-905d-bd1873ca480a)

**Comment by deepanshu-iiitu** [comment]
@HeetVekariya All default cases should be handled.

**Comment by HeetVekariya** [comment]
we can close this as completed

**Comment by SanchithHegde** [comment]
Closing as completed in #2701.
