### ISSUE TITLE
[REFACTOR]: [Worldline] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2289]
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by nik132-eng** [comment]
can you assign me this issue?

**Comment by AkshayaFoiger** [comment]
Hey @nik132-eng , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @nik132-eng  ,
Let us know if you face any issues. Happy to help! : )

**Comment by VedantKhairnar** [comment]
Hey @nik132-eng ,
Just checking in - are you working on it or shall we consider reassigning it to someone else?

**Comment by swangi-kumari** [comment]
Hello @nik132-eng  , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by Hangsaai** [comment]
Hey @swangi-kumari can you assign this to me I am willing  to submit PR

**Comment by swangi-kumari** [comment]
Hey @Hangsaai  , sure! I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with.

**Comment by Hangsaai** [comment]
I am not able to push the code shows that I am not a collaborator @swangi-kumari

**Comment by Hangsaai** [comment]
![image](https://github.com/juspay/hyperswitch/assets/148209280/c6a2ecb7-8bff-4fe8-9c5c-faff9cb0b755)

**Comment by Hangsaai** [comment]
Yep I have already tried using Brave aswell but same problem occuring
![image](https://github.com/juspay/hyperswitch/assets/148209280/bb05bdeb-2b07-4f37-8944-7089a0248a04)

**Comment by SanchithHegde** [comment]
@Hangsaai Which repository are you trying to open a pull request from? Please ensure that you have write access to the repository you're opening the PR from.

**Comment by Hangsaai** [comment]
I am directly pushing to a branch in hyperswitch itself and then creating a PR to main @SanchithHegde

**Comment by SanchithHegde** [comment]
@Hangsaai Could you please share the link to the repository/branch you're pushing to?

**Comment by SanchithHegde** [comment]
@Hangsaai Ideally you shouldn't have had access to push a branch to our repository. Could you push the branch to your fork instead and open a PR from there?

**Comment by Hangsaai** [comment]
Yep I just figured it out I guess it's a vulnerability of github shouldn't have happened

**Comment by swangi-kumari** [comment]
Completed in [2674](https://github.com/juspay/hyperswitch/pull/2674)
