### ISSUE TITLE
[FEATURE]: [Authorizedotnet] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2292]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented. Please find api documentation for authorizedotnet [here](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card).  
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by AkshayaFoiger** [comment]
Hey @ShatilKhan , I see that you're already assigned to [#2241](https://github.com/juspay/hyperswitch/issues/2241) and are working on it. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on [#2241](https://github.com/juspay/hyperswitch/issues/2241) is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by amitroy-thedev** [comment]
@srujanchikke 
Assign this issue to me.
Thank you

**Comment by amitroy-thedev** [comment]
@srujanchikke 
Can you guide how do I make contribution

**Comment by srujanchikke** [comment]
Hey @amitroy-thedev , i have assigned this issue to you , Please let us know in case you have any questions, on this issue thread or on our Discord server.

**Comment by srujanchikke** [comment]
> @srujanchikke Can you guide how do I make contribution
Please refer this [Contributing guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by AkshayaFoiger** [comment]
Hi @SoundaryaKoutharapu ,

Please refer api docs of Authorizedotnet [here](https://developer.authorize.net/api/reference/index.html#payment-transactions)

**Comment by amitroy-thedev** [comment]
@VedantKhairnar 
Actually I'm new to Rust and the codebase is hard to digest but I'll surely make a PR soon..

**Comment by amitroy-thedev** [comment]
@srujanchikke 
Would you please guide me what need to be replace and should be added ?

**Comment by srujanchikke** [comment]
You can refer to this pr https://github.com/juspay/hyperswitch/pull/2512 . `refId` would be the merchant reference id according to api docs of [authroizedotnet](https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card) . You need to declare `refId` in `AuthorizedotnetPaymentsRequest` struct and map to `connector_request_reference_id` .

**Comment by amitroy-thedev** [comment]
Yes @deepanshu-iiitu 
Actually I want to know how to run or test the code in my pc locally

**Comment by Sakilmostak** [comment]
Hello @amitroy-thedev, we already have checks on Github to test the changes when PR is raised so you can skip it but if you still want to test then you can follow our [Postman Guide](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#try-out-our-apis)

**Comment by amitroy-thedev** [comment]
@Sakilmostak 
Can you please review my PR and if it is all right would you please merge it
