### ISSUE TITLE
[FEATURE]: [Bitpay] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2294]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Cioraz** [comment]
Hey, 
Could you assign me this issue?

**Comment by Sakilmostak** [comment]
Hi @Cioraz !, I have assigned this issue to you.

**Comment by VedantKhairnar** [comment]
Hey @Cioraz ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by Cioraz** [comment]
Yeah, sorry was a bit busy will continue work on it

**Comment by Himanshu-370** [comment]
Can I be assigned?

**Comment by Sakilmostak** [comment]
Hey @Cioraz, if you require help you can head to our official [discord](https://discord.com/invite/wJZ7DVW8mm) or [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) channel. We would be glad to help

**Comment by Cioraz** [comment]
Yeah sure, I'll take up another issue when I get some time off from college

**Comment by Sakilmostak** [comment]
Hello @Himanshu-370 , I have assigned this issue to you

**Comment by Himanshu-370** [comment]
I don't see any `attempt_id` or `payment_id` in the code. Neither is the `connector_request_reference_id`.

**Comment by Sakilmostak** [comment]
Hello @Himanshu-370 according to the [Bitpay](https://developer.bitpay.com/reference/create-an-invoice) docs, the request can have `orderId` field which can be used as reference to the transaction

**Comment by Himanshu-370** [comment]
> Hello @Himanshu-370 according to the [Bitpay](https://developer.bitpay.com/reference/create-an-invoice) docs, the request can have `orderId` field which can be used as reference to the transaction

Oh right! I forgot about the docs.😅

**Comment by Himanshu-370** [comment]
I cannot find `orderId` as well:(

**Comment by Sakilmostak** [comment]
@Himanshu-370 , you need to explicitly add this field to the payment request struct :)

**Comment by Himanshu-370** [comment]
Hey, I am having trouble understanding how to approach the situation here, is there any similar issue which is already fixed?

**Comment by deepanshu-iiitu** [comment]
Hey @Himanshu-370 
You can refer the following PR https://github.com/juspay/hyperswitch/pull/2631

**Comment by Himanshu-370** [comment]
Does this looks good?
I intialized a order_id variable and called it in inside the `get_crypto_specific_payment_data()` function.


![image](https://github.com/juspay/hyperswitch/assets/96609252/e3ae0b7b-05d0-49f4-8393-8f6d99dd9713)

![image](https://github.com/juspay/hyperswitch/assets/96609252/517b0389-f6f0-4030-af3b-bfaa4f460e2d)

**Comment by deepanshu-iiitu** [comment]
Yes @Himanshu-370 . Also please raise a PR and link it to this issue.
