### ISSUE TITLE
[FEATURE]: [Fiserv] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2298]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by sahil9001** [comment]
Can you assign this to me @Sakilmostak ?

**Comment by AkshayaFoiger** [comment]
Hey @sahil9001, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @sahil9001  ,
Let us know if you face any issues. Happy to help! : )

**Comment by sahil9001** [comment]
Hey, yes, can you give a brief about how I should approach to this problem?

**Comment by AkshayaFoiger** [comment]
Hello @sahil9001,
Thank you for getting in touch. To gain a comprehensive understanding of this issue, I would like to elucidate how it has been resolved in the context of Adyen.
On examining the [Adyen documentation](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments) regarding payment requests, it is evident that they accept a field known as reference within their API requests for creating a transaction. This reference serves as a means to specifically identify and reference individual payments, and thus, it can been aptly designated with the value of `connector_request_reference_id`. We have accordingly made the necessary modifications to the connector/adyen/transformer.rs file, to include reference field in both payment requests and responses. I recommend reviewing the details of these changes in this associated [Pull Request](https://github.com/juspay/hyperswitch/pull/2052).

Note: Some connectors may not necessitate a payment reference id in their payment requests. 

For specific guidance on the Fiserve connector, please refer here.

I hope this information proves helpful. In case you have any further queries, you can ask them on this issue thread, or on our discord server, or on slack whichever you are comfortable with

**Comment by sahil9001** [comment]
Hey thanks, is there a way to test my change? I wanted to test it out locally.

**Comment by Sakilmostak** [comment]
Hello @sahil9001 
You can checkout this [guide](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#try-out-our-apis) to test payments through our postman collection

**Comment by deepanshu-iiitu** [comment]
Hey @sahil9001 
Just checking in - are you working on it? Do you need help from our side?

**Comment by TejasMate** [comment]
Hey @deepanshu-iiitu 
Could you please assign this issue to me?

**Comment by sahil9001** [comment]
> Hey @sahil9001 Just checking in - are you working on it? Do you need help from our side?

yes, I am

**Comment by swangi-kumari** [comment]
Hey @TejasMate ,
Sure! I've assigned this to you. 
In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by TejasMate** [comment]
#2698
