### ISSUE TITLE
[FEATURE]: [GlobalPayments] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2300]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by amaan14999** [comment]
Please assign me this issue! @Sakilmostak

**Comment by Sakilmostak** [comment]
Hello @amaan14999, I have assigned this issue to you👍

**Comment by amaan14999** [comment]
Hey @Sakilmostak. I have made the changes but upon performing cargo checks, I am facing an error. Can you please help me out here?

```bash
hyperswitch on  main [!] via  v18.14.2 via 🦀 v1.73.0 took 20s
❯ cargo check --all-features
   Compiling git2 v0.17.2
    Checking zstd v0.12.3+zstd.1.5.2
   Compiling openssl-sys v0.9.90
    Checking foreign-types-shared v0.1.1
   Compiling openssl v0.10.55
   Compiling oid-registry v0.6.1
    Checking unicode-ident v1.0.9
    Checking color_quant v1.1.0
    Checking triomphe v0.1.8
    Checking png v0.16.8
   Compiling darling v0.20.1
   Compiling rust-embed-impl v6.6.0
   Compiling utoipa-swagger-ui v3.1.3
   Compiling tempfile v3.6.0
    Checking num-rational v0.3.2
error: failed to run custom build command for `openssl-sys v0.9.90`

Caused by:
  process didn't exit successfully: `C:\Users\Amaan\Documents\GitHub\hyperswitch\target\debug\build\openssl-sys-0f397f02f302ffcf\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'

  --- stderr
```

Screenshot:

![image](https://github.com/juspay/hyperswitch/assets/73187712/1ebdb22a-0c43-4976-b2f5-c9254c5e4433)
