### ISSUE TITLE
[FEATURE]: [Iatapay] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2302]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by AkshayaFoiger** [comment]
Hey @soumya-dash3, , I see that you're already assigned to #2295 and are working on it. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2295 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by SoumyoPurkayastha** [comment]
@AkshayaFoiger I'm interested to work on this issue. Can I be assigned this issue?

**Comment by Sakilmostak** [comment]
Hi @SoumyoPurkayastha , I have assigned this issue to you 👍

**Comment by SoumyoPurkayastha** [comment]
Thanks a lot for assigning me the issue, I'll start working on it right away.

I have a small doubt though. The IATA Pay API references that I could find don't explicitly mention if the field iataPayementId is necessarily returned for every payment request. Ref:
<img width="541" alt="image" src="https://github.com/juspay/hyperswitch/assets/59766344/c5d0d50c-64d3-4cfb-b371-6101538d8220">

So should I write a fallback code for the connector_response_reference_id field, and if so, is there any prescribed field to fallback to.

@AkshayaFoiger @Sakilmostak

**Comment by Sakilmostak** [comment]
Hello @SoumyoPurkayastha, for the fallback you can add the `merchantPaymentId` which we are already receiving in the response.

**Comment by daniloff200** [comment]
I finished issue, assigned to me, I can pick this one
But it feels like it has been fixed in #2524

**Comment by swangi-kumari** [comment]
Hey @daniloff200 ,
This issue is for `connector_request_reference_id` but #2524 is for connector_response_reference_id.

**Comment by daniloff200** [comment]
oh, my bad
Anyway, I'm available

cc @swangi-kumari

**Comment by swangi-kumari** [comment]
Hey @daniloff200 , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with
