### ISSUE TITLE
[FEATURE]: [Nuvei] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2309]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Himanshu-370** [comment]
I would like to be assigned for this issue.

**Comment by Himanshu-370** [comment]
As per my understanding, in the folder named "nuvei" with a file "transformers.rs", I just have to replace "attempt_id" or "payment_id" with "connector_request_reference_id", right ? @Sakilmostak  @VedantKhairnar

**Comment by AkshayaFoiger** [comment]
Hey @Himanshu-370, I've assigned this issue to you.  Indeed, your assessment is correct. You have to proceed in the same direction. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Himanshu-370** [comment]
@AkshayaFoiger I made the necessary changes and I am trying to make a PR, but do i need to create a new branch? It was not mentioned in the contributing.md file, i think. Can you help me here?

**Comment by SanchithHegde** [comment]
> [...] do i need to create a new branch?

@Himanshu-370 You can either choose to open a PR from your fork's `main` branch, or create a new branch for the changes for this issue. I'd suggest the latter, so that changes/commits for different issues/PRs reside on different branches, making it easier to manage.
