### ISSUE TITLE
[FEATURE]: [Opayo] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2310]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by kurayami07734** [comment]
I would like to work on this issue

**Comment by AkshayaFoiger** [comment]
Hey @kurayami07734, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @kurayami07734  ,
Let us know if you face any issues. Happy to help! : )

**Comment by kurayami07734** [comment]
Yeah, linux's OOM is killing the compilation process
Even with `cargo build -j 1`

**Comment by Sakilmostak** [comment]
Hey @kurayami07734 , if you are using linux distro, you can use this [guide](https://www.scaler.com/topics/how-to-increase-swap-space-in-linux/) and then try to run

**Comment by Charuhas10** [comment]
@Sakilmostak If this is free and earlier issue has been resolved, assign this to me :)

**Comment by kurayami07734** [comment]
@Sakilmostak adding the swapfile seems to have done the trick
It building now
I guess I'll another go at it

**Comment by Sakilmostak** [comment]
@kurayami07734 , Im glad that the guide has helped you

**Comment by Sakilmostak** [comment]
Hey @Charuhas10, sorry again, since the issue is stil being continued by @kurayami07734, can you pickup other unassigned issue, I would gladly assign them to you

**Comment by Sakilmostak** [comment]
This issue is closed since the flow required for the implementation is not merged.
