### ISSUE TITLE
[FEATURE]: [PayU] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2313]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by aniketh-varma** [comment]
Hi @Sakilmostak @VedantKhairnar, I would like to work on this issue.

**Comment by AkshayaFoiger** [comment]
Hey @aniketh-varma, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by srujanchikke** [comment]
Hi @aniketh-varma , 

Please refer api documentation of payu [here](https://developers.payu.com/en/restapi.html) .

**Comment by VedantKhairnar** [comment]
Hey @aniketh-varma  ,
Let us know if you face any issues. Happy to help! : )

**Comment by VedantKhairnar** [comment]
Hey @aniketh-varma ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by aniketh-varma** [comment]
Hi @VedantKhairnar, yes, I am still working on this. Apologies for the delay.

**Comment by VedantKhairnar** [comment]
No problem @aniketh-varma . Take your time.
Please let us know if you need any assistance. Happy to help!  : )

**Comment by swangi-kumari** [comment]
HEY @aniketh-varma ,
Are you still working on this issue? If you are done with it, you can raise a PR of it.

**Comment by swangi-kumari** [comment]
Hey @aniketh-varma , as we didn't got response from you, we are assigning this issue to @vinfinity7  .

**Comment by vinfinity7** [comment]
assign me this

**Comment by vinfinity7** [comment]
@swangi-kumari kindly review

**Comment by vinfinity7** [comment]
@srujanchikke kindly review pr

**Comment by gorakhnathy7** [comment]
Hey All, Freeing this Issue due to prolonged inactivity.

**Comment by nabeel001** [comment]
Hi @gorakhnathy7 , I would like to work on this issue. Kindly assign this to me.

**Comment by gorakhnathy7** [comment]
@nabeel001 Assigning this to you, thanks for your interest!

**Comment by nabeel001** [comment]
@gorakhnathy7 @Sakilmostak 
Kindly review the pull request.

**Comment by gorakhnathy7** [comment]
Hey @nabeel001,
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
