### ISSUE TITLE
[FEATURE]: [Rapyd] Use `connector_request_reference_id` as reference to the connector

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2315]
### :memo: Feature Description 

- We transmit our reference id from Hyperswitch to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
- Presently, there is a lack of uniformity in this process, as some implementations employ `payment_id` while others utilize `attempt_id`.
- This inconsistency arises from the fact that `payment_id` and `attempt_id` correspond to two distinct entities within our system.

### :hammer: Possible Implementation 

- To mitigate this confusion, we've introduced a new field called `connector_request_reference_id` in our RouterData. 
- This id should replace them as a reference id to the connector for payment request. 
- One might need to have exposure to api docs of the connector for which it is being implemented.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052

:bookmark: Note : All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by soumya-dash3** [comment]
Hello @Sakilmostak , can I be assigned this issue please?

**Comment by AkshayaFoiger** [comment]
Hey @soumya-dash3, , I see that you're already assigned to #2295 and are working on it. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2295 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by ankushbhardwaj408** [comment]
Hi @AkshayaFoiger i am new to open source ,eager to contribute.Seeking guidance to start my journey.Any help appreciated. Thank You!!

**Comment by AkshayaFoiger** [comment]
Hey @ankushbhardwaj408, 
Thank you for getting in touch. Certainly, issue #2315 presents itself as an excellent opportunity for initiating open-source contributions.
First I would recommend you to start with setting up hyperswitch in your [local system](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md) 

 To gain understanding of this Issue, I would like to elucidate how it has been resolved in the context of Adyen. On examining the [Adyen documentation](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md) regarding payment requests, it is evident that they accept a field known as reference within their API requests for creating a transaction. This reference serves is an id that we can pass in the request, as a means to specifically identify and reference individual payments, and thus, it can been aptly designated as a connector_request_reference_id. We have accordingly made the necessary modifications to the `connector/adyen/transformer.rs` file, to include reference field in both payment requests and responses. I recommend reviewing the details of these changes in this associated [Pull Request.](https://github.com/juspay/hyperswitch/pull/2052)

For specific guidance on the Rapyd connector, please refer [here](https://docs.rapyd.net/en/create-payment.html).

I hope this information proves helpful. In case you have any further queries, you can ask them on this issue thread, or on our discord server, or on slack whichever you are comfortable with

**Comment by AkshayaFoiger** [comment]
@ankushbhardwaj408 , Shall this issue to you?

**Comment by ankushbhardwaj408** [comment]
Hello @akshayfoiger thanks for your help. I would like to contribute. Please assign it over to me. If I encounter any problems I will contact you.

**Comment by AkshayaFoiger** [comment]
Hey @ankushbhardwaj408 , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Sakilmostak** [comment]
Hello @ankushbhardwaj408 , on reading through [Rapyd Api Docs](https://docs.rapyd.net/en/create-payment.html), they are passing a field called `merchant_reference_id` which can be used as reference to transaction

**Comment by deepanshu-iiitu** [comment]
Hey @ankushbhardwaj408 
Just checking in - are you working on it? Do you need help from our side?

**Comment by deepanshu-iiitu** [comment]
Hey @ankushbhardwaj408 
You can reference the following PR https://github.com/juspay/hyperswitch/pull/2631
It contains a similar implementation that is required for this issue.

**Comment by TejasMate** [comment]
hey @deepanshu-iiitu,  Could you please assign this issue to me? since @ankushbhardwaj408 is inactive

**Comment by deepanshu-iiitu** [comment]
Hey @TejasMate , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by swangi-kumari** [comment]
Hey @TejasMate ,
Are you still working on this issue?
Let us know if you need any help.

**Comment by dalprahcd** [comment]
Hello @swangi-kumari, can you assign this issue to me? I would like to help.

**Comment by Sakilmostak** [comment]
Hi @dalprahcd , sure, I will assign this issue to you.

**Comment by dalprahcd** [comment]
Hello @Sakilmostak sorry but I will not be able to help with this issue in the time being.

**Comment by nabeel001** [comment]
@Sakilmostak @AkshayaFoiger 
I would like to work on this issue. Can you assign it to me?

**Comment by Sakilmostak** [comment]
Sure @nabeel001 , assigning this issue to you 👍

**Comment by nabeel001** [comment]
@Sakilmostak @VedantKhairnar 
Kindly review my Pull request.

**Comment by gorakhnathy7** [comment]
Hey @nabeel001 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
