### ISSUE TITLE
[FEATURE]: [Bambora] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2324]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by tarunsinghofficial** [comment]
I'm happy to work on this issue, so kindly assign me this issue.
Thanks

**Comment by SanchithHegde** [comment]
Hey @tarunsinghofficial, since you're already assigned to #2332, we'll leave this open to other contributors for now. You may pick this up once your work on #2332 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you.

**Comment by urvashi2712** [comment]
I'm happy to work on this issue, so kindly assign me this issue Thanks

**Comment by AkshayaFoiger** [comment]
Hey @urvashi2712, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @urvashi2712  ,
Let us know if you face any issues. Happy to help! : )

**Comment by VedantKhairnar** [comment]
Hey @urvashi2712,
Just checking in - are you working on it or shall we consider reassigning it to someone else?

**Comment by Rutam21** [comment]
@VedantKhairnar If it's available for re-assignment, then I would love to take this up. I have completed my previous PRs. Thanks.

**Comment by Sakilmostak** [comment]
Hello @Rutam21, since it is still assigned to someone and one of the issues assigned to you still under review, we are unable to assign this to you right now but once the review is done, I can gladly assign you any issue which is not already picked👍

**Comment by Sangamesh26** [comment]
@urvashi2712 , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by Rutam21** [comment]
Yeah @Sangamesh26 . Please assign it to me. Thanks.

**Comment by swangi-kumari** [comment]
Hey @Rutam21, I have assigned this issue to you.
In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with.
