### ISSUE TITLE
[FEATURE]: [Bitpay] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2325]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by tarunsinghofficial** [comment]
I'm happy to work on this issue, so kindly assign me this issue.
Thanks

**Comment by SanchithHegde** [comment]
Hey @tarunsinghofficial, since you're already assigned to #2332, we'll leave this open to other contributors for now. You may pick this up once your work on #2332 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you.

**Comment by ashh1215** [comment]
Hey @SanchithHegde I'd like to work on this issue. Please assign it to me.

**Comment by AkshayaFoiger** [comment]
Hey @ashh1215, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @ashh1215 ,
Let us know if you face any issues. Happy to help! : )

**Comment by ashh1215** [comment]
Hey @VedantKhairnar 
So I was going though the Bitpay documentation to figure out what they're using as the reference id.
Problem is that I've gone through a lot of different areas in the documentation, but haven't been able to find one place where all the variables that are being used in the Hyperswitch code match with those present in the documentation.
I wanted to know whether to proceed with whatever I've found, or whether you could guide me to the correct documentation.

**Comment by Sakilmostak** [comment]
Hello @ashh1215 you can go through the invoice section of this [Bitpay's API](https://developer.bitpay.com/reference/concepts) reference doc to check how we are interacting with their API.

**Comment by VedantKhairnar** [comment]
Hey @ashh1215 ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by ashh1215** [comment]
Hey @VedantKhairnar 
Yeah, I'm working on it. I should be done soon.

**Comment by deepanshu-iiitu** [comment]
Hey @ashh1215  ,
Just checking in - are you working on it? Do you need help from our side?

**Comment by ashh1215** [comment]
Hey @deepanshu-iiitu 
I made a PR around a week ago which should close this issue. It hasn't been reviewed yet though.
