### ISSUE TITLE
[FEATURE]: [Coinbase] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2326]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Kota-Karthik** [comment]
@Sakilmostak @AkshayaFoiger 
I am interested in doing this issue 
so kindly assign me this 
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik, I see that you're already assigned to #2351. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2351 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by Ceres445** [comment]
I tried checking coinbase documentation and landed at [this](https://docs.cloud.coinbase.com/commerce/docs/webhooks-events) but it doesn't describe the data event properly or give any context as to what it uses as a reference id for the transaction. The [structure](https://github.com/juspay/hyperswitch/blob/89cb63be3328010d26b5f6322449fc50e80593e4/crates/router/src/connector/coinbase/transformers.rs#L325) also has different fields than the example provided in the documentation. Can anyone point me in the correct direction?

**Comment by AkshayaFoiger** [comment]
Hello @Ceres445,

I noticed you were referring to the webhook structure, and I recommend consulting [Coinbase's API documentation](https://docs.cloud.coinbase.com/commerce/reference/) for more detailed information. Additionally, while searching for the connector reference ID, please be aware that some connectors may not require a payment reference ID in their payment requests. However, it is expected that they will provide a payment-specific ID in their response, which should then be populated as the 'connector_reference_id,' as specified in the issue.

I trust that this information proves valuable. If you have any further inquiries, please feel free to reach out.

**Comment by Ceres445** [comment]
@AkshayaFoiger can you please assign me this issue

**Comment by AkshayaFoiger** [comment]
Hey @Ceres445, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Ceres445** [comment]
I'm having some issues running the test script `cargo test --package router --test connectors -- stripe:: --test-threads=1`. But I've read the [documentation](https://docs.cloud.coinbase.com/commerce/reference/getevents) mentioned above and made the changes.

**Comment by srujanchikke** [comment]
Hello @Ceres445 ,

No worries, Don't need to run the test script . Please raise a PR to main!
