### ISSUE TITLE
[FEATURE]: [Forte] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2330]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by AaronTJDev** [comment]
Hi @VedantKhairnar and @Sakilmostak ,

I'm new to this project and rust, but I'm interested in taking this on as a first issue. I'm curious where would be a good place to find connector docs to familiarize myself with this as instructed in the issue description? I've checked the crate docs, but not 100% sure, what I'm looking for. Any guidance would be appreciated, thanks!

> One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.

**Comment by AkshayaFoiger** [comment]
Hello @AaronTJDev ,

Thank you for getting in touch. Certainly, issue #2330 presents itself as an excellent opportunity for initiating open-source contributions. 
To gain a comprehensive understanding of this matter, I would like to elucidate how it has been resolved in the context of Adyen. On examining the [Adyen documentation regarding payment requests](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments), it is evident that they accept a field known as **reference** within their API requests for creating a transaction. This **reference** serves as a means to specifically identify and reference individual payments, and thus, it can been aptly designated as a **connector_response_reference_id**. We have accordingly made the necessary modifications to the connector/adyen/transformer.rs file, to include **reference** field in both payment requests and responses. I recommend reviewing the details of these changes in this associated [Pull Request](https://github.com/juspay/hyperswitch/pull/1735).

Note: Some connectors may not necessitate a `payment reference id` in their payment requests. However, it is anticipated that they will provide a `payment reference id` in their response, which should then be mapped to the 'connector_reference_id' as specified in the issue.

For specific guidance on the Forte connector, please refer to the [Forte API Docs](https://restdocs.forte.net/#cc0708ad-bd90-4821-a601-d31365f4a249).

I hope this information proves helpful. In case you have any further queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by AaronTJDev** [comment]
Thanks for the thorough feedback @AkshayaFoiger , I really appreciate it! Based on that, it looks like the correct key for this would be the `transaction_id`. I have the code worked out, but I'll have to spend some time this week to configure my local environment to test this before I open a PR.

**Comment by AkshayaFoiger** [comment]
> Thanks for the thorough feedback @AkshayaFoiger , I really appreciate it! Based on that, it looks like the correct key for this would be the `transaction_id`. I have the code worked out, but I'll have to spend some time this week to configure my local environment to test this before I open a PR.

Hey @AaronTJDev, that's a good news. Shall I assign you this issue ?

**Comment by AkshayaFoiger** [comment]
Hey @AaronTJDev, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @AaronTJDev  ,
Let us know if you face any issues. Happy to help! : )

**Comment by AaronTJDev** [comment]
I've created a PR for this. Thank you both for your kindness and your assistance @AkshayaFoiger and @VedantKhairnar .
