### ISSUE TITLE
[FEATURE]: [GlobalPayments] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2331]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Abhiramjampani** [comment]
@AkshayaFoiger
I would be delighted to work on this issue
so kindly assign me this
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Abhiramjampani , I see that you're already assigned to #2346. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2346 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by amitroy-thedev** [comment]
@AkshayaFoiger 
I want to give it a try can you assign this issue to me.
Thank you

**Comment by amitroy-thedev** [comment]
@AkshayaFoiger 
Hello there, I'm new to rust but want to give it a try on this issue can you assign this issue to me.
Thank you 😊

**Comment by SanchithHegde** [comment]
Sure @amitroy-thedev, I'll assign this to you. Let us know in case you have any questions, on this issue thread or on our Discord server.

**Comment by srujanchikke** [comment]
Hello @amitroy-thedev ,

This issue is already been solved , Can i assign you a similar issue #2292 ?

**Comment by amitroy-thedev** [comment]
@srujanchikke okay

**Comment by amitroy-thedev** [comment]
@srujanchikke 
Okay

**Comment by SanchithHegde** [comment]
@amitroy-thedev Please ensure you comment on the issue (either on #2292 or anything else that interests you) so that we can assign it to you.

**Comment by srujanchikke** [comment]
Closed as in https://github.com/juspay/hyperswitch/pull/2102
