### ISSUE TITLE
[FEATURE]: [Iatapay] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2333]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Kota-Karthik** [comment]
@AkshayaFoiger @Sakilmostak 
I would be delighted to work on this issue
so kindly assign me this issue
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik, I see that you're already assigned to https://github.com/juspay/hyperswitch/issues/2351. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on https://github.com/juspay/hyperswitch/issues/2351 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by ALLENGJOSE** [comment]
@AkshayaFoiger @Sakilmostak  Can I please work on this issue?

**Comment by SanchithHegde** [comment]
Sure @ALLENGJOSE, I'll assign this to you. Let us know in case you have any questions, on this issue thread or on our Discord server.

**Comment by ALLENGJOSE** [comment]
Thanks. Working on it.

**Comment by ALLENGJOSE** [comment]
@SanchithHegde I am blank on this. Can you please help me with this as to how to proceed?

**Comment by AkshayaFoiger** [comment]
Hello @ALLENGJOSE ,
Thank you for getting in touch. 

To give you a better idea about the issue, I would like to elucidate how it has been resolved in the context of Adyen. On examining the [Adyen documentation](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments) regarding payment requests, it is evident that they accept a field known as `reference` within their API requests for creating a transaction. This `reference` serves as a means to specifically identify and reference individual payments, and thus, it can been aptly designated as a `connector_response_reference_id`. We have accordingly made the necessary modifications to the `connector/adyen/transformer.rs` file, to include reference field in payment  responses. I recommend reviewing the details of these changes in this associated [Pull Request](https://github.com/juspay/hyperswitch/pull/1735).
We are hoping to do similar implementation for Iatapay.

I hope this information proves helpful. In case you have any further queries, you can ask them on this issue thread, or on our discord server, or on slack whichever you are comfortable with

**Comment by ALLENGJOSE** [comment]
I am sorry. I am not able to understand this . Therefore I am Unassigning myself.

**Comment by prasunna09** [comment]
> @SanchithHegde I am blank on this. Can you please help me with this as to how to proceed?

Hi @ALLENGJOSE, Can you please tell us what issue you are facing earlier? Is it with understanding the issue or how to do the local setup of hyperswitch?

**Comment by Nittzza** [comment]
@Sakilmostak Hi i would like to work on this issue. Can i please be assigned thanks.

**Comment by AkshayaFoiger** [comment]
Hey @Nittzza , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Nittzza** [comment]
Thanks, working on it.

**Comment by VedantKhairnar** [comment]
Hey @Nittzza ,
Let us know if you face any issues. Happy to help! : )

**Comment by Nittzza** [comment]
I have set up hyperswitch on my local system so far. I'll let you know about any issues i face thanks.

**Comment by swangi-kumari** [comment]
Hello @Nittzza ,
This issue is already resolved by @SoumyoPurkayastha in this pr [2524](https://github.com/juspay/hyperswitch/pull/2524).
If you are interested, we will assign you with other open issues.
