### ISSUE TITLE
[FEATURE]: [NMI] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2338]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue! Could you please assign it to me?"

**Comment by AkshayaFoiger** [comment]
Hey @TechWizard9999  , I see that you're already assigned to #2352. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2352 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by parasss19** [comment]
Hey @AkshayaFoiger I want to work on this issue could you please assign this issue

**Comment by AkshayaFoiger** [comment]
Hey @parasss19, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by parasss19** [comment]
Hey @AkshayaFoiger is there any docs for NMI?

**Comment by AkshayaFoiger** [comment]
Hello @parasss19 , I kindly suggest that you consult [NMI's API documentation](https://www.nmi.com/sdks-and-apis/) for reference and guidance.

In case you have any further queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @parasss19  ,
Let us know if you face any issues. Happy to help! : )

**Comment by parasss19** [comment]
> Hey @parasss19 , Let us know if you face any issues. Happy to help! : )

Yeah actually I am busy with some work I will send PR today

**Comment by VedantKhairnar** [comment]
Sure @parasss19 
Let us know if you face any issues.

**Comment by VedantKhairnar** [comment]
Hey @parasss19  ,
Please let me know if you are working on it.
Thanks.

**Comment by deepanshu-iiitu** [comment]
Hello @parasss19  , we didn't hear back from you, so we are unassigning you from this issue. If you are interested, we will assign you with other issues, if the current one is taken.

**Comment by Hangsaai** [comment]
Hey @deepanshu-iiitu , can you assign this to me

**Comment by TejasMate** [comment]
@AkshayaFoiger @deepanshu-iiitu @VedantKhairnar @Sakilmostak 
Could you please assign this issue to me? This will be my first contribution to this repo.

**Comment by deepanshu-iiitu** [comment]
Hey @TejasMate , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with
