### ISSUE TITLE
[FEATURE]: [PowerTranz] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2345]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Kota-Karthik** [comment]
@AkshayaFoiger
I would be delighted to work on this issue
so kindly assign me this
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik, I see that you're already assigned to https://github.com/juspay/hyperswitch/issues/2351. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on https://github.com/juspay/hyperswitch/issues/2351 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by manirht** [comment]
@AkshayaFoiger 
I'm interested in doing this issue so kindly assign me this
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @manirht, I see that you're already assigned to https://github.com/juspay/hyperswitch/issues/2248. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on https://github.com/juspay/hyperswitch/issues/2248 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by kritikash18** [comment]
Hi @AkshayaFoiger I would like to work on this issue if its still available

**Comment by AkshayaFoiger** [comment]
Hey @kritikash18, sure! I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by kritikash18** [comment]
Hi @AkshayaFoiger, I'm a little confused w.r.t the API contract.
I checked the API contract for PowerTranz to find an appropriate reference number and found that we are using the fields in a different format.
Example:
the field "TransactionIdentifier" in PowerTranz contract is being passed as "transaction_identifier" in our request. 

Am I missing something? Is there any contract I should be referring to?
the contract I looked up: [https://staging.ptranz.com/api/swagger/index.html](https://staging.ptranz.com/api/swagger/index.html)

**Comment by AkshayaFoiger** [comment]
Yes, @kritikash18 , you are indeed referring to the correct documentation.

The difference in field names is due to our practice of renaming all fields of struct PowertranzPaymentsRequest into PascalCase form. 

Using `#[serde(rename_all = "PascalCase")]`

Consequently, when a request is sent, `transaction_identifier` is automatically converted into `TransactionIdentifier`.
I trust this answers your query. 

Please feel free to reach out, if you have any further queries.
