### ISSUE TITLE
[FEATURE]: [Rapyd] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2346]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- Please refer to the Rapyd API documentation [here](https://docs.rapyd.net/en/create-payment.html). In the payment response, there is a field called `merchant_reference_id` (an optional field). This `merchant_reference_id` needs to be mapped to the `connector_response_reference_id`.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Abhiramjampani** [comment]
@AkshayaFoiger @VedantKhairnar @Sakilmostak I would be delighted to work on this issue
so kindly assign me this issue
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Abhiramjampani , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Abhiramjampani** [comment]
thankyou for assigning me this issue 
sure !! i will consult for any  queries.

**Comment by srujanchikke** [comment]
Hi @Abhiramjampani ,

Please raise a PR to main , I have updated the issue, that how `connector_resoponse_reference_id ` needs to mapped according to api docs of rapyd . Please re-read the issue .

**Comment by VedantKhairnar** [comment]
Hey @Abhiramjampani  ,
Let us know if you face any issues. Happy to help! : )

**Comment by VedantKhairnar** [comment]
Hey @Abhiramjampani ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by tejas-raskar** [comment]
Hey @VedantKhairnar @Sakilmostak 
I would like to work on this issue.

**Comment by VedantKhairnar** [comment]
Hey @tejas-raskar  , sure! I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with.

**Comment by tejas-raskar** [comment]
Hey @VedantKhairnar,
I have gone through the issue and the Rapyd docs. 

I have to map the `merchant_reference_id` to the `connector_response_reference_id`. 

This is how I am planning to do it:

```
connector_response_reference_id: Some(
    item.data.merchant_reference_id.unwrap_or(item.response.id)
)
``` 
According to the Rapyd docs, the `merchant_reference_id` is under `data` in the response. Is this approach correct?

**Comment by swangi-kumari** [comment]
Hey @tejas-raskar ,
Please raise a PR for whatever you did as per your understanding ASAP, It will be easy for us to review from there.

**Comment by tejas-raskar** [comment]
> Hey @tejas-raskar , Please raise a PR for whatever you did as per your understanding ASAP, It will be easy for us to review from there.

I have created a PR
Please review

**Comment by vinfinity7** [comment]
@swangi-kumari kindly look into PR https://github.com/juspay/hyperswitch/pull/2724

**Comment by vinfinity7** [comment]
@srujanchikke please assign me this

**Comment by swangi-kumari** [comment]
@vinfinity7 ,
sure! We've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by vinfinity7** [comment]
@swangi-kumari the pr has been updated , it needs review #2724 & #2722

**Comment by nabeel001** [comment]
@Sakilmostak @AkshayaFoiger 
I would like to work on this issue, kindly assign this to me.

**Comment by Sakilmostak** [comment]
Sure @nabeel001 , assigning this issue to you👍

**Comment by nabeel001** [comment]
@Sakilmostak @AkshayaFoiger
Kindly review my pull request

**Comment by gorakhnathy7** [comment]
Hey @nabeel001 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
