### ISSUE TITLE
[FEATURE]: [Shift4] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2347]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by Kota-Karthik** [comment]
@AkshayaFoiger
I would be delighted to work on this issue
so kindly assign me this issue
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik, I see that you're already assigned to #2351. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2351 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by Illuminati9** [comment]
Hey @AkshayaFoiger , I would like to work on this issue. Could you please assign to me??

**Comment by AkshayaFoiger** [comment]
Hey @Illuminati9, sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Illuminati9** [comment]
Hey @AkshayaFoiger , can you explain me this issue clearly??

**Comment by AkshayaFoiger** [comment]
Hello @Illuminati9 ,
Thank you for getting in touch. To gain a comprehensive understanding of this matter, I would like to elucidate how it has been resolved in the context of Adyen. 
On examining the [Adyen documentation regarding payment requests](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments), it is evident that they accept a field known as reference within their API requests for creating a transaction. This reference serves as a means to specifically identify and reference individual payments, and thus, it can been aptly designated as a connector_response_reference_id. We have accordingly made the necessary modifications to the connector/adyen/transformer.rs file, to include reference field in both payment requests and responses. I recommend reviewing the details of these changes in this associated [Pull Request.](https://github.com/juspay/hyperswitch/pull/1735)
Note: Some connectors may not necessitate a payment reference id in their payment requests. However, it is anticipated that they will provide a payment reference id in their response, which should then be mapped to the 'connector_reference_id' as specified in the issue.
For specific guidance on the Forte connector, please refer to the [Shift4 API Docs.](https://dev.shift4.com/docs/api)
I hope this information proves helpful. In case you have any further queries, you can ask them on this issue thread, or on our discord server, or on slack whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @Illuminati9  ,
Let us know if you face any issues. Happy to help! : )

**Comment by daniloff200** [comment]
it feels like I also gonna fix that in my MR for shift4
Can this one be assigned to me?

**Comment by SanchithHegde** [comment]
Sure @daniloff200.

**Comment by daniloff200** [comment]
looks like this can be closed.
or not?

**Comment by SanchithHegde** [comment]
Closing as completed in #2492.
