### ISSUE TITLE
[FEATURE]: [Tsys] Use `connector_response_reference_id` as reference to merchant

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2350]
### :memo: Feature Description

- Reference id are used to map transactions in the connector’s dashboard.
- Hyperswitch manages several reference ids, such as `payment_id`, `attempt_id`, and `connector_transaction_id` for a single transaction. 
- However, merchants may encounter uncertainty when determining which ID to utilize in the connector dashboard to identify the payment.

### :hammer: Possible Implementation

- When we receive a response from the connector for the payment, we deserialize it and populate the `response` field in RouterData. 
- For the `TransactionResponse` type, we must fill the `connector_response_reference_id` with a corresponding reference id for the merchant to identify the transaction. 
- One might need to have exposure to api docs of the connector for which it is being implemented to decide what to fill in connector_response_reference_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1735

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by harshalkh** [comment]
Can someone tell me where can i get api doc/contracts for this one.

**Comment by AkshayaFoiger** [comment]
Hello @harshalkh, I recommend referring to the [TSYS API documentation](https://developers.tsys.com/api/product?key=Payments) for further guidance.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by Kota-Karthik** [comment]
@AkshayaFoiger
I would be delighted to work on this issue
so kindly assign me this
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by AkshayaFoiger** [comment]
Hey @Kota-Karthik, I see that you're already assigned to #2351. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on #2351 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by manirht** [comment]
I'm interested in doing this issue so kindly assign me this
Thank You : )

**Comment by AkshayaFoiger** [comment]
Hey @manirht, I see that you're already assigned to https://github.com/juspay/hyperswitch/issues/2248. For now, we'll leave this issue open to any other interested contributors. You may pick this up once your work on https://github.com/juspay/hyperswitch/issues/2248 is completed, and if no other contributors have expressed interest on this. I hope that's fine by you

**Comment by charan-1303** [comment]
Hey @AkshayaFoiger , I would to like to work on this issue. Can you please assign it to me??

**Comment by AkshayaFoiger** [comment]
Hey @charan-1303, sure! I've assigned this to you.

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by VedantKhairnar** [comment]
Hey @charan-1303  ,
Let us know if you face any issues. Happy to help! : )

**Comment by VedantKhairnar** [comment]
Hey @charan-1303  ,
Just checking in - are you working on it?
Let us know if you need any help.

**Comment by Rutam21** [comment]
@VedantKhairnar I would love to take this up and raise a PR asap. Thanks.

**Comment by VedantKhairnar** [comment]
@charan-1303 
As we haven't heard back from you, we would be unassigning the issue. 
Whenever you get available to contribute, feel free to take any available issue. More than happy to help! 
Thanks for your time.

@Rutam21 
Sure, I have assigned this to you.
Let us know if you have any queries.
