### ISSUE TITLE
[Docs] : Some links not working

### ISSUE THREAD

**Issue by parasss19** [juspay/hyperswitch#2400]
## Some index links are not working
- Quick start guide
- Fast integration for stripe users
- Supported Features
- Faq

### Video
https://github.com/juspay/hyperswitch/assets/101205226/70f42b41-4c94-40fb-a538-85ef5ac4dd6c

**Comment by ATREAY** [comment]
Hey @parasss19, mind if I work on this issue?

**Comment by parasss19** [comment]
Hey @AkshayaFoiger I want to work on this issue please assign me this
