### ISSUE TITLE
[BUG] Horizontal Scrollbar 

### ISSUE THREAD

**Issue by itshypon** [juspay/hyperswitch#2430]
### Bug Description

Website have content overflowing which leads to appearance of horizontal scrollbar.
![image](https://github.com/juspay/hyperswitch/assets/30335924/abe10916-d290-4fef-b879-d421efdeba6a)

### Expected Behavior

Content should not overflow and no horizontal scrollbar should be present.

### Actual Behavior

Horizontal scrollbar is showing because of overflowing of some content.

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Go to hyperswitch
2. In laptop, use laptop to scroll horizontally and we will see white space on right side.

### Environment

Are you using hyperswitch hosted version? 
Yes

Operating System or Linux distribution: Arch Linux
Browser : Brave

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by agatekartik** [comment]
The "Sign Up" button on the homepage spills over too - even when window is maximised

Possibly related: the "Pricing" tab, when the window is not maximised, is cropped on the left too. Here's a screenshot:

<img width="983" alt="Screenshot 2023-10-05 at 1 54 37 PM" src="https://github.com/juspay/hyperswitch/assets/8896296/f0261218-1c9d-4ab7-a4e2-fc7391debe11">

**Comment by VedantKhairnar** [comment]
Hey @itshypon, @agatekartik 
Thanks for raising the issue and bringing it to our attention.
This forum is for the hyperswitch backend. We will look into these bugs.
Thanks.  : )
