### ISSUE TITLE
[FEATURE] Update twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [juspay/hyperswitch#2499]
### Feature Description

Update the logo from bird to X

### Possible Implementation

I can remove the old logo and write the code for new X logo.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by blindaks** [comment]
Please assign this issue to me

**Comment by SanchithHegde** [comment]
This repository does not contain the source code for the website, closing this as invalid.
