### ISSUE TITLE
[FEATURE] Reference IDs are used in the connector's dashboard to link transactions.

### ISSUE THREAD

**Issue by Shruti192903** [juspay/hyperswitch#2538]
### Feature Description

Feature Description

Reference IDs are used in the connector's dashboard to link transactions. Hyperswitch handles multiple reference IDs, including payment_id, attempt_id, and connector_transaction_id, for a single transaction. However, merchants might face confusion when deciding which ID to use on the connector dashboard to identify the payment.

### Possible Implementation

Upon receiving a response from the connector for the payment, we perform deserialization and populate the response field in RouterData. For the TransactionResponse type, it's crucial to populate the connector_response_reference_id with the appropriate reference ID, allowing the merchant to accurately identify the transaction. To determine what to fill in the connector_response_reference_id, familiarity with the connector's API documentation is essential. For more details, please refer to this PR.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by SanchithHegde** [comment]
Closing this as invalid, spam.
