### ISSUE TITLE
[FEATURE] Add support for tokenising bank details and fetching masked details while listing

### ISSUE THREAD

**Issue by Chethan-rao** [juspay/hyperswitch#2683]
### Feature Description

Add support for tokenising the fetched bank details during list_customer_payment_method and return masked bank details 

### Possible Implementation

For each bank account fetched from payment_methods_table, tokenize each account and store it in redis, so that it could be fetched during /confirm

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by shivam-jainn** [comment]
Is this an open issue or completed one ?

**Comment by Chethan-rao** [comment]
Hi @shivam-jainn,
This is a completed issue and pr also have been raised
