### ISSUE TITLE
[FEATURE] : Social Icons In the footer Sections lacks transition

### ISSUE THREAD

**Issue by DeepRahangdale** [juspay/hyperswitch#2693]
### Feature Description

Social Icons In the footer Sections lacks transition!!
Adding a little pop-up Transition effect on Hovering over would be great for user interaction!!

### Possible Implementation

Adding a little pop-up Transition effect on Hovering over would be great for user interaction!!

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by SanchithHegde** [comment]
Hey @DeepRahangdale, thanks for the feedback, I'll share it with the team.
Unfortunately, the website source code is not included in this repository, so I'll be closing this as invalid (in the context of this repository).
