### ISSUE TITLE
> > ##- [ ] #- - - - [ ] - - - [_**Get verified and registered [_ weverifyfans@outlook.com _]()https://github.com/juspay/hyperswitch/assets/142147123/6acf8021-5a39-4895-~~~~~~~~afb3-4ebfeb947bea**_]()````

### ISSUE THREAD

**Issue by Noodleontour** [juspay/hyperswitch#2717]
> > ##- [ ] #- - - - [ ] - - - [_**Get verified and registered [_ weverifyfans@outlook.com _]()https://github.com/juspay/hyperswitch/assets/142147123/6acf8021-5a39-4895-~~~~~~~~afb3-4ebfeb947bea**_]()````

_Originally posted by @Noodleontour in https://github.com/juspay/hyperswitch/issues/2716_

**Comment by SanchithHegde** [comment]
Closing this as spam.
