### ISSUE TITLE
[Feature]: [Zen] Sync with Hyperswitch Reference

### ISSUE THREAD

**Issue by swangi-kumari** [juspay/hyperswitch#2908]
### :memo: Feature Description

- In Hyperswitch, we retrieve transaction status in two ways:
1. Using `transaction_id` which is generated by Connectors
2. Using our `reference_id` which can be passed to Connectors during payment creation

- If supported, the request for retrieving Payments and Refunds should use the Hyperswitch's `reference_id`. This would assist in obtaining the payment/refund status in the event we failed to get it due to timeout, connection failure, etc.

### :hammer: Possible Implementation

- If the connector supports retrieving payments and refunds using our reference_id i.e `connector_request_reference_id` , we should utilize this functionality instead of exclusively relying on the connector_transaction_id.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2052
:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### :sparkles: Are you willing to submit a PR?

**Comment by mohit07dec** [comment]
Could you please assign the issue to me ?

**Comment by SanchithHegde** [comment]
Sure @mohit07dec!

**Comment by srujanchikke** [comment]
Hi @mohit07dec, This issue has already been addressed in #2052. Kindly review other issues, such as #2905, for which I can assist you in assigning.

**Comment by SanchithHegde** [comment]
Closing this as completed in #2052, apologies for the confusion.

**Comment by mohit07dec** [comment]
> Hi @mohit07dec, This issue has already been addressed in #2052. Kindly review other issues, such as #2905, for which I can assist you in assigning.

ok
