### ISSUE TITLE
[REFACTOR]: [Zen] MCA metadata validation

### ISSUE THREAD

**Issue by swangi-kumari** [juspay/hyperswitch#2913]
### :memo: Feature Description

- We don't have validation for MCA metadata, So while creating MCA we are allowing any json value. Because of which RequestEncodingFailure happening during payments for the MCA which doesn't have the expected fields

### :hammer: Possible Implementation

- While adding Merchant Connector Account we want that metadata field should be validated. 
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/2746
:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/zen` and `crates/router/src/core/admin.rs`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### :sparkles: Are you willing to submit a PR?

**Comment by alpha951** [comment]
Hi, I would like to work on this issue.

**Comment by SanchithHegde** [comment]
Sure @alpha951. In case of queries, feel free to reach out on this issue thread or on our Discord server.

**Comment by alpha951** [comment]
@swangi-kumari What is expected metadata format for MCA creation. According to postman collection it's : 
```json
  "metadata": {
    "city": "NY",
    "unit": "245"
  }
 ```
 Also I believe I need to validate the metadata at this [line](https://github.com/juspay/hyperswitch/blob/734327a957c216511b182151a2f0b27819e7e3bb/crates/router/src/core/admin.rs#L136)
 
PS: I'm coming Java and JS, totally new to Rust so expect some silly questions coming.

**Comment by AkshayaFoiger** [comment]
Resolved
