### ISSUE TITLE
[FEATURE] Implement `AuthorizationInterface` for `MockDb`

### ISSUE THREAD

**Issue by sai-harsha-vardhan** [juspay/hyperswitch#3044]
Spin off from https://github.com/juspay/hyperswitch/issues/172. Refer to the parent issue for more information

**Comment by kashifsoofi** [comment]
I would like to work on this.

**Comment by SanchithHegde** [comment]
Sure @kashifsoofi, I'll assign this to you. 

In case you have any queries, you can ask them here or on our Discord server.
