### ISSUE TITLE
[BUG] ARM64 images are not available on Docker Hub

### ISSUE THREAD

**Issue by alshaikh1** [juspay/hyperswitch#3195]
### Bug Description

I couldn't start all docker containers 
formbricks/formbricks:latest, it keeps Restarting

after investigation: I got the following message:

>  ! hyperswitch-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s 

Machine: Linux Ubuntu Server 22.04 running on ARM64

### Expected Behavior

All containers should be up and running

### Actual Behavior

 formbricks/formbricks:latest   "docker-entrypoint.s…"   2 months ago    Restarting (1) 2 seconds ago

### Steps To Reproduce

docker compose up -d

### Environment

Linux Ubuntu Server 22.04 running on ARM64

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by SanchithHegde** [comment]
Hey @alshaikh1, we are aware that we don't have arm64 Docker images (yet), but we do want to build and publish arm64 images. That said, for setting up Hyperswitch locally, you should still be able to run the amd64 images on an arm64 machine, it should work.

---

> formbricks/formbricks:latest, it keeps Restarting

> formbricks/formbricks:latest "docker-entrypoint.s…" 2 months ago Restarting (1) 2 seconds ago

I don't recognize the `formbricks/formbricks:latest` image however, it's not something we use in our Docker setup guide(s).

**Comment by alshaikh1** [comment]
Hello, The below image shows the issue regarding the AMD/ARM I'm facing:

<img width="913" alt="image" src="https://github.com/juspay/hyperswitch/assets/8459043/fbaf6fc0-ceca-4a9e-9567-d4815b792cbc">

**Comment by SanchithHegde** [comment]
@alshaikh1 Could you try adding `platform: linux/amd64` after this line in the `docker-compose.yml` file and let me know if it works?
https://github.com/juspay/hyperswitch/blob/61cd8d50a863308b03b3c158bd493b4408c03627/docker-compose.yml#L49

The resultant diff should look like so:

```diff
 services:
   ### Application services
   hyperswitch-server:
     image: juspaydotin/hyperswitch-router:standalone
+    platform: linux/amd64
     command: /local/bin/router -f /local/config/docker_compose.toml
     ports:
       - "8080:8080"
```

**Comment by alshaikh1** [comment]
I added it to the `platform: linux/amd64` to the `docker-compose.yml` in the place you mentioned. 
hyperswitch image didn't work. as you see from running `docker ps` command:

<img width="1187" alt="image" src="https://github.com/juspay/hyperswitch/assets/8459043/16702d64-1ebe-47dc-ad11-b481c343d5ec">

**Comment by SanchithHegde** [comment]
@alshaikh1 Could you please run the `docker ps -a` command to also include exited containers?

I see that all containers were started successfully, so it could have exited due to some other reason. If it has indeed exited, could you check logs using `docker logs hyperswitch-hyperswitch-server-1` and share it?

**Comment by alshaikh1** [comment]
Here you go

`crocodile@crocs:~/hyperswitch$ docker ps -a
CONTAINER ID   IMAGE                                       COMMAND                  CREATED      STATUS                     PORTS                                         NAMES
13e41126e9e2   postgres:latest                             "docker-entrypoint.s…"   2 days ago   Up 3 minutes               0.0.0.0:5432->5432/tcp, :::5432->5432/tcp     hyperswitch-pg-1
accc262f1a39   juspaydotin/hyperswitch-router:standalone   "/local/bin/router -…"   2 days ago   Exited (1) 3 minutes ago                                                 hyperswitch-hyperswitch-server-1
1ce6fb8bf6be   redis:7                                     "docker-entrypoint.s…"   2 days ago   Up 3 minutes               0.0.0.0:32768->6379/tcp, :::32768->6379/tcp   hyperswitch-redis-standalone-1
01a2c1b86616   rust:latest                                 "bash -c 'cargo inst…"   2 days ago   Exited (0) 3 minutes ago                                                 hyperswitch-migration_runner-1
crocodile@crocs:~/hyperswitch$ docker logs hyperswitch-hyperswitch-server-1 
exec /local/bin/router: exec format error
exec /local/bin/router: exec format error
crocodile@crocs:~/hyperswitch$ 
`

**Comment by SanchithHegde** [comment]
Hey @alshaikh1, the container indeed exited due to the differences in architecture. As of now, we don't have arm64 images available on Docker Hub, so if you'd like to try hyperswitch out locally, you can use the `docker-compose-development.yml` file to build it. You can refer to this section of the local setup guide:

https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#set-up-a-development-environment-using-docker-compose

**Comment by alshaikh1** [comment]
Unfortunately, compiling didn't work !
Will wait for the ARM image.

**Comment by SanchithHegde** [comment]
Hey @alshaikh1, the multi-architecture images for all app server components (router, consumer, producer, drainer) are now available for the latest stable release ([`v1.108.0`](https://github.com/juspay/hyperswitch/releases/tag/v1.108.0)). 

Closing this issue as completed.

**Comment by alshaikh1** [comment]
Hi @SanchithHegde 
Any idea how to install on ARM64 using this docker image?

**Comment by SanchithHegde** [comment]
@alshaikh1 You can run the Docker Compose setup and it should automatically pull images for your machine's architecture, you need not make any changes to the Docker Compose file to pull the arm64 images. You can find the docs for setting up Hyperswitch locally using Docker Compose either on [our docs site](https://docs.hyperswitch.io/hyperswitch-open-source/local-setup-guide/unified-local-setup-using-docker) or on [our GitHub repository](https://github.com/juspay/hyperswitch/blob/v1.110.0/docs/try_local_system.md#run-hyperswitch-using-docker-compose).

**Comment by alshaikh1** [comment]
@SanchithHegde 
I'm afraid I'm getting the same error above.

**Comment by SanchithHegde** [comment]
@alshaikh1 Could you please try the same with a fresh clone of the hyperswitch repository?

**Comment by alshaikh1** [comment]
Yes I did that. 

1. I deleted all existing docker containers and images
2. Cloned a fresh copy of the repositoy
Didin't work.

I tried to clone using `git clone --depth 1 --branch v1.110.0 https://github.com/juspay/hyperswitch.git` for the specific branch but also didn't work.

**Comment by SanchithHegde** [comment]
@alshaikh1 Could you please share a screenshot of these command outputs:

- `docker compose ps -a`
- `docker compose logs hyperswitch-server`

**Comment by alshaikh1** [comment]
@SanchithHegde 
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/b8a0d91b-ba05-4d0c-b148-bc23ba84a9d2">
and
<img width="747" alt="image" src="https://github.com/user-attachments/assets/4c518f9a-2b84-40cf-9cd9-d414f8c2df33">

**Comment by SanchithHegde** [comment]
@alshaikh1 Could you please update the value from `NOR` to `NOK` in `config/docker_compose.toml`, re-run `docker compose up -d`, and let us know if that fixes it? You'd have to update [this line](https://github.com/juspay/hyperswitch/blob/03f0ea1582c76f1ed9dc4ff2215e80d659e5591a/config/docker_compose.toml#L560C117-L560C120) in the file. Looks like it was a typo from our end.

**Comment by alshaikh1** [comment]
@SanchithHegde 
Worked like a charm on ARM64. Many thanks.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/1082725c-839a-4f3a-abb4-b929cc561ca3">
