### ISSUE TITLE
[BUG] Payment create: name field is ignored

### ISSUE THREAD

**Issue by whiteagle3k** [juspay/hyperswitch#3321]
### Bug Description

I create the payment with the name literally inserted:

`{
    "amount": 100,
    "currency": "USD",
    "profile_id": "pro_xxxxx",
    "description": "123",
    "name": "John Doe"
}`

the response is created payment with name:null

### Expected Behavior

payment object name should be the value I passed

### Actual Behavior

null

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
Create a payment with "name" value

### Environment

106

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by Narayanbhat166** [comment]
Hi @whiteagle3k, please pass the `customer_id` field as specified in the [api reference](https://api-reference.hyperswitch.io/api-reference/payments/payments--create) when passing customer details. Then the `name` field will be consumed. I hope that helps. Will close this issue for now, you can reopen this issue in case of any further queries.
