### ISSUE TITLE
[FEATURE] 3DS APIs design

### ISSUE THREAD

**Issue by akash-kamble-juspay** [juspay/hyperswitch#3411]
### Feature Description

Design APIs for HS 3DS Authentication Service.
Endpoints- 
/preAuth
/auth
/postAuth

### Possible Implementation

Implementation details to be added.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by sai-harsha-vardhan** [comment]
API Contract finalized with backend team, link here - https://docs.google.com/document/d/1SOG1KxUZjFYJ1zWUShD9wi1ZhiS_lZulh1dLHvCe1zg/edit?usp=sharing
