### ISSUE TITLE
[FEATURE] Create a delete endpoint for Config Table

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#3488]
### Feature Description

Add an API for deleting data from config table.

### Possible Implementation

Add the endpoint DELETE `config/{key}` for deleting the config key.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by opeolluwa** [comment]
Hello here. 
How may I get started with this

**Comment by dracarys18** [comment]
Hi @opeolluwa thank you for your interest,

DB function for deleting config data by key already exist [here](https://github.com/juspay/hyperswitch/blob/892b04f805c219e2cf7cbe5736aef19909e986f7/crates/router/src/db/configs.rs#L157). You need to create a route [here](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/routes/configs.rs) and a function to call the DB function [here](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/core/configs.rs) .

**Comment by dracarys18** [comment]
Hey @tanbirali. Can you co-ordinate with @opeolluwa with this issue since @opeolluwa asked for it first.

**Comment by opeolluwa** [comment]
@dracarys18 let's have @tanbirali work it out. I'll try familiarize myself with the codebase

**Comment by dracarys18** [comment]
Sure Okay assigning to @tanbirali

**Comment by tanbirali** [comment]
Okay, thank you @opeolluwa for letting me take this issue, I will help you find issue in future.
