### ISSUE TITLE
[FIX] add a configuration validation for workers

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#3510]
We don't have a validation check 
[number of workers in our config](https://github.com/juspay/hyperswitch/blob/94cd7b689758a71e13a3eaa655335e658d13afc8/crates/router/src/configs/settings.rs#L422) . But if the number of workers is zero actix straight out panics. Ref: https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.workers

**Comment by ravikiran232** [comment]
Hi, I would like to work on this issue.

**Comment by dracarys18** [comment]
Hi @ravikiran232 assigning the issue to you
