### ISSUE TITLE
[BUG] Nuvei Payment request validation issues

### ISSUE THREAD

**Issue by cb-alfredjoseph** [juspay/hyperswitch#3511]
### Bug Description

nuvei payments

-  browser_info is validated for both non-3ds and 3ds flows, as per nuvei docs browser_info is mandatory only for 3ds flows. The validation should be thrown by gateway instead 
-  IP address and billing address not sent to Nuvei, which is mandatory by default, hyperswitch is currently not passing these fields. we were not able to use any other nuvei account due to this, These fields can be controlled at nuvei gateway account level, but by default they are mandatory and nuvei recommends these info to be sent.

### Expected Behavior

- browser_info :  Gateway should validate if browser info is not provided, payment request should go through even without browser_info for non-3ds
- IP address and billing address should forward  these details to nuvei

### Actual Behavior

- browser_info is validated by hyperswitch when not provided, even in cases where its not mandatory 
- IP address and billing address is not sent from hyperswitch to nuvei

### Steps To Reproduce

Payment request to reproduce the issue : 

```

`curl --location 'http://localhost:8090/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_GHrXsmnL5N4eGiw363ZF6qfzWxjk2UqwQHlkvaE4B03lGV9Vb4ESpCK6aKjYdN9V' \
--data-raw '{
    "amount": 1000,
    "currency": "USD",
    "confirm": true,
    "capture_method": "automatic",
    
    
    
    "customer_id": "futurebilling",
    "email": "guest@example.com",
    "name": "John Doe",
    "phone": "999999999",
    "phone_country_code": "+65",
    "description": "testing",
    "authentication_type": "three_ds",
    "return_url": "https://google.com",
    "payment_method": "card",
    "payment_method_type": "credit",
    
    "setup_future_usage": "off_session",
    
    "payment_method_data": {
        "card": {
            "card_number": "4000027891380961", 
            "card_exp_month": "12",
            "card_exp_year": "2030",
            "card_holder_name": "joseph Doe",
            "card_cvc": "123"
        }
    },
    "mandate_data": {
        "customer_acceptance": {
            "acceptance_type": "offline",
            "accepted_at": "1963-05-03T04:07:52.723Z",
            "online": {
                "ip_address": "127.0.0.1",
                "user_agent": "amet irure esse"
            }
        },
        "mandate_type": {
            "multi_use": {
                "amount": 7000,
                "currency": "USD",
                "metadata": {
                    "frequency": "1"
                },
                "end_date": "2025-05-03T04:07:52.723Z"
            }
        }
    },
    "billing": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "state": "California",
            "zip": "94122",
            "country": "BR",
            "first_name": "joseph",
            "last_name": "Doe"
        }
        
    },
    "shipping": {
        "address": {
            "line1": "1467",
            "line2": "Harrison Street",
            "line3": "Harrison Street",
            "city": "San Fransico",
            "zip": "94122",
            "country": "BR",
            "first_name": "joseph",
            "last_name": "Doe"
        },
        "phone": {
            "number": "8056594427",
            "country_code": "+91"
        }
    },
    "statement_descriptor_name": "joseph",
    
    "metadata": {
        "udf1": "value1",
        "new_customer": "true",
        "login_date": "2019-09-10T10:11:12Z"
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}'`

```

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.
x-request-id : 018d6035-8137-75c6-8088-4754d80e0701

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by ArjunKarthik** [comment]
Hi @cb-alfredjoseph  , Thank you for bringing this issue to our attention. After reviewing the Nuvei documentation, it appears that the browser_info field is mandatory only for 3DS transactions. For all other cases, ip_address and billing details (country, email, firstName, lastName, phone) are required.

If you're interested in contributing to the resolution of this issue, I can assign it to you. Let me know if you'd like to take on this task.

**Comment by cb-alfredjoseph** [comment]
@ArjunKarthik 
Kindly check this [PR](https://github.com/juspay/hyperswitch/pull/3602) for Nuvei mandatory fields fix and Recurring mandate payments

**Comment by cb-alfredjoseph** [comment]
@ArjunKarthik PR convention check is failing due to this, are we missing something here, I think we dont have permission to link issue to PR.

<img width="772" alt="image" src="https://github.com/juspay/hyperswitch/assets/97145230/bf5db924-6047-41f8-80a9-f33c9bf8979a">
