### ISSUE TITLE
[BUG] Nuvei recurring MIT payment is not handled in Authorize flow

### ISSUE THREAD

**Issue by ArjunKarthik** [juspay/hyperswitch#3537]
### Bug Description

In the Nuvei Authorize flow implementation, the `get_request_body` method currently utilizes `TryFrom` to construct a `NuveiPaymentsRequest` using `RouterData`. To accommodate `NuveiPaymentsRequest` for each payment method, we have a match statement where `payments::PaymentMethodData::MandatePayment` needs to implement `TryFrom` for building `NuveiPaymentsRequest` specifically for recurring mandates. The logic already present in the `get_card_info` method should be relocated inside the new `TryFrom` implementation for `payments::PaymentMethodData::MandatePayment`

### Expected Behavior

Recurring MIT payments should work with connector_mandate_id for Nuvei connector.

### Actual Behavior

Recurring MIT payment with mandate id through Nuvei is failing saying "Selected payment method through nuvei is not implemented". 

### Steps To Reproduce

1. Create CIT payment with nuvei connector.
2. Use mandate_id from the previous CIT payment and create MIT payment
3. Hyperswitch throws 501 http status code in the response

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by cb-alfredjoseph** [comment]
To initiate recurring payments with nuvei, we need user_id as well as token_id which we are not storing in hyperswitch db.


{"payment_method_id": null, "connector_mandate_id": "88514158"}

**Comment by cb-alfredjoseph** [comment]
@ArjunKarthik I belive connector_mandate_id is enough for recurring payment, ignore the previous comment

**Comment by cb-alfredjoseph** [comment]
@ArjunKarthik 
Have raised this [PR](https://github.com/juspay/hyperswitch/pull/3602) for Nuvei recurring MIT payment
