### ISSUE TITLE
[Logging Framework] - eliminate flow = UNKNOWN log lines

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#3670]
Currently there seems to be a lot of consolidated logs generated with `flow=UNKNOWN` parameter,
while a lot of them are unavailable endpoints a lot of successful api requests are being tagged as `UNKNOWN` as well.
Need to reduce such logs by identifying all the cases where an incorrect flow is logged...

## Triaged Issues
- [x] Add flow for `/health` API calls
- [x] #3683
- [x] #4003

**Comment by ShivanshMathurJuspay** [comment]
Failing for no_thress_ds payments too

Request ID -018dadac-79ac-72f9-82d1-9f5c1ddba869
Loki -> https://grafana.staging.eu.juspay.net/explore?orgId=1&left=%7B%22datasource%22:%22x5WTfCG4k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22bach%5C%22,%20service%3D%5C%22router%5C%22%7D%20%7C%3D%20%60018dadac-79ac-72f9-82d1-9f5c1ddba869%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22x5WTfCG4k%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708007400000%22,%22to%22:%221708021799000%22%7D%7D

Kibana -> https://kibana.staging.eu.juspay.net/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-15T16:36:47.187Z',to:'2024-02-15T17:01:30.862Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'39f5dc40-a03c-11ee-8413-95b9b1b2162b',key:flow,negate:!f,params:(query:PaymentsConfirm),type:phrase),query:(match_phrase:(flow:PaymentsConfirm))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'39f5dc40-a03c-11ee-8413-95b9b1b2162b',key:request_id,negate:!f,params:(query:'018dadac-79ac-72f9-82d1-9f5c1ddba869'),type:phrase),query:(match_phrase:(request_id:'018dadac-79ac-72f9-82d1-9f5c1ddba869')))),index:'39f5dc40-a03c-11ee-8413-95b9b1b2162b',interval:auto,query:(language:kuery,query:''),sort:!())
