### ISSUE TITLE
[FEATURE]: add `offset` field to mandates list

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#3748]
### Feature Description

The [mandates list](https://github.com/juspay/hyperswitch/blob/54c0b218d9f20c6388dde0f30ea525011cdad573/crates/router/src/routes/mandates.rs#L114) endpoint currently has no field to specify `offset`, which would skip certain number of entries from the start. This is necessary in order to provide pagination support.

### Possible Implementation

accept a field called `offset` which specifies the number of items to skip from the start.

This would be similar to the `payments_list` pagination. Refer [here](https://github.com/juspay/hyperswitch/blob/54c0b218d9f20c6388dde0f30ea525011cdad573/crates/router/src/routes/payments.rs#L868)

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by neithanmo** [comment]
@Narayanbhat166 you described a possible implementation that consists of adding an offset field to that endpoint method, but after looking at it I noticed that it also takes a payload argument of type: **MandateListConstrains**. 
This led me to ask myself why not make this offset part of the constraints? doing so would allow us to keep the endpoint signature as it is. 

can you provide feedback about this option? 
I guess an offset is completely unrelated to what a constraint is regarding MandateList and the way the user is querying it.

**Comment by PanGan21** [comment]
Hi @Narayanbhat166  since this issue was not assigned to someone I did some work on #3923 
Please let me know if something could be improved :)

**Comment by Narayanbhat166** [comment]
>This led me to ask myself why not make this offset part of the constraints

Hey @neithanmo, yes you can add it to the constraints.
