### ISSUE TITLE
[FEATURE] Determine card brand from card BIN number

### ISSUE THREAD

**Issue by ArjunKarthik** [juspay/hyperswitch#379]
### Feature Description

Some connectors like Worldline require a card brand name to be provided when providing payment method details. As of now, we have a limited set of regular expressions to identify card brands from card BIN number:

https://github.com/juspay/hyperswitch/blob/d107b44fd356f172ef7c9535567d266a6301e43d/crates/router/src/connector/worldline/transformers.rs#L20-L32

We'd need a more comprehensive way of identifying card brands. It would be great if the card identification logic is included in a new crate called `cards` which would contain this card brand identification logic and validation of card numbers (taken up on #606). It would also be great if the implementation minimizes CPU usage, so please include benchmarking code and times observed on your machine. Please also include unit tests in your PR.

_For external contributors, clarify any questions you may have, and let us know that you're interested in picking this up. We'll assign this issue to you to reduce duplication of effort on the same task._

### Possible Implementation

There are 2 ways to handle this: either using regular expressions, or maintaining a mapping of card BINs to brand names. You can decide to go with either of them, keeping the requirements in mind.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/contrib/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by jeevaprakashdr** [comment]
@SanchithHegde is this feature needs to be added as part of  `cards info api` or it is part of new crate `cards` from #607 ?

**Comment by SanchithHegde** [comment]
Closing as completed in #749.
