### ISSUE TITLE
[BUG]Remove braintree rest api transformers 

### ISSUE THREAD

**Issue by srujanchikke** [juspay/hyperswitch#3798]
I've found this bug while creating payment connector account for braintree. Validation for metadata is added for braintree graphql metadata but not for braintree REST api. Anyway's as braintree REST api is getting deprecated so need to remove code from codebase .

**Comment by AkshayaFoiger** [comment]
Yes as stated, the metadata validation is not implemented for Braintree Rest API. But we depreciate Braintree Rest API.  Therefore we are not expecting to add the required validation. However in the current system, metadata needed for both braintree transformers are same, Braintree REST API requests are validated by a common validation check present in Braintree graphql transformer.
