### ISSUE TITLE
[REFACTOR] provide an identifier for the api key in the expiry reminder email

### ISSUE THREAD

**Issue by Chethan-rao** [juspay/hyperswitch#3801]
### Issue Description:

Currently, our system sends out reminder emails to merchants when their API key is about to expire. However, since merchants can create multiple API keys, the email lacks clarity on which specific API key is expiring.

### Proposed Solution:

Refactor the api key expiry reminder workflow to include the name and prefix of the expiring API key in email. This will help merchants easily identify which API key requires attention without confusion.

### Details:

Update the email template to include the following information:
API Key Name along with Prefix in below format -
`API_KEY_NAME [PREFIX]`

### Reference:
Check `ApiKeyExpiryTrackingData` type in https://github.com/juspay/hyperswitch/blob/2c95dcd19778726f476b219271dc42da182088af/crates/diesel_models/src/api_keys.rs

**Comment by ravikiran232** [comment]
Hi, I would like to work on this issue.

**Comment by Chethan-rao** [comment]
Hi @ravikiran232,

Sure, I'm assigning the issue to you. Let us know if you need any help.
