### ISSUE TITLE
Allow off-session payments using Payment Method ID (only with API Key auth)

### ISSUE THREAD

**Issue by tinu-hareesswar** [juspay/hyperswitch#3814]
When a mandate is created on connector's end, we store the connector mandate details in our payment methods table. Now in order to make recurring payment with this, we basically have to do a token based payment where set the `setup_future_usage = off_session` and we list the payment methods of a customer and make a payment with payment token. But we should also allow off-session payments using payment method id without having to list customer payment methods. For this, we accept `off_session = true` and payment method id in the request and make a recurring mandate payment.

**Comment by jagan-jaya** [comment]
Need a Client token implementation for the SDK to make recurring payments
