### ISSUE TITLE
Create a merchant config for enable `pg_agnostic_mit`

### ISSUE THREAD

**Issue by ShankarSinghC** [juspay/hyperswitch#3992]
Create a merchant config (`pg_agnostic_mit`) to enable usage of Network Transaction/Reference ID in recurring mandate payments. This will be a `business profile` level config that a merchant specifies.

**API Spec:-**
```
POST /business_profile/{bp_id}/configs/pg_agnostic_mit
{
    “enabled”: true,
}
```

**Comment by tinu-hareesswar** [comment]
Can we not store this under mandate? and the endpoint also lets make it something like pg_agnostic_recurring?
