### ISSUE TITLE
Use NRID in recurring payments if the merchant config is enabled

### ISSUE THREAD

**Issue by ShankarSinghC** [juspay/hyperswitch#3994]
During the MIT process, there needs to be validation to check the off_session field. If set to true, then check if the `pg_agnostic_mit` config is enabled. If it is, perform a lookup in the payment methods table with the `payment_method_id` in the MIT payment request for the NRID. Retrieve the card details from the locker for the specific `payment_method_id`. Make the confirm call to the connector decided by routing.

If the confirm call fails, retry across the retry-able connectors specified in the pg_agnostic_mit configuration.

If the NRID is not present for that particular `payment_method_id`, or if the `pg_agnostic_mit` flag is not enabled, call the initial connector with which the CIT was performed.

**Comment by manojradhakrishnan** [comment]
@ShankarSinghC Looks like you linked an alternate PR to close this issue. Shall we manually mark this issue as closed?

**Comment by ShankarSinghC** [comment]
@manojradhakrishnan The issues addressed in both https://github.com/juspay/hyperswitch/issues/3993 and https://github.com/juspay/hyperswitch/issues/3994 have been resolved in a single pull request: https://github.com/juspay/hyperswitch/pull/4113. That's why these issues are linked to the same pull request.
