### ISSUE TITLE
Fails to build with rust 1.77.0

### ISSUE THREAD

**Issue by MikaelUrankar** [juspay/hyperswitch#4137]
### Bug Description

I have the following error with rust 1.77.0:
```
  --- stderr                                                                                  
  thread 'main' panicked at crates/router_env/src/cargo_workspace.rs:57:5:
  Unknown workspace members package ID format. Please run `cargo metadata --format-version=1 | jq '.workspace_members'` and update this build script to match the updated package ID format.
```

The format of ids in 'cargo metadata' has changed with cargo 1.77, it's documented here: https://github.com/rust-lang/cargo/issues/13528

### Expected Behavior

It should build.

### Actual Behavior

It fails to build.

### Steps To Reproduce

exec `cargo build` with rust 1.77.0

### Context For The Bug

```
  --- stderr                                                                                  
  thread 'main' panicked at crates/router_env/src/cargo_workspace.rs:57:5:
  Unknown workspace members package ID format. Please run `cargo metadata --format-version=1 | jq '.workspace_members'` and update this build script to match the updated package ID format.
```

### Environment

If not (or if building/running locally), please provide the following details:
1. Operating System: FreeBSD
2. Rust version (output of `rustc --version`): ```rustc 1.77.0 (aedd173a2 2024-03-17) (built from a source tarball)
binary: rustc
commit-hash: aedd173a2c086e558c2b66d3743b344f977621a7
commit-date: 2024-03-17
host: x86_64-unknown-freebsd
release: 1.77.0
LLVM version: 17.0.6```
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by MikaelUrankar** [comment]
hyperswitch builds fine with rust 1.76.0. I am preparing the update to rust 1.77.0 (I am the FreeBSD rust maintainer) and encounter this error.
Thanks.

**Comment by SanchithHegde** [comment]
Thanks again for reporting, I've opened #4139 to address this.
