### ISSUE TITLE
Implementation of Minio for storage of Loki logs

### ISSUE THREAD

**Issue by godwinpinto** [juspay/hyperswitch#4204]
### Feature Description

While Loki may be configured for log collection and storage on regular storage. It would be great to persist the logs on a dependable storage engine.

### Possible Implementation

[Minio](https://min.io/) is an object storage database that will help store logs on dependable clustered setup. Moreover, loki can be easily configured for storing logs on Minio. In Addition, Minio is AWS S3 compatible. This will help people looking forward for possible best practices in choosing cloud services.

However, the second question that comes to my mind is that configuring minio for loki might also be out of scope for the purpose of this project.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by lsampras** [comment]
@godwinpinto 
Can u describe the problem a bit more and how you intend to solve it?

> It would be great to persist the logs on a dependable storage engine.

Do you mean in terms of cloud deployment or local environment?

For local environment we aim for quick & easy setup (which we target via our docker compose files).

We don't seem to provide any help/guidance on production/cloud setup of loki yet.
Were you suggesting that we add those instead?

**Comment by godwinpinto** [comment]
Considering, Loki only for local environment for quick setup, we can ignore minio. Closing this issue.
