### ISSUE TITLE
[REFACTOR]: add `updated` field to payments response

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#4283]
Add a field called `updated` to the payments response. This field will have the ISO timestamp at which the payment was updated. 

This field should have the value from `modified_at` column from the `payment_intent` table.

The struct that is being used for the response is 
https://github.com/juspay/hyperswitch/blob/97fbc899c12a0c66ac89a7feaa6d45d39239a746/crates/api_models/src/payments.rs#L2910

In order to populate the field, use the builder method `.set_updated` when the response is generated
https://github.com/juspay/hyperswitch/blob/97fbc899c12a0c66ac89a7feaa6d45d39239a746/crates/router/src/core/payments/transformers.rs#L792

**Comment by soumilbaldota** [comment]
https://github.com/juspay/hyperswitch/pull/42920

@Narayanbhat166 Sent a PR.

**Comment by SanchithHegde** [comment]
@soumilbaldota Thanks, I'll be assigning this issue to you.

**Comment by abhishektanwar2309** [comment]
Is it closed ?. If not can I work on it ?.
