### ISSUE TITLE
[FEATURE] Add support for sending additional metadata in the `MessagingInterface`

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4472]
### Feature Description

In the current implementation of message interface I can only send a Message & a timestamp associated with the message,
There is no accomodation to send additional metadata about the message which isn't part of the data but could be propogated to the downstream implementations,

These could be used downstream as kafka headers or redis hashes or partition keys.

### Possible Implementation

metadata can be a simplistic `HashMap<String, String>` and can be either accomodated as a new param in the [`MessagingInterface`](https://github.com/juspay/hyperswitch/blob/cc1051da99c1b4e007d7f730e2fe3cb08b078d80/crates/events/src/lib.rs#L239) or a new method on the [`Message`](https://github.com/juspay/hyperswitch/blob/cc1051da99c1b4e007d7f730e2fe3cb08b078d80/crates/events/src/lib.rs#L239) Interface.

The implementers of MessageInterface can handle it as follows
1. Kafka
Send the metadata as headers
2. EventLogger
Log the metadata as a separate key along with the raw data

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by tanbirali** [comment]
I am interested in this

**Comment by lsampras** [comment]
Hey @tanbirali thanks for your interest.
I'll assign this issue, you can ask for clarifications here or reach out on our slack/discord.

**Comment by tanbirali** [comment]
whenever I am running the docker-compose up -d all the services are working but the hyperswitch-hyperswitch-server-1 is exiting everytime starting the container, how can I fix this

**Comment by lsampras** [comment]
Hey @tanbirali ,
Can you share the logs that are emitted on docker failure ?
you can get them via `docker compose logs hyperswitch-server`..

Also [these](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#set-up-a-development-environment-using-docker-compose) are the steps for running hyperswitch locally via docker compose you can walk through them again if anything is amiss...

There were some similar issues reported and solved in the [discord](https://discord.com/channels/1060451405535649813/1070640021968785408/threads/1234895411202887721) can check if your issue is present there

**Comment by lsampras** [comment]
Hey @tanbirali ,

Are you still interested/working on this,
Is there any clarification/help you need about this issue.

**Comment by tanbirali** [comment]
I am working on it, will try to create a PR soon

**Comment by tanbirali** [comment]
Sorry I am not able to run the project locally, I tried having a convo in the discord community, something or the other is not working for me, sorry for delaying it, I am trying in the mean time if anyone is willing to take this issue, please assign it to the individual

**Comment by lsampras** [comment]
Hey @tanbirali no worries, I'll keep the issue unassigned for now.
