### ISSUE TITLE
[Refactor] Convert KafkaStore to EventStore

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4494]
Currently we have hardcoded [`KafkaStore`](https://github.com/juspay/hyperswitch/blob/c20ecb855aa3c4b3ce1798dcc19910fb38345b46/crates/router/src/db/kafka_store.rs#L76-L79) as a composite of StorageInterface along with a kafka producer,
However we wanna make this more generic by substituting `KafkaProducer` with a generic [`MessageInterface`](https://github.com/juspay/hyperswitch/blob/c20ecb855aa3c4b3ce1798dcc19910fb38345b46/crates/events/src/lib.rs#L235-L242)

The final structure of `EventStore` would look like

```rust
#[derive(Clone)]
pub struct EventStore<T: StorageInterface, E: MessagingInterface> {
    event_producer: E,
    storage: T,
}
```

This refactor could be done in 2 parts as follows

1. Use `MessageInterface` as a generic trait instead of fixed `KafkaProducer`
2. Remove `KafkaMessage` trait implementations and use `MessageInterface` instead

**Comment by rishav-bose0** [comment]
Hey @lsampras! I would like to help with this issue. Can I work on this?

**Comment by lsampras** [comment]
Hi @rishav-bose0, since this change is slightly spread out throughout the code base, I'd prefer if we connect on either slack or discord to formulate & plan the approach to solve this...

**Comment by rishav-bose0** [comment]
sure, I too had some doubts on the generic replacements. Let's connect on discord.

**Comment by speedhs** [comment]
Hey! Is this still open?

**Comment by lsampras** [comment]
Hey @speedhs thanks for the interest,
unfortunately this issue is no longer relevant...
Feel free to take a look at some of our other open issues
