### ISSUE TITLE
[REFACTOR] Update KafkaStore to hold variables for tenant ID

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4496]
Update the [`KafkaStore`](https://github.com/juspay/hyperswitch/blob/c20ecb855aa3c4b3ce1798dcc19910fb38345b46/crates/router/src/db/kafka_store.rs#L75-L79) to hold a variable for tenant-ID.

This can be achieved by simply adding a new field in the `KafkaStore` struct.
Update the KafkaStore constructor method to accept a Tenant-ID.

Tenant-ID can be a new type field backed by a string;

```rust
pub struct TenantID(String);
```

For now the KafkaStore can be initialized with a fixed tenantID `"default"`

**Comment by subhajit20** [comment]
hey @lsampras can You review my pr once?

**Comment by lsampras** [comment]
@subhajit20 Thanks for the PR. I'll assign you this issue
