### ISSUE TITLE
 [REFACTOR] Update AnalyticsPool to hold variables for tenant ID

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4521]
Update the [AnalyticsProvider](https://github.com/juspay/hyperswitch/blob/be44447c09ea8814dc8b88aa971e08cc749db5f3/crates/analytics/src/lib.rs#L67-L72) (or [`AnalyticsConfig`](https://github.com/juspay/hyperswitch/blob/be44447c09ea8814dc8b88aa971e08cc749db5f3/crates/analytics/src/lib.rs#L593-L608)) to hold a variable for tenant-ID.

This can be achieved by simply adding a new field in the underlying structs for SqlxClient & ClickhouseClient.
Update the AnalyticsPool constructor method to accept a Tenant-ID.

Tenant-ID can be a new type field backed by a string;

pub struct TenantID(String);

For now the AnalyticsPool can be initialized with a fixed tenantID "default"

**Comment by Mohamed-Ayaan358** [comment]
@lsampras are all the analytic issues open for outside collaborators?

**Comment by lsampras** [comment]
All the issues are open for outside collaborators ideally (atleast for analytics),
We add `good-first-issue` for relatively simpler issues...

Once you ask to be assigned on an issue (could be a good-first-issue or not) the author can decide on it (there can be conditions)

@SanchithHegde correct me here in case we do have a specific label or convention...

**Comment by RaghavRox** [comment]
I would like to work on this.

**Comment by subhajit20** [comment]
hey @lsampras can I get assigned for this issue.

**Comment by lsampras** [comment]
I'll assign this issue to @RaghavRox if he is still interested since we try to follow `first come, first serve` when assigning issues.

Sry for the confusion @subhajit20 you can pick this up if @RaghavRox is no longer interested or can take a look at one of the below issues

1. #4595
2. #4525

**Comment by subhajit20** [comment]
> I'll assign this issue to @RaghavRox if he is still interested since we try to follow `first come, first serve` when assigning issues.
> 
> Sry for the confusion @subhajit20 you can pick this up if @RaghavRox is no longer interested or can take a look at one of the below issues
> 
> 1. [[Feature] Add tenant-ID as a field to all KafkaStore events #4595](https://github.com/juspay/hyperswitch/issues/4595)
> 2. [[FEATURE] Adding Audit events for payment core operations #4525](https://github.com/juspay/hyperswitch/issues/4525)

Allright!!

**Comment by lilyTokens** [comment]
The multi-PSP routing logic here is interesting. I have been thinking about similar state machine patterns in an agentic context where the agent needs to decide which action to take based on accumulated context, and the transition logic gets complex fast. The approach of encoding routing rules as explicit configuration rather than imperative code makes the system much easier to audit and debug. Good design pattern regardless of the payment domain.
