### ISSUE TITLE
[Feature] Add a cargo binary for running diesel migrations locally

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4589]
### Objective
Add a new binary in the `router` crate that would run migrations locally via cli i.e `cargo run migrations`.

### Context
Currently migrations are managed via the diesel_cli which rely on explicitly providing the database username/password & host,
This is a bit cumbersome when you have to provide the variables over & over again.

```bash
diesel migration --database-url postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME run
```

It would be somewhat easier if we could leverage [`diesel_migrations`](https://docs.rs/diesel_migrations/latest/diesel_migrations/) to read the credentials from config file / env & apply migrations.

(Open to alternative approaches as well for this)

### Outcomes
- A new rust binary that can be used for running local db migrations from file
- Updates to the local setup documentation outlining the usage of this cli tool

**Comment by davidkurilla** [comment]
I am interested in taking on this issue!

**Comment by lsampras** [comment]
Hey @davidkurilla , thanks for your interest.
I'm assigning you this issue, you can ask any doubts here or reach out to me or @SanchithHegde  on our slack/discord.
