### ISSUE TITLE
[Feature] Add tenant-ID as a field to all KafkaStore events

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4595]
### Context
In-order to support multi-tenancy we need to store data partioned via tenant-id.
In order to do that for kafka events we need to pass tenant-id as a field in the generated kafka events

We can use the KafkaStore field added in #4512 to add them to events in Kafka

### Approach
1. Add a new field in `KafkaEvent` struct representing tenant_id

```rust
#[derive(serde::Serialize, Debug)]
struct KafkaEvent<'a, T: KafkaMessage> {
    #[serde(flatten)]
    event: &'a T,
    sign_flag: i32,
    tenant_id: TenantID
}
```

Alternate approaches can be discussed in the issue

**Comment by subhajit20** [comment]
hey @lsampras I am taking this issue.
