### ISSUE TITLE
[FEATURE] Alipay and WeChat integration

### ISSUE THREAD

**Issue by 9cat** [juspay/hyperswitch#462]
### Feature Description

 alipay and wechat pay needed

### Possible Implementation

 alipay and wechat pay needed

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by SanchithHegde** [comment]
Hey @9cat, thanks for raising this feature request. We'll consider your request against our roadmap and incorporate it at the appropriate time.

Have a good day!

**Comment by SanchithHegde** [comment]
Closing this as completed.
Alipay: #1048, #1140
WeChat: #1049
