### ISSUE TITLE
Add audit events for PaymentCreate update

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4672]
Created from https://github.com/juspay/hyperswitch/issues/4525

This covers adding events for PaymentCreate operation

This event should include the payment data similar to https://github.com/juspay/hyperswitch/pull/4166

It should also include any metadata for the event
e.g reason for payment rejection, error codes, rejection source etc

**Comment by aadityasinha-dotcom** [comment]
Hi @lsampras, is this issue available?

**Comment by lsampras** [comment]
Hey @aadityasinha-dotcom thanks for the interest, yeah this issue is available.

**Comment by Rutam21** [comment]
@swangi-kumari This issue has been inactive for a long time now. I want to take this up. Kindly assign this to me. Thanks.

**Comment by gorakhnathy7** [comment]
Hey @aadityasinha-dotcom Are your still working on this issue?

**Comment by gorakhnathy7** [comment]
Hey @Rutam21 let's know if you're still interested in working on this issue?

**Comment by Rutam21** [comment]
@gorakhnathy7 Yes, I am interested to work on this issue. Please assign this to me.

**Comment by Rutam21** [comment]
@gorakhnathy7 I am starting to work on this issue now as I have already raised a PR for my last assigned issue.
