### ISSUE TITLE
Add audit events for CompleteAuthorize update

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4674]
Created from #4525 

This covers adding events for Complete Authorize operation

This event should include the payment data similar to [PaymentCancel](https://github.com/juspay/hyperswitch/pull/4166)

It should also include any metadata for the event  
e.g reason for payment rejection, error codes, rejection source etc

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by hex1c** [comment]
Hi @gorakhnathy7 , can you assign me this issue. i would like to work on it.

**Comment by gorakhnathy7** [comment]
Hey @hex1c Assigning the issue to you, thanks for your interest.
