### ISSUE TITLE
Add audit events for PaymentStatus update

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4677]
Created from #4525 

This covers adding events for PaymentStatus operation

This event should include the payment data similar to [PaymentCancel](https://github.com/juspay/hyperswitch/pull/4166)

It should also include any metadata for the event  
e.g reason for payment rejection, error codes, rejection source etc

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by XmchxUp** [comment]
@lsampras hi, can I take this issue?

**Comment by MridulQB** [comment]
Hey I want to work on this
Can you assign this to me

**Comment by MridulY** [comment]
Hey I want to work on this
Can you please assign this to me

**Comment by qstommyshu** [comment]
Hi, I can help on this issue

**Comment by qstommyshu** [comment]
Hi @lsampras and @gorakhnathy7 ,

I would like to help on this. All my other issues are done, just waiting for code review and merging.

**Comment by gorakhnathy7** [comment]
Already assigned another issue, @qstommyshu.
