### ISSUE TITLE
Add audit events for PaymentApprove update

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4680]
Created from #4525 

This covers adding events for PaymentApprove operation

This event should include the payment data similar to [PaymentCancel](https://github.com/juspay/hyperswitch/pull/4166)

It should also include any metadata for the event  
e.g reason for payment rejection, error codes, rejection source etc

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by gorakhnathy7** [comment]
Hey @Jayanth-M0625 There is another issue assigned to you, kindly submit that one so that i can assign another issue to you!

**Comment by gorakhnathy7** [comment]
Hey @paradoxxx09 Assigning this issue to you, Thanks for your interest!

**Comment by gorakhnathy7** [comment]
Hey @paradoxxx09 


Kindly let us know, if you're still working on the issue? If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by Rutam21** [comment]
@gorakhnathy7 I would like to take this up. Please assign this to me. Thanks.

**Comment by Rutam21** [comment]
@gorakhnathy7 I have started working on this issue. Assign this to me whenever you're available. Thanks,
