### ISSUE TITLE
Add audit events for PaymentUpdate update

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#4682]
Created from #4525 

This covers adding events for PaymentUpdate operation

This event should include the payment data similar to [PaymentCancel](https://github.com/juspay/hyperswitch/pull/4166)

It should also include any metadata for the event  
e.g reason for payment rejection, error codes, rejection source etc

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by Jayanth-M0625** [comment]
Can I get assigned this issue or other Rust issues that are similar to this one?

**Comment by gorakhnathy7** [comment]
Hey Guys, request you to complete your currently assigned issue to get next issues to work upon.

**Comment by gorakhnathy7** [comment]
Hey @Rutam21 Assigned the issue to you, Happy coding🥳

**Comment by Rutam21** [comment]
Thanks @gorakhnathy7 🙂

**Comment by gorakhnathy7** [comment]
Hey @Rutam21 



Kindly let us know, if you're still working on the issue? If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by Rutam21** [comment]
Hello @gorakhnathy7 , I will raise the PR by EOD and will take up another issue after that that I have commented on. Thanks for checking on this one.
