### ISSUE TITLE
add unit tests for glopalpay Connector

### ISSUE THREAD

**Issue by ArjunKarthik** [juspay/hyperswitch#474]
### Feature Description

As part of adding unit tests to existing connectors we are adding test for globalpay

### Possible Implementation

add a test file for globalpay connector in the crates/router/tests folder

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by jagan-jaya** [comment]
Closing in favour of #471
