### ISSUE TITLE
[FEATURE] add payment methods afterpay, klarna, affirm for adyen connector

### ISSUE THREAD

**Issue by ArjunKarthik** [juspay/hyperswitch#488]
### Feature Description

Support for payment methods afterpay, klarna and affirm should be added for adyen connector

### Possible Implementation

Implementation is similar to card payment method. Newly adding payment method should support following flows,

1. Authorise
2. Capture
3. Cancel
4. Refund
5. Webhook

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by SanchithHegde** [comment]
Closed in #516.
