### ISSUE TITLE
bug(events): update the ApiEventsType for `PaymentsSessionResponse` to use payments flow

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch#5059]
update the `ApiEventMetric` trait for this response to return `ApiEventsType::Payment { payment_id : String}` variant.
based on the payment id stored in its body

This would help for better structuring and help list this api call in the dashboard events as well

**Comment by tanbirali** [comment]
I am interested

**Comment by aayushdhiman01** [comment]
I would like to work on this issue.

**Comment by lsampras** [comment]
Assigning this issue to @tanbirali since he asked first.
@aayushdhiman01 you can take a look at similar open issues.
