### ISSUE TITLE
[FEATURE] Populate status code and delivery attempt information in outgoing webhooks ClickHouse events

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#5070]
### Description

As of opening this issue, the outgoing webhooks ClickHouse events contain a few fields:

https://github.com/juspay/hyperswitch/blob/ca61e47585071865cf7df5c05fdbe3f57818ca95/crates/router/src/events/outgoing_webhook_logs.rs#L11-L21

There are `error` and `is_error` fields that indicate whether an error occurred when delivering the webhook to the merchant server, but do not include any information on whether the merchant server even received the webhook.

To address this issue, we must include the following optional fields in the ClickHouse events:

- `status_code`
- `delivery_attempt`
- `initial_attempt_id`

The fields would have to be added in the `OutgoingWebhookEvent` struct, and the corresponding columns must be added in the ClickHouse table. Once the fields have been added in code, the fields must be populated from the [`Event` in the database](https://github.com/juspay/hyperswitch/blob/ca61e47585071865cf7df5c05fdbe3f57818ca95/crates/router/src/types/domain/event.rs#L15-L31):

- The `delivery_attempt` and `initial_attempt_id` are available directly in the `Event` struct.
- The `status_code` field is available within the `response` struct, if the webhook was delivered to the merchant server.

**Comment by thegeek13242** [comment]
Hi @lsampras @SanchithHegde ,
I am willing to work on this issue please assign it to me

**Comment by lsampras** [comment]
Hey @thegeek13242 thanks for your interest,
have assigned you the issue.

You can find the docs about setting up clickhouse locally for testing [here](https://github.com/juspay/hyperswitch/blob/main/crates/analytics/docs/README.md). Can ask any doubts/questions about this on the issue or our discord/slack channels.

Good luck.... 🍀

**Comment by Loaki07** [comment]
Hi @SanchithHegde @lsampras,

I see this issue is currently assigned. I'm interested to work on it if it becomes available.

**Comment by SanchithHegde** [comment]
@thegeek13242 Could you let us know if you've started any work on this issue, since I see there's a PR open (#5383) by @Loaki07 for the same?
