### ISSUE TITLE
[CYPRESS] : Add Checkout Connector

### ISSUE THREAD

**Issue by Gnanasundari24** [juspay/hyperswitch#5893]
**Description:**
This task involves adding a payment connector for the checkout functionality in Cypress. 
For reference, similar connectors have already been implemented in the repository. You can refer to the existing connectors here:
https://github.com/juspay/hyperswitch/tree/main/cypress-tests/cypress/e2e/PaymentUtils

**Pre-requisites:**

- Cypress is the testing framework that Hyperswitch is using to run automated tests. Having good grip on Javascript to work on Cypress is a must.
- Please follow the [README](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/readme.md) for guidelines on file structure, formatting and instructions on how to set up and run Cypress.

**Steps:**

1.  Add the checkout connector .js files under the PaymentUtils directory:
    [PaymentUtils Directory](https://github.com/juspay/hyperswitch/tree/main/cypress-tests/cypress/e2e/PaymentUtils)

2.  Add the card details and corresponding test case functions for checkout, following the format used in the [Cybersource.js connector](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js).

3.  In the checkout connector, map the test cases and statuses properly. To do this, use the below dashboard credentials where checkout is already configured, test the flows, and then assign the correct statuses.

URL: https://integ.hyperswitch.io
Username, Password: Please drop a comment requesting credentials. The Creds are only shared on request

**Test Cases:**

-  Add test cases only for card payments.

**Postman collection for reference**
https://www.postman.com/altimetry-participant-63653904/hyperswitch

Note: 

- Test cases for other payment methods should be skipped.
- The test cases are already written under PaymentTest:
- [PaymentTest Directory](https://github.com/juspay/hyperswitch/tree/main/cypress-tests/cypress/e2e/PaymentTest).Just map the test cases and their statuses in the config.js file.

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by gorakhnathy7** [comment]
Hey @wttc-nitr Assigning the issue to you, Happy coding!

**Comment by wttc-nitr** [comment]
`URL: https://integ.hyperswitch.io/
Username, Password: Please drop a comment requesting credentials. The Creds are only shared on request`
where to get credentials ?

**Comment by Gnanasundari24** [comment]
Hey @wttc-nitr ,
pub key - pk_snd_a1f96dd7aff44a44a21ffa493ce96220
profile id --- pro_XGEJyvNZahagf3AOrnFE
api key - https://privnote.com/6iTNlDx8#18fxZXSMg -   Please open this and
copy the API key.
