### ISSUE TITLE
[CYPRESS] : Add Noon Connector

### ISSUE THREAD

**Issue by Gnanasundari24** [juspay/hyperswitch#5895]
**Description:**

This task involves adding a connector for the Noon functionality in Cypress. 
For reference, similar connectors have already been implemented in the repository. You can refer to the existing connectors here:
https://github.com/juspay/hyperswitch/tree/main/cypress-tests/cypress/e2e/PaymentUtils

**Pre-requisites:**

- Cypress is the testing framework that Hyperswitch is using to run automated tests. Having good grip on Javascript to work on Cypress is a must.
- Please follow the [README](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/readme.md) for guidelines on file structure, formatting and instructions on how to set up and run Cypress.

**Steps:**

1.  Add the Noon connector .js files under the PaymentUtils directory:
    [PaymentUtils Directory](https://github.com/juspay/hyperswitch/tree/main/cypress-tests/cypress/e2e/PaymentUtils)

2.  Add the card details and corresponding test case functions for Noon, following the format used in the [Cybersource.js connector](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js).

3.  In the Noon connector, map the test cases and statuses properly. To do this, use the below dashboard credentials where Noon is already configured, test the flows, and then assign the correct statuses.

URL: https://integ.hyperswitch.io
Username, Password: Please drop a comment requesting credentials. The Creds are only shared on request

**Test Cases:**

-  Add test cases only for card payments.
- Test creds for noon https://docs.noonpayments.com/test/cards

**Postman collection for reference**

https://www.postman.com/altimetry-participant-63653904/hyperswitch

Note: 

- Test cases for other payment methods should be skipped.

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by SlaydeSequeira** [comment]
i forked the repo and added a test case and tried if it works on cyprus i then added more test cases for card payments 
![Screenshot 2024-10-02 203837](https://github.com/user-attachments/assets/0b7a4155-861d-43ac-83f7-e039f289082d)
these test cases include too short cvv, invalid date, invalid card number etc. pls assign it to me so i can submit my pull request.
Thank you.

**Comment by gorakhnathy7** [comment]
Hey @SlaydeSequeira Assigned this issue to you, thanks!

**Comment by SlaydeSequeira** [comment]
i created a pull request for the same issue 
i labeled the request #5895

**Comment by gorakhnathy7** [comment]
Hey @SlaydeSequeira Kindly link the PR to this issue.
