### ISSUE TITLE
[CYPRESS_FRAMEWORK] Re-use config update commands

### ISSUE THREAD

**Issue by pixincreate** [juspay/hyperswitch#5913]
**Description:**

Cypress is the testing framework that Hyperswitch uses to run automated tests. Having good grip on Javascript to work on Cypress is a must.

Cypress makes use of custom [commands](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/cypress/support/commands.js) to make requests and parse responses instead of having the exchange put in a spec file. This increases the code redundancy. Custom commands are versatile that helps in reducing command duplication. These commands should be generic and should be capable of handling multiple requests of same / similar type.  

**The problem:**

Currently, there exist `3` implementations that makes update config request for different purposes:

- [autoRetryConfig](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/support/commands.js#L2229-L2255)
- [setMaxAutoRetries](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/support/commands.js#L2257-L2282)
- [stepUp](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/support/commands.js#L2312-L2334)

These are called by [Retries](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js) tests under Routing specs.

**Getting started:**

Go through the [README](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/readme.md) for guidelines on file structure, formatting and instructions on how to set up and run Cypress.

In short:

```sh
cd cypress-tests
npm ci
```

**Possible implementation:**

Refactor config update `context`s in the spec file (for example: [Update max auto retries](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js#L102-L108), [Enable auto retries](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js#L46-L48), [Step up](https://github.com/juspay/hyperswitch/blob/45c19a1729af3f4b80bde2661868cb213138df86/cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js#L482C10-L483C14)) and pass as all the necessary data into the new unified command in [commands](https://github.com/juspay/hyperswitch/blob/main/cypress-tests/cypress/support/commands.js)

**Additional info:**

- Language: Javascript
- Difficulty: Easy

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by Ankesh2004** [comment]
Hi @pixincreate , I would like to work on this issue. Please assign it to me.

**Comment by Ankesh2004** [comment]
@pixincreate Kindly review the PR
