### ISSUE TITLE
[REFACTOR]: [CYBERSOURCE] Add amount conversion framework to Cybersource

### ISSUE THREAD

**Issue by mrudulvajpayee4935** [juspay/hyperswitch#5942]
### :memo: Feature Description

Currently, amounts are represented as `i64` values throughout the application. We want to introduce a `Unit` struct that explicitly states the denomination. A new type, `MinorUnit`, has been added to standardize the flow of amounts across the application. This type will now be used by all the connector flows.

Rather than handling conversions in each connector, we will centralize the conversion logic in one place within the core of the application.

### :hammer: Possible Implementation

- For each connector, we need to create an amount conversion function. Connectors will specify the format they require, and the core framework will handle the conversion accordingly.
- Connectors should invoke the `convert` function to receive the amount in their required format.
- Refer to the [connector documentation](https://developer.cybersource.com/docs/cybs/en-us/api-fields/reference/all/so/api-fields/original-transaction-amount.html) to determine the required amount format for each connector.
- You can refer [this PR](https://github.com/juspay/hyperswitch/pull/4825) for more context.

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/` , `crates/router/src/types/api.rs` , `crates/router/tests/connectors/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### :package: Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

###  :sparkles: Are you willing to submit a PR?

**Comment by Ankesh2004** [comment]
Hi @gorakhnathy7  @mrudulvajpayee4935  , I would like to work on this issue. Please assign  it to me.

**Comment by mrudulvajpayee4935** [comment]
> Hi @gorakhnathy7 @mrudulvajpayee4935 , I would like to work on this issue. Please assign it to me.

hey @Ankesh2004, Thanks for your interest, I have assigned you [this](https://github.com/juspay/hyperswitch/issues/5943), i would suggest to keep working on it.
Please reach out here, once that is done.
This will help us maintain fairness in the assignment process.

**Comment by gauravghodinde** [comment]
hey @gorakhnathy7 @mrudulvajpayee4935 as no one is assigned this issue currently, can you assign it to me?

**Comment by gorakhnathy7** [comment]
Hey @gauravghodinde Assigning the issue to you, Thanks for your interest!
