### ISSUE TITLE
[REFACTOR] Update Database Connection Functions for Read Operations

### ISSUE THREAD

**Issue by ThisIsMani** [juspay/hyperswitch#5965]
### Feature Description

Currently, in our codebase, we are using `pg_connection_write` for database operations even when performing read operations, which is inefficient. The `pg_connection_write` function should only be used when we need to perform write operations. For read operations, we should use `pg_connection_read` to optimize resource usage.

### Possible Implementation

Find occurrences of the usage of `pg_connection_write` for read operations and replace them with `pg_connection_read` in the following files:

- `crates/router/src/db/role.rs`
- `crates/router/src/db/user.rs`
- `crates/router/src/db/user_role.rs`
- `crates/router/src/db/dashboard_metadata.rs`

1. Open each of the specified files and search for functions that are performing read operations (for e.g., `find_by_*`, `get_*`) but are using `pg_connection_write`.
2. Replace the usage of `pg_connection_write` with `pg_connection_read` in these functions.
3. Ensure that the database calls still behave correctly and no write operations are mistakenly changed.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by zeel991** [comment]
Hey  @ThisIsMani according to the description , the files , namely `dashboard.rs` , `user_role.rs` , `user.rs` and ` role.rs` , have methods which either read from the database or write or maybe update the database using `pg_connection_write()`  , so to solve this problem , we need to identify where the database is used to read , like in functions like `find_by_user_email()` and change the `pg_connection_write()` to `pg_connection_read()` , If I am correct, I would like to go ahead and work on this issue

**Comment by ThisIsMani** [comment]
Hey @zeel991,
Thanks for showing interest in contributing to Hyperswitch! This issue is open for contributions, and you can work on it. It's also part of Hacktoberfest 2024, If you work on resolving it during Hacktoberfest, you'll be eligible to claim a goodie as a reward.

Regarding your query, you are correct! you will have to identify all the places where `pg_connection_read()` should've used instead of `pg_connection_write()`.

**Comment by gorakhnathy7** [comment]
Hey @zeel991 Let us know if you are working on this, so it can be assigned to you.
Thanks!

**Comment by zeel991** [comment]
> Hey @zeel991 Let us know if you are working on this, so it can be assigned to you. Thanks!

Yes , I am working on this issue , please assign it to me !

**Comment by zeel991** [comment]
@ThisIsMani Since the Hactoberfest starts considering the PRs from 1st October , would it be Ok if I raise the PR on 1st October?

**Comment by Boweresjack3l** [comment]
__

**Comment by gorakhnathy7** [comment]
Hey @zeel991 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
