### ISSUE TITLE
[FEATURE] Add functionality to generate and delete sample disputes based on payment count in sample data

### ISSUE THREAD

**Issue by apoorvdixit88** [juspay/hyperswitch#5991]
### Feature Description
This issue consists of two parts that must be resolved sequentially:
Part 1: #6111
Part 2: #6117

The [/sample_data](https://github.com/juspay/hyperswitch/blob/5a36252d3f6738367e065dd45764ac1eb3f7ea5e/crates/router/src/routes/app.rs#L2024) API currently generates sample data for payments and refunds, with refunds making up 20% of the payments. We need to extend the functionality to generate disputes based on the number of payments generated:

2 disputes if the number of generated payments is between 50-100
1 dispute if the number of generated payments is less than 50.
Current Behavior:
- The /sample_data API generates payments and refunds, but no disputes are generated.
Expected Behavior:

The DELETE request to /sample_data should also delete these sample disputes when cleaning up the data.

### Possible Implementation

Affected Code:
The current route configuration is as follows:
```
route = route.service(
    web::resource("/sample_data")
        .route(web::post().to(user::generate_sample_data))  // Modify to generate disputes based on payment count
        .route(web::delete().to(user::delete_sample_data)), // Modify to delete generated disputes
)
```
- Modify the generate_sample_data function:
    If 50-100 payments are generated, create 2 sample disputes.
    If less than 50 payments are generated, create 1 sample dispute.
- Modify the delete_sample_data function to ensure the disputes are deleted when cleaning up.
- Test the functionality to ensure the correct number of disputes are generated and deleted based on the payment count.

Additional Context:
This change ensures that sample disputes are proportionally generated based on the volume of payments, allowing for more realistic sample data and better coverage for testing dispute-related processes.

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by qstommyshu** [comment]
Hi! I would like to help on this!

**Comment by apoorvdixit88** [comment]
Hi @qstommyshu,

Thank you for your willingness to help! I've split the issue into two parts:

Part 1: #6111 This involves writing the database logic.
Part 2: # 6117 This focuses on generating random disputes based on the specified criteria, and it can be tackled only after Part 1 is completed.

Please start with Part 1, and feel free to reach out if you have any questions or need assistance. Looking forward to your contributions!

**Comment by qstommyshu** [comment]
Got it, thanks. I'll take a look and let you know if I need help!

**Comment by apoorvdixit88** [comment]
Sure, take a look and let us know if you're interested in submitting a PR for this. If so, I will assign this issue to you.

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 ,

I've reviewed issues #6111 and #6117, and I think both the instructions are clear. Please assign this two issues to me. I will set up the dev environment today and get start working on the issues. Thanks!

**Comment by apoorvdixit88** [comment]
Please comment on both issues, so that i can assign

**Comment by apoorvdixit88** [comment]
This is done, since both the linked issues are merged.

**Comment by gorakhnathy7** [comment]
Hey @qstommyshu 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
