### ISSUE TITLE
[REFACTOR]: [RAPYD] Add amount conversion framework to Rapyd

### ISSUE THREAD

**Issue by mrudulvajpayee4935** [juspay/hyperswitch#6020]
### :memo: Feature Description

Currently, amounts are represented as `i64` values throughout the application. We want to introduce a `Unit` struct that explicitly states the denomination. A new type, `MinorUnit`, has been added to standardize the flow of amounts across the application. This type will now be used by all the connector flows.

Rather than handling conversions in each connector, we will centralize the conversion logic in one place within the core of the application.

### :hammer: Possible Implementation

- For each connector, we need to create an amount conversion function. Connectors will specify the format they require, and the core framework will handle the conversion accordingly.
- Connectors should invoke the `convert` function to receive the amount in their required format.
- Refer to the [connector documentation](https://docs.rapyd.net/en/create-refund.html) to determine the required amount format for each connector.
- You can refer [this PR](https://github.com/juspay/hyperswitch/pull/4825) for more context.

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/` , `crates/router/src/types/api.rs` , `crates/router/tests/connectors/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### :package: Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by gorakhnathy7** [comment]
@ankkyprasad Assigning this to you!

**Comment by gorakhnathy7** [comment]
Hey @ankkyprasad  ,

Quick check-in on the status of this issue. If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by qstommyshu** [comment]
Hi,

I would like to contribute to this issue if there is no update.

**Comment by gorakhnathy7** [comment]
Hey @qstommyshu You have already been assigned another issue, let me know if you want to work on this one instead.

**Comment by qstommyshu** [comment]
I should be able to finish my other tickets within this week then I would be available for this one.

**Comment by gauravghodinde** [comment]
hey @gorakhnathy7  as no one is assigned this issue currently, can you assign it to me?

**Comment by gorakhnathy7** [comment]
Sure @gauravghodinde

**Comment by gorakhnathy7** [comment]
Hey @gauravghodinde 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
