### ISSUE TITLE
[BUG] Unable to deserialize `bank_of_china` as `common_enums::enums::BankNames`: Matching variant not found

### ISSUE THREAD

**Issue by Niek** [juspay/hyperswitch#6025]
### Bug Description

A fresh checkout, running `docker compose up` and I see this error:
```
migration_runner-1            |    Compiling equivalent v1.0.1
migration_runner-1            |    Compiling hashbrown v0.14.5
migration_runner-1            |    Compiling indexmap v2.5.0
migration_runner-1            |    Compiling memchr v2.7.4
migration_runner-1            |    Compiling utf8parse v0.2.2
migration_runner-1            |    Compiling once_cell v1.19.0
migration_runner-1            |    Compiling winnow v0.6.19
pg-1                          | 2024-09-25 10:34:58.401 UTC [75] FATAL:  role "root" does not exist
hyperswitch-server-1          | thread 'main' panicked at crates/router/src/bin/router.rs:16:10:
hyperswitch-server-1          | Unable to construct application configuration: Application configuration error
hyperswitch-server-1          | ├╴at crates/router/src/configs/settings.rs:755:14
hyperswitch-server-1          | │
hyperswitch-server-1          | ╰─▶ bank_config.?.fiuu.banks: Some errors occurred:
hyperswitch-server-1          |     Unable to deserialize `bank_of_china` as `common_enums::enums::BankNames`: Matching variant not found
hyperswitch-server-1          |     ├╴at crates/router/src/configs/settings.rs:754:14
hyperswitch-server-1          |     ╰╴Unable to deserialize application configuration
hyperswitch-server-1          | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
migration_runner-1            |    Compiling darling_core v0.20.10
hyperswitch-server-1 exited with code 101
dependency failed to start: container hyperswitch-hyperswitch-server-1 exited (101)
```

### Expected Behavior

The `hyperswitch-server` service will start

### Actual Behavior

The `hyperswitch-server` service crashes

### Steps To Reproduce

```bash
git clone --depth 1 --branch latest https://github.com/juspay/hyperswitch
cd hyperswitch
docker compose up
```

### Environment

Are you using hyperswitch hosted version? No

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution: Debian 12
2. Rust version (output of `rustc --version`): Not relevant, docker version
3. App version (output of `cargo r --features vergen -- --version`): Not relevant, docker version

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by SanchithHegde** [comment]
Hey @Niek, could you please confirm that you correctly checked out to the `latest` tag and then ran the Docker Compose setup?

This error may occur when trying to run the Docker Compose setup from the `main` branch of our repository, but shouldn't happen on the `latest` tag. Could you also please confirm that the `latest` tag correctly points to the `v1.111.2` tag by running the following command and sharing the output with us?
```shell
git log --oneline -n 1 latest
```

**Comment by Niek** [comment]
Thanks @SanchithHegde - the branch was indeed the issue, I was on `main`. My bad, apologies! Closing this now.

**Comment by SanchithHegde** [comment]
No worries!
