### ISSUE TITLE
[FEATURE] Validate card numbers when accepting payment method information

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#606]
### Feature Description

As of now, we just pass the card information to the payment processor without performing any form of validation on the provided card number. It'd be great if the card number could have been validated on our end whenever a payment is being created or payment method is being created, instead of invalid card numbers being caught by the payment processor.

It'd be preferable if the card number validation logic is included in a new crate called `cards` which would contain this validation of card numbers and card brand identification logic (taken up on #379). This must check that the card number provided is of correct length, and also handle whitespaces being included in the card number input. Please also include unit tests in your PR.

_For external contributors, clarify any questions you may have, and let us know that you're interested in picking this up. We'll assign this issue to you to reduce duplication of effort on the same task._

### Possible Implementation

For validating card numbers, you can use the [Luhn Algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm). I'm thinking of an API like so (refer to [the newtype pattern](https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html)):

```rust
use masking::StrongSecret;

struct CardNumber(StrongSecret<String>);

let card_number = CardNumber::from_str("..."); // You can use the `FromStr` trait for this purpose
```

This would ensure that a `CardNumber` once constructed is always valid and no further validation is necessary. You can also implement `Serialize` and `Deserialize` traits on `CardNumber`.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by phillyphil91** [comment]
Hi.

I would like to take a look at this.

**Comment by hemantku** [comment]
Is someone working on this already?

**Comment by phillyphil91** [comment]
Hi @SanchithHegde, 
I'm currently working on this and wondering about error handling. For example when the CC number validation would fail. Should I create a new error type for this? Is there a central place for errors?
I saw: `crates/router/src/core/errors.rs` not sure if it would make sense to include this there. 

I saw that `StrongSecret::from_str(s)` is Infallible. So I probably don't have to worry about this, if my assumption is correct.
I am mainly concerned with the associated type Err in the FromStr trait.
```rust
impl FromStr for CardNumber {                                                                                                                  
    type Err = Box<dyn std::error::Error>;
```

**Comment by SanchithHegde** [comment]
@phillyphil91 

> Should I create a new error type for this?

Yes, you can have it as an enum if there are multiple possible card number validation errors. Otherwise, a unit struct should suffice.

> Is there a central place for errors?

If you're adding this card validation logic in a new crate, you can include the card validation error in the same crate. 

> I saw that `StrongSecret::from_str(s)` is Infallible. So I probably don't have to worry about this, if my assumption is correct.

Correct. It should suffice to check if the string input received is valid or not.
