### ISSUE TITLE
[FEATURE] Use newtype pattern for email addresses

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#608]
### Feature Description

This issue covers one of the problems mentioned in #119, about using [the newtype pattern](https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html) for email addresses. The requirement is that email addresses must be validated once during construction/deserialization and should never be validated again. This would also eliminate the validation being performed at the time of masking email addresses (specifically line 97 in the snippet):

https://github.com/juspay/hyperswitch/blob/d107b44fd356f172ef7c9535567d266a6301e43d/crates/common_utils/src/pii.rs#L87-L109

Please also include unit tests in your PR.

_For external contributors, clarify any questions you may have, and let us know that you're interested in picking this up. We'll assign this issue to you to reduce duplication of effort on the same task._

### Possible Implementation

You can use a newtype like so:

```rust
use masking::Secret;

struct Email(Secret<String>);

let email = Email::from_str("..."); // You can use the `FromStr` trait for this purpose
```

For validating emails, the existing regex validation should suffice. Also, implement `Serialize`, `Deserialize` and `masking::Strategy` for `Email`.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by phillyphil91** [comment]
Hi,
I am not accustomed to the hyperswitch code base, but I would like to take a look at this issue. Will probably need some help though.

**Comment by SanchithHegde** [comment]
Hey @phillyphil91, I'm afraid there's already a WIP PR for this issue by @nachiketkanore. 

If you're interested, you can take a look at #606. I can answer any questions you may have about that issue.

**Comment by phillyphil91** [comment]
Ah sorry. I overlooked that. #606 sounds good.

**Comment by SanchithHegde** [comment]
No problem, please leave a comment on the issue that you're interested, and I'll assign it to you.
