### ISSUE TITLE
[FEATURE] Extend the BatchSampleDataInterface Trait for Disputes

### ISSUE THREAD

**Issue by apoorvdixit88** [juspay/hyperswitch#6111]
### Feature Description
The issue is sub part of issue: #5991 

We currently have a feature for generating sample data, which includes batch insertion of payments and refunds. The feature inserts payments and refunds in batches using the BatchSampleDataInterface trait. We need to extend this functionality to support batch insertion and deletion of disputes as well.

Steps to Implement Batch Support for Disputes

**Extend the BatchSampleDataInterface Trait**
We need to extend the existing BatchSampleDataInterface to include methods for batch insertion and deletion of disputes. These methods will be similar to the ones already implemented for PaymentIntent, PaymentAttempt, and Refund.

**New Methods for Disputes:**
`insert_disputes_batch_for_sample_data`: This method will handle batch insertion of disputes.
`delete_disputes_for_sample_data`: This method will handle (batch) deletion of disputes.

### Possible Implementation

Add Functions for Dispute Insert and Delete in `BatchSampleDataInterface`
- File: `crates/router/src/db/user/sample_data.rs`
- Extend the existing BatchSampleDataInterface to include the methods for inserting and deleting disputes.

Complete these interface functions for Store, Mock Db and Kafka like we did for other functions.

Write Batch Insert and Delete Queries for Disputes
- File: `crates/diesel_model/src/query/user/sample_data.rs`
 - Define the queries (using diesel) to handle batch insertion and deletion of disputes, similar to how they are handled for payments and refunds.
 
 
To test we can hard code some dummy dispute and try inserting using the function we made in core. We can check Db and see the logs for the query that is getting printed.

Steps for Testing Dispute Batch Insertion and Deletion
- To verify the batch insertion and deletion of disputes using the functions implemented in the BatchSampleDataInterface, we can perform a simple test by hardcoding some dummy dispute data. 
- Once we have the dummy dispute data, we can use the `generate_sample_data_for_user`  method from the core function to insert the disputes into the database. This should invoke the appropriate batch insertion logic. (Or we can make an api to test the behaviour when the function is invoked)
Curl to invoke this core function:
```
curl --location 'http://localhost:8080/user/sample_data' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data '{

}'
```
The JWT token we can get from signup and then skipping the 2FA:
```
curl --location 'http://localhost:8080/user/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "JohnTest@test.com",
    "password": "Test@321"
}'
```
This will give an intermediate token in response, we need to use this token to skip 2FA
```
curl --location 'http://localhost:8080/user/2fa/terminate?skip_two_factor_auth=true' \
--header 'Authorization: Bearer Intermediatetoken'
```
This will give us JWT Token that we can use to hit the sample_data api
Curl to delete sample data (The core function for sample dispute delete can be used to our advantage):
```
curl --location --request DELETE 'http://localhost:8080/user/sample_data' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data '{

}'
```
- We can check Database Logs and Printed Queries whether the appropriate queries are getting printed
- We can also manually check DB 

Note: Omit the Code for Testing part in the PR raised, have only Insert and Delete logic related to the DB, include the relevant logs and screenshots after test.
The Sample disputes generation part, we will be handling in the separate PR. (#6117 )

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 , I can help on this.

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 ,

Just wondering which commit should I use as my branch base? I can successfully run hyperswitch using `docker compose up -d` (I suppose this is production environment?). However, I tried to run the development environment on tagged revision v1.111.3 following [this guide](https://github.com/juspay/hyperswitch/blob/602f50b939f320ea9d85dff28dfe3f5c65afeb70/docs/try_local_system.md#set-up-a-development-environment-using-docker-compose) but failed. I think I need some guide on setting up the dev environment.

Here is a screen shot of what I encountered:
I'm on branch tagged v1.111.3
<img width="1570" alt="image" src="https://github.com/user-attachments/assets/a1611702-565c-4b58-919b-7643b15bbcc0">

Please let me know how to set up the development environment. Thanks!

**Comment by apoorvdixit88** [comment]
Hey @qstommyshu I will suggest to use docker to run all the services, but for hyperswitch server, you can run it locally [Set up Rust and other dependencies natively](https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#set-up-dependencies-on-ubuntu-based-systems) it will be better for local develelpment.

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 ,
I've finished working on this issue. Here is the result:

Before sending a `POST` request to `/sample_data`:
table `payment_intent` starts with 18 non-generated records:
<img width="878" alt="image" src="https://github.com/user-attachments/assets/b6ac2501-8399-46ab-b210-c0d644a1249c">

and table `dispute` does not have any records:
<img width="756" alt="image" src="https://github.com/user-attachments/assets/472c4622-63ee-46e5-86e3-ec3fd6af7959">

After sending a `POST` request to `/sample_data`:
<img width="1576" alt="image" src="https://github.com/user-attachments/assets/82887a10-31e7-4689-9a86-4105abf69757">

table `payment_intent` now has 118 records:
<img width="885" alt="image" src="https://github.com/user-attachments/assets/fa50261a-58fa-41cf-ba65-4d1ffc26d311">

table `dispute` has 100 records with prefixed `test_` dispute_id, payment_id, attempt_id, connector_dispute_id
<img width="908" alt="image" src="https://github.com/user-attachments/assets/94ebb82c-958b-490a-ac2f-6d24c6c12444">

We can also tell disputes are generated from diesel logs, for example, the highlighted area is a generated dispute as we can see keywords `PreArbitration` and `DisputeOpened`.
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/7f32f4f2-6259-4999-b721-aed3ec3e6e19">

Then, we send a `DELETE` request to `/sample_data`:
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/605be969-7407-40f5-b829-86a671127587">

We are now left with the original 18 records in the `payment_intent` table and 0 records for the `dispute` table:
<img width="944" alt="image" src="https://github.com/user-attachments/assets/ab4b4d11-a280-42d4-b499-280349abf983">
<img width="822" alt="image" src="https://github.com/user-attachments/assets/b93d0c6b-0bd4-47c7-b4b9-96694b1b1930">


For now, the `/sample_data` generates as many disputes as payment intents. I will address the dispute number requirement and randomness requirement in #6117.

Should I submit a PR for this issue or you want me to submit a PR that combines this issue and #6117?

**Comment by apoorvdixit88** [comment]
Hey @qstommyshu you can raise PR for this issue first.

**Comment by apoorvdixit88** [comment]
Hey @qstommyshu, the PR looks great. Added few comments, please address.

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 ,

Thanks for the quick reply. I've addressed all your comments.  Please take a look when you are available.

It seems I also accidentally added `resolve #5991` to the latest commit, this might close #5991 after the PR is merged. Do you know how can I fix it?
<img width="566" alt="image" src="https://github.com/user-attachments/assets/06dd3543-7614-4396-a986-966cbc69da8e">

**Comment by apoorvdixit88** [comment]
> Hi @apoorvdixit88 ,
> 
> Thanks for the quick reply. I've addressed all your comments. Please take a look when you are available.
> 
> It seems I also accidentally added `resolve #5991` to the latest commit, this might close #5991 after the PR is merged. Do you know how can I fix it? <img alt="image" width="566" src="https://private-user-images.githubusercontent.com/56746466/375850390-06dd3543-7614-4396-a986-966cbc69da8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDY5ODAsIm5iZiI6MTcyODkwNjY4MCwicGF0aCI6Ii81Njc0NjQ2Ni8zNzU4NTAzOTAtMDZkZDM1NDMtNzYxNC00Mzk2LWE5ODYtOTY2Y2JjNjlkYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDExNTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZTA2ZjQzZTc2Y2M5NjZiMGEwMDhkOWEzZDMzYzliNWNhOTk2N2RkMTllZTYxMWZlNzI3YjkzYmRlZmFiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jb_U6g9JlxUBO6dL-RRjfxzJx9dR26ns3_WjceqvLY0">

For other issue which you mentioned we can do Force Push that removes the issue from commit message. We can Squash commits.
But we can simply open it again after it gets closed. So let it be.

**Comment by gorakhnathy7** [comment]
Hey @qstommyshu 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
