### ISSUE TITLE
[FEATURE] Generate Random Disputes for sample data

### ISSUE THREAD

**Issue by apoorvdixit88** [juspay/hyperswitch#6117]
### Feature Description

The issue is sub part of issue: #5991 (Please refer to this First)
The current implementation of the generate_sample_data_for_user function generates sample data for payments and refunds. However, there is no functionality to generate sample disputes. This issue is about extending the generate_sample_data_for_user function to generate random disputes based on the sample payments created.

Current Behavior
- The /sample_data API generates sample payments and refunds.
- No disputes are generated as part of the sample data generation process.

Expected Behavior
- The generate_sample_data_for_user function should also generate random disputes along with payments and refunds.
- The number of disputes generated should be based on the number of payments created:
     2 disputes if the number of payments is between 50 and 100.
     1 dispute if the number of payments is less than 50.

### Possible Implementation

Modify generate_sample_data_for_user Function:
Update the function in `utils::user::sample_data::generate_sample_data` to create sample disputes based on the number of generated payments.
The Data should be random and fields should be related to sample payments/refunds for which we are creating dispute.
Call the Db function inside `generate_sample_data_for_user` to Batch insert sample disputes
Call the Db function inside `delete_sample_data_for_user` to Delete sample disputes

Test
To generate Sample Data:
```
curl --location 'http://localhost:8080/user/sample_data' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data '{
}'
```

To Delete Sample Data:
```
curl --location --request DELETE 'http://localhost:8080/user/sample_data' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer JWT' \
--data '{

}'

```

### Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 , I can help on this.

**Comment by anshulsoni2010** [comment]
Seems like there's no update

Assign me so I will work on this...

**Comment by qstommyshu** [comment]
> Seems like there's no update
> 
> 
> 
> Assign me so I will work on this...

Hi, I'm working on the prerequisite issue of this issue. This is the second part of an issue I'm working on.

**Comment by qstommyshu** [comment]
Hi @apoorvdixit88 , #6341 is mostly done, please take a look when you are available.

**Comment by gorakhnathy7** [comment]
Hey @qstommyshu 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
