### ISSUE TITLE
[REFACTOR]: [WISE] Add amount conversion framework to Wise

### ISSUE THREAD

**Issue by swangi-kumari** [juspay/hyperswitch#6121]
### :memo: Feature Description

Currently, amounts are represented as `i64` values throughout the application. We want to introduce a `Unit` struct that explicitly states the denomination. A new type, `MinorUnit`, has been added to standardize the flow of amounts across the application. This type will now be used by all the connector flows.

Rather than handling conversions in each connector, we will centralize the conversion logic in one place within the core of the application.

### :hammer: Possible Implementation

- For each connector, we need to create an amount conversion function. Connectors will specify the format they require, and the core framework will handle the conversion accordingly.
- Connectors should invoke the `convert` function to receive the amount in their required format.
- Refer to the [connector documentation](https://docs.wise.com/api-docs/api-reference/card) to determine the required amount format for each connector.
- You can refer [this PR](https://github.com/juspay/hyperswitch/pull/4825) for more context.

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/` , `crates/router/src/types/api.rs` , `crates/router/tests/connectors/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [ ] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [ ] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### :package: Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by ayan-joshi** [comment]
Hey @swangi-kumari , I would like to work on this refactor issue

**Comment by swangi-kumari** [comment]
Hii @ayan-joshi , sure! I've assigned this to you. 
In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm),

**Comment by swangi-kumari** [comment]
> Hi @swangi-kumari , I would like to work on this issue. Please assign it to me.

As we follow a first-come, first-serve basis, I have already assigned this issue to @arya . However, if you're still interested in contributing, feel free to pick another issue from [here](https://github.com/juspay/hyperswitch/issues). We would greatly appreciate your help!

**Comment by Danbaba1** [comment]
Hi @swangi-kumari  I can work on this issue

**Comment by Aryant01** [comment]
Hey! If no one is working on it, I am interested.

**Comment by AmoghPadukone** [comment]
Hi, Can i please work on this issue :)

**Comment by shuklamaneesh23** [comment]
@gorakhnathy7 ,can you please assign this issue to me as there is no assignee at the moment.

**Comment by gorakhnathy7** [comment]
Hey All, Assigning this issue to @Danbaba1 as per first come first serve basis, kindly pick another issue from [here](https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee).

**Comment by gorakhnathy7** [comment]
Hey @Danbaba1 


Kindly let us know, if you're still working on the issue? If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by Danbaba1** [comment]
@gorakhnathy7 I apologize. I have not had time to look at it yet.

**Comment by shuklamaneesh23** [comment]
Hey @gorakhnathy7 , could you please assign this to me as I'm willing to complete it within this hacktoberfest duration. 
Thanks!
