### ISSUE TITLE
[CYPRESS]: Use the SDK to process a payment.

### ISSUE THREAD

**Issue by JeevaRamu0104** [juspay/hyperswitch#6124]
---

### **Title**: Verify Make and View a Test Payment

---

### **Description**:

This task involves testing the "Make a test payment" feature from the homepage. The user will go through the checkout process, entering payment details and viewing the payment summary upon successful payment.

---

### **Test Case**: Make and View a Test Payment

- **Pre-requisites**: None
- **Steps**:
  1. Go to the homepage.
  2. Click on **"Try it out"** in the **"Make a test payment - Try our unified checkout"** message box.
  3. Verify the user is redirected to the **test checkout page**.
  4. Select the currency from the dropdown (e.g., **"EUR"**).
  5. Enter the amount (**77**) in the text box.
  6. Click on **"Show preview"**.
  7. Verify that the **SDK preview** is rendered with the following elements:
     - **"Card number"** text box
     - **"Expiry"** text box
     - **"CVC"** text box
     - **"Save card details"** checkbox
     - **"Pay"** button with the currency and amount
  8. Enter the test card details into the SDK:
     - **Card Number**: 4242 4242 4242 4242
     - **Expiry**: 01/27
     - **CVC**: 492
  9. Verify that the card details are displayed correctly in the respective text boxes.
  10. Click on the **"Pay"** button.
  11. Verify that the **"Payment Successful"** message is displayed.
  12. Click on **"Go to payment"**.
  13. Verify that the user is redirected to the **payment details page**.
  
- **Test Data**:
  - **Currency**: EUR
  - **Amount**: 77
  - **Card Number**: 4242 4242 4242 4242
  - **Expiry**: 01/27
  - **CVC**: 492

- **Expected Results**:
  - The user is redirected to the **test checkout page** after clicking "Try it out."
  - The selected currency (**"EUR"**) should be reflected in the dropdown.
  - The amount (**77**) should be entered and displayed correctly in the text box.
  - After clicking **"Show preview,"** the SDK preview should be rendered with all necessary elements (card number, expiry, CVC, etc.).
  - Test card details should be entered correctly, and the payment form should reflect the correct input.
  - Upon clicking **"Pay,"** a **"Payment Successful"** message should be displayed.
  - The user should be redirected to the **payment details page** upon clicking **"Go to payment."**

---

### **Acceptance Criteria**:
1. The test checkout page is accessible from the homepage.
2. The currency and amount are correctly entered and reflected in the form.
3. The SDK preview renders with the appropriate fields.
4. Payment details are correctly submitted, and the payment is processed successfully.
5. The user can view the payment details page after successful payment.

---

This structured format ensures that all steps, test data, and expected outcomes are clearly defined for testing the payment process.

**Comment by Ankesh2004** [comment]
Hi , I would like to work on this issue. Please assign it to me.

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7, I would like to work on this issue as this is the prerequisite for other issues.

As ankesh has also commented on verification of time range in payment operations page issue already, can I have this one?

**Comment by gorakhnathy7** [comment]
Sure @s-vamshi assigning this issue to you!

Hey @Ankesh2004 As i see you have commented on multiple issues, but we won't be able to assign all at once.
let me know if you want to work on any new issues.

Thanks!

**Comment by gorakhnathy7** [comment]
Hey @s-vamshi 
Please note that for this issue, submit a PR on https://github.com/juspay/hyperswitch-control-center, and link to the issue.

**Comment by s-vamshi** [comment]
hey @JeevaRamu0104 @gorakhnathy7 
i am trying to create a test payment using the try it out button on the home page by spinning up hyperswitch-control-center and hyperswitch server locally,
when i click on show preview button the sdk preview is breaking.
can someone guide me to fix this issue?
![image](https://github.com/user-attachments/assets/19169700-b06b-4d26-904c-5f00d0427aec)

**Comment by JeevaRamu0104** [comment]
Hi @s-vamshi you need to configure the sdk url in the config file or set it has env.You also need to run the sdk locally
export default__endpoints__sdk_url="http://localhost:9050";

**Comment by s-vamshi** [comment]
Hey if i am not wrong just setting the url in [https://github.com/juspay/hyperswitch-control-center/blob/main/config%2Fconfig.toml#L7](config.toml) right?

**Comment by JeevaRamu0104** [comment]
yes @s-vamshi

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7,
Can i fill the form with the following issue also?
https://github.com/juspay/hyperswitch/issues/6125#issue-2551184783

**Comment by gorakhnathy7** [comment]
Hey @s-vamshi if you wish to raise more PRs, feel free to wait till all the PRs are merged.
