### ISSUE TITLE
[CYPRESS]: Create a dummy connector.

### ISSUE THREAD

**Issue by JeevaRamu0104** [juspay/hyperswitch#6125]
---

### **Title**: Verify Creation of Dummy Connector (Stripe Dummy)

---

### **Description**:

This task involves testing the process of creating a dummy payment connector through the "Payment Processors" page. It covers the entire flow from selecting a dummy processor to setting up payment methods and ensuring that the connector is successfully created and listed under connected processors.

---

### **Test Case**: Verify Creation of Dummy Connector (Stripe Dummy)

- **Pre-requisites**: None
- **Steps**:
  1. From the side menu, click on **"Connectors."**
  2. From the dropdown, click on **"Payment Processors."**
  3. Verify the user is redirected to the **"Payment Processors"** page.
  4. Click on the **"Connect Now"** button below the **"No Test Credentials? Connect a Dummy Processor"** message.
  5. A **"Connect a Dummy Processor"** popup should appear with four dummy connectors.
  6. Click on **"Connect"** under **"Stripe Dummy."**
  7. Verify the user is redirected to the **"Connector Credentials"** page.
  8. Enter the **"API key"** and **"Connector label"** and click on **"Connect and Proceed."**
  9. Verify the user is redirected to the **"Payment Methods"** page.
  10. Select the required payment methods and click on **"Proceed."**
  11. Verify the user is redirected to the **"Summary"** page with the message **"Connector Created Successfully!"**
  12. Click on **"Done."**
  13. Verify the user is redirected back to the **"Payment Processors"** page, and the **"Stripe Dummy"** connector should be present under the **"Connected Processors"** table.
- **Test Data**: 
  - API Key: `dummy_api_key`
  - Connector Label: **"Stripe Dummy"**
  - Payment Methods: Selected methods based on requirements.
- **Expected Results**:
  - The user is successfully redirected to the **"Payment Processors"** page after clicking the **"Connectors"** menu item.
  - The **"Connect a Dummy Processor"** popup should appear with four dummy connector options.
  - Upon clicking **"Connect"** under **"Stripe Dummy,"** the user should be redirected to the credentials page.
  - After entering the API key and connector label, the user should be able to proceed to the payment methods page and then to the summary page with the **"Connector Created Successfully!"** message.
  - Clicking **"Done"** should redirect the user back to the **"Payment Processors"** page, where **"Stripe Dummy"** is listed in the **"Connected Processors"** table.

---

### **Acceptance Criteria**:
1. The user can successfully navigate to the **"Payment Processors"** page.
2. The **"Connect a Dummy Processor"** popup appears with four options.
3. The **"Stripe Dummy"** connector can be selected, and the user can input credentials.
4. The process completes with the correct payment methods and a success message.
5. The **"Stripe Dummy"** connector appears in the **"Connected Processors"** table after the connector is created.

---
This structured approach ensures that all steps and expected outcomes for creating the dummy connector are clearly documented and ready for testing.

- For this issue, please submit a PR on juspay/hyperswitch-control-center repo, and link it to the issue.

**Comment by s-vamshi** [comment]
hey @gorakhnathy7 @JeevaRamu0104, i see few issues are dependent on this issue, I would like to work on this. Can you please assign it to me?

**Comment by gorakhnathy7** [comment]
Hey @s-vamshi assigned the issue to you!

**Comment by s-vamshi** [comment]
hey @gorakhnathy7, i have raised the pr, and this is my first pr to the repo, I would greatly appreciate it if you could review it in your free time and guide me in case I’m not following any of the project's conventions or if there are any improvements I can make.

**Comment by gorakhnathy7** [comment]
Sure @s-vamshi Will get it checked.
Thanks for participating.

**Comment by gorakhnathy7** [comment]
Hey @shreyT19 @pixincreate Slight correction here, As this issue corresponds to the @juspay/hyperswitch-control-center repo, Can we please raise the PR on that repo, and link it to the issue.

Updated the issue description as well. Thanks and apologies for inconvenience!

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7 , I have raised the pr to juspay/hyperswitch-control-center repo only!
