### ISSUE TITLE
[CYPRESS]: Verify Time Range Filters in "Payment operations" page.

### ISSUE THREAD

**Issue by prajwalnl0** [juspay/hyperswitch#6129]
---

### **Title**: Verify Time Range Filters in "Payment operations" page.

---

### **Description**:

This task is to write and execute automated test cases for various UI elements and functionalities on the "Payment Operations" page. The tests should validate that key UI elements are present and that core functionalities operate as expected.

### **Objective**:

Ensure that the "Payment Operations" page displays all key elements and that interactions like searching, filtering, and report generation work as intended. The task will include multiple test cases covering these areas.

### **Pre-requisites:**

[Create a dummy connector](https://github.com/juspay/hyperswitch/issues/6125)
[Use the SDK to process a payment](https://github.com/juspay/hyperswitch/issues/6124)

---

#### **Test Case 1: Verify Time Range Filters**

- **Pre-requisites**: Make a payment.
- **Steps**:
  1. Login to the application.
  2. Navigate to the "Payment Operations" page.
  3. Verify the default time range is "Last 30 Days."
  4. Click on the time range dropdown and select various options: "Last 30 Mins," "Last 1 Hour," "Last 2 Hours," etc.
- **Expected Results**:
  - For each selected time range, verify the payments are displayed accordingly.
  - "Customize columns" button visibility should be checked based on the presence of payments.

#### **Test Case 2: Verify "Custom Range" in Time Range Filters**

- **Pre-requisites**: Make a payment.
- **Steps**:
  1. Login to the application.
  2. Navigate to the "Payment Operations" page.
  3. Select "Custom Range" in the time range dropdown.
  4. Select a custom date range and click "Apply."
- **Expected Results**:
  - Payments within the selected range should be displayed.
  - The selected time range should be displayed when the dropdown is minimized.

---

### **Acceptance Criteria**:

1. All test cases should pass with the expected results.
2. Each test case must verify the required functionality or UI element.
3. The tests should be included in the regression suite and executed in the CI/CD pipeline.

---

### **Submission Process**:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).
- For this issue, please submit a PR on juspay/hyperswitch-control-center repo, and link it to the issue.

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

---

**Comment by s-vamshi** [comment]
@prajwalnl0 @gorakhnathy7 I would like to work on this. Can you assign it to me?

**Comment by gorakhnathy7** [comment]
@sure @s-vamshi , i'll assign it to you!

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @gorakhnathy7

**Comment by Akshayp02** [comment]
Hello @gorakhnathy7 ,

I would like to contribute to this issue. Could you please assign it to me.

**Comment by gorakhnathy7** [comment]
Hey @Akshayp02 Assigning this issue to you!

Hey @Ankesh2004 Kindly request assignment for one issue at a time.
You can ask for the next issue to be assigned, once you have completed the earlier assigned one.

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7 can I work on this issue? Can you please assign this to me?

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7 can I work on this issue?

**Comment by gorakhnathy7** [comment]
Hey @Akshayp02,

Kindly let us know, if you're still working on the issue? Else, we can assign it to some one else.

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7, just following up since it’s been a day with no response from @Akshayp02. I’d love to work on this issue if it's available!

**Comment by gorakhnathy7** [comment]
Sure @s-vamshi , Assigning this to you!

**Comment by gorakhnathy7** [comment]
Hey @s-vamshi 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.

**Comment by gorakhnathy7** [comment]
Hey For the Hyperswitch any PR raised by today EOD, and merged by 6th Nov will be considered.
