### ISSUE TITLE
[CYPRESS]: Verify Search in "Payment operations" page.

### ISSUE THREAD

**Issue by prajwalnl0** [juspay/hyperswitch#6130]
---

### **Title**: Verify Search in "Payment operations" page.

---

### **Description**:

This task is to write and execute automated test cases for various UI elements and functionalities on the "Payment Operations" page. The tests should validate that key UI elements are present and that core functionalities operate as expected.

### **Objective**:

Ensure that the "Payment Operations" page displays all key elements and that interactions like searching, filtering, and report generation work as intended. The task will include multiple test cases covering these areas.

### **Pre-requisites:**

[Create a dummy connector](https://github.com/juspay/hyperswitch/issues/6125)
[Use the SDK to process a payment](https://github.com/juspay/hyperswitch/issues/6124)

---

#### **Test Case 1: Search for Payment Using Existing Payment ID**

- **Pre-requisites**: Make a payment.
- **Steps**:
  1. Login to the application.
  2. Navigate to the "Payment Operations" page.
  3. Enter an existing payment ID into the search bar.
- **Test Data**: {{payment_id}}
- **Expected Results**:
  - Payments table should contain one row with valid payment details.

#### **Test Case 2: Search for Payment Using Invalid Payment ID**

- **Pre-requisites**: User is logged in.
- **Steps**:
  1. Navigate to the "Payment Operations" page.
  2. Enter an invalid payment ID or string into the search bar.
- **Test Data**: "abacd," "something," "createdAt"
- **Expected Results**:
  - "There are no payments as of now" text should be displayed.
  - "Customize columns" button should not be present.

---

### **Acceptance Criteria**:

1. All test cases should pass with the expected results.
2. Each test case must verify the required functionality or UI element.
3. The tests should be included in the regression suite and executed in the CI/CD pipeline.

---

### **Submission Process**:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).
- For this issue, please submit a PR on juspay/hyperswitch-control-center repo, and link it to the issue.

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

---

**Comment by nik132-eng** [comment]
hey, can I work on this issue for hacktoberfest?

**Comment by gorakhnathy7** [comment]
Hey @nik132-eng 
Are you still working on this?

Also, Please make sure to review the Submission process Steps before raising PR.

**Comment by nik132-eng** [comment]
Hey sorry for the delay but because of office work I am not able to give time in week days. If anyone wants to pick this one please go ahead.

**Comment by gorakhnathy7** [comment]
Hey @nik132-eng 
As we haven't got any other request about this issue, Would you like to continue, or should i unassign it?

**Comment by nik132-eng** [comment]
I can check this issue on sunday. If anyone is up for this issue please assign them although i will check in weekends

**Comment by gorakhnathy7** [comment]
Hey @nik132-eng 


Kindly let us know, if you're still working on the issue? If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7 as i see no progress, can i work on this issue?

**Comment by gorakhnathy7** [comment]
Sure @s-vamshi Assigning this to you!
