### ISSUE TITLE
[REFACTOR]: [OPAYO] Add amount conversion framework to Opayo

### ISSUE THREAD

**Issue by ImSagnik007** [juspay/hyperswitch#6135]
### :memo: Feature Description

Currently, amounts are represented as `i64` values throughout the application. We want to introduce a `Unit` struct that explicitly states the denomination. A new type, `MinorUnit`, has been added to standardize the flow of amounts across the application. This type will now be used by all the connector flows.

Rather than handling conversions in each connector, we will centralize the conversion logic in one place within the core of the application.

### :hammer: Possible Implementation

- For each connector, we need to create an amount conversion function. Connectors will specify the format they require, and the core framework will handle the conversion accordingly.
- Connectors should invoke the `convert` function to receive the amount in their required format.
- Refer to the [connector documentation](https://docs.recurly.com/docs/opayo) to determine the required amount format for each connector.
- You can refer [this PR](https://github.com/juspay/hyperswitch/pull/4825) for more context.

🔖 Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/` , `crates/router/src/types/api.rs` , `crates/router/tests/connectors/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [ ] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [ ] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by priyavratamohan** [comment]
Hi @ImSagnik007! 
I'd like to work on this issue under Hacktoberfest '24. Can you please assign this to me with the required labels?
Thanks!

**Comment by gorakhnathy7** [comment]
Hey @priyavratamohan  ,

Quick check-in on the status of this issue. If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by priyavratamohan** [comment]
Hi @gorakhnathy7,

I had been busy with my College Placement activities, and hence, wasn't very active in working on my current issues at the moment.
Now that I'm free, I've joined the community already and will be working on getting this issue sorted asap.

Thanks for your concern!

**Comment by priyavratamohan** [comment]
@gorakhnathy7 Sorry for the delay, I'll finish it off by Sunday. If not, I'll unassign myself.

**Comment by AnishKacham** [comment]
Can take this up in case assignee is busy 😅

**Comment by gorakhnathy7** [comment]
Hey @priyavratamohan Are you still working on this?

**Comment by priyavratamohan** [comment]
I'll unassign myself from this, sorry for the issues I may have caused. I'll pick up an easier issue for me to start with.

**Comment by gauravghodinde** [comment]
hey @gorakhnathy7  as no one is assigned this issue currently, can you assign it to me?

**Comment by gorakhnathy7** [comment]
Hey @gauravghodinde Assigned the Issue to you, Happy Coding!

**Comment by gorakhnathy7** [comment]
Hey @gauravghodinde,
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all your PRs are merged.
