### ISSUE TITLE
[BUG] CI is failing due to wrong spelling

### ISSUE THREAD

**Issue by vil02** [juspay/hyperswitch#6195]
### Bug Description

I noticed that the CI-push is reporting this spelling errors:
- https://github.com/juspay/hyperswitch/actions/runs/11135615914/job/30945965216,
- https://github.com/juspay/hyperswitch/actions/runs/11123807888/job/30908038374,
- https://github.com/juspay/hyperswitch/actions/runs/11123440265/job/30906897289,
- https://github.com/juspay/hyperswitch/actions/runs/11123158701/job/30906005608.

#6194 attempts to fix the spelling.

### Expected Behavior

The CI should pass.

### Actual Behavior

It actually... fails.

### Steps To Reproduce

Not relevant.

### Context For The Bug

I want the CI pass in my PR #6191.

### Environment

Not related.

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by gorakhnathy7** [comment]
Thanks @vil02 For the contribution, this will be reviewed soon

**Comment by SanchithHegde** [comment]
Addressed in #6164.
