### ISSUE TITLE
[BUG] Docker Compose dev environment fails to setup hyperswitch-server

### ISSUE THREAD

**Issue by akhildevelops** [juspay/hyperswitch#6216]
### Bug Description

`hyperswitch-hyperswitch-server-1` container stops abruptly without spinning up the server.  Container can't find `protobuf-compiler` debian package and fails. Below are the logs of the container
```shell
➜  hyperswitch git:(main) docker logs hyperswitch-hyperswitch-server-1            

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package protobuf-compiler
```

Protobuf compiler mentioned here https://github.com/juspay/hyperswitch/blob/a3c2694943a985d27b5bc8b0371884d17a6ca34d/docker-compose-development.yml#L64

### Expected Behavior

`hyperswitch-hyperswitch-server-1` should run

### Actual Behavior

Container simply exits
```shell
➜  hyperswitch git:(main) docker ps -a
CONTAINER ID   IMAGE                                           COMMAND                  CREATED         STATUS                          PORTS                                                 NAMES
3569baada69f   rust:latest                                     "apt-get install -y …"   3 minutes ago   Exited (100) 3 minutes ago                                                            hyperswitch-hyperswitch-server-1

```

### Steps To Reproduce

1. Clone the repo on a new machine
2. Run `docker compose --file docker-compose-development.yml up -d`

### Environment

Are you using hyperswitch hosted version? No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution: Debian 12

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by gorakhnathy7** [comment]
Hey @akhildevelops 

Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
