### ISSUE TITLE
[FEAT] add support for Hashicorp Vault Engine

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#6226]
**Description:**

Cripta is a service which creates keys and maintains it (includes key rotation etc.) individually for different Merchants and Users.

Currently it uses the AWS KMS as the Master Key (Key Encryption Key) for encrypting and decrypting Data Encryption Keys, But this is limited to AWS, To support deployment of Keymanager in multiple clouds, We need to support more Engines.

**Getting started:**

Go through the [README](https://github.com/juspay/hyperswitch-encryption-service/blob/main/README.md) for guidelines on the structure and functionality.

**Possible implementation:**
1. Go through the Hashcorp Vault Engine Implementation [here](https://github.com/juspay/hyperswitch/tree/main/crates/external_services/src/hashicorp_vault).
2. Add the Implementation [here](https://github.com/juspay/hyperswitch-encryption-service/tree/main/src/crypto)
3. Create a feature for Hashicorp Vault.
4. Add Initializer for Hashicorp Vault [here](https://github.com/juspay/hyperswitch-encryption-service/blob/main/src/config.rs#L174).

**Reference:**

- [Hyperswitch Keymanager](https://docs.hyperswitch.io/security-and-compliance/security#key-manager-service-encryption)

- Language: Rust
- Difficulty: Medium

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).
- For this issue, please raise a PR on the https://github.com/juspay/hyperswitch-encryption-service repo, and link the issue.

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by ssenthilnathan3** [comment]
hi @dracarys18, i am interested in working on this issue. can you assign it to me?

**Comment by jrowlandtexas** [comment]
This would be great addition, thank you!

**Comment by akhildevelops** [comment]
Find PR for this feature request: https://github.com/juspay/hyperswitch-encryption-service/pull/29

P.S: I know it has been assigned but still I wanted to work on this feature request to understand inner workings of Secrets Engines like Vault and https://github.com/juspay/hyperswitch-encryption-service. @dracarys18, feel free to disband my PR if @ssenthilnathan3 comes with his contribution.

**Comment by dracarys18** [comment]
Hey @ssenthilnathan3 are you working on the issue?

**Comment by ssenthilnathan3** [comment]
I was...but @akhildevelops approach seems more productive and neat.

Please accept his PR @dracarys18
