### ISSUE TITLE
[FEAT] Add benchmarking for encryption/decryption

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#6228]
**Description:**

Cripta is a service which creates keys and maintains it (includes key rotation etc.) individually for different Merchants and Users.

We need to add a tool which benchmarks the internal encryption/decryption implementation, And any changes to the application should not cause any Perf regressions.

**Possible implementation:**

- Add `benches` folder for different benchmarking scenarios
- Use [criterion.rs](https://github.com/bheisler/criterion.rs) for benchmarking
- Call [this](https://github.com/juspay/hyperswitch-encryption-service/blob/main/src/core/crypto/crux.rs#L29) fuction in criterion to benchmark

### Submission Process:
- Ask the maintainers for assignment of the issue, you can request for assignment by commenting on the issue itself.
- Once assigned, submit a pull request (PR).
- Maintainers will review and provide feedback, if any. 
- Maintainers can unassign issues due to inactivity, [read more here](https://github.com/juspay/hyperswitch/wiki/Hacktoberfest-Contribution-Rules).
- For this issue, please raise a PR on the https://github.com/juspay/hyperswitch-encryption-service repo, and link the issue.

Refer [here](https://github.com/juspay/hyperswitch/blob/main/docs/TERMS_OF_CONTEST.md) for Terms and conditions for the contest.

**Comment by khaile** [comment]
Hello! Could you please assign me this issue?

**Comment by dracarys18** [comment]
Assigned the issue to you @khaile

**Comment by gorakhnathy7** [comment]
Hey @khaile 


Kindly let us know, if you're still working on the issue? If you have any questions or need assistance, feel free to reach out in the [community](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-2jqxmpsbm-WXUENx022HjNEy~Ark7Orw).

**Comment by Anupam-1208** [comment]
Hi can you assign me this issue? @dracarys18
