### ISSUE TITLE
[REFACTOR]: (merchant_account_v2) move `organization_id` from request body to `headers`

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#6237]
When creating the merchant account, the request body is 
```json
{
    "merchant_name": "cloth_seller",
    "organization_id": "org_tdhdTbv3z85XtxXGgVHS"
}
```

Here `organization_id` is the hierarchy_id / lineage id. This should be moved to a header called `X-Organization-Id`. Necessary changes have to be made in the handlers wherever this is affected. In this case only merchant account create would be affected.

**Comment by shivam-jainn** [comment]
Can i work on this?

**Comment by gorakhnathy7** [comment]
Hey @shivam-jainn, 
Thanks for your interest.
But, This has already been worked upon by a team member, You can pick an issue from this [pool](https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee).
