### ISSUE TITLE
[BUG] Broken links to Running additional services

### ISSUE THREAD

**Issue by vil02** [juspay/hyperswitch#6242]
### Bug Description

These lines:

- https://github.com/juspay/hyperswitch/blob/b7139483bb4735b7dfaf7e659ab33a16a90af1db/README.md?plain=1#L137,
- https://github.com/juspay/hyperswitch/blob/b7139483bb4735b7dfaf7e659ab33a16a90af1db/docs/try_local_system.md?plain=1#L59,
- https://github.com/juspay/hyperswitch/blob/b7139483bb4735b7dfaf7e659ab33a16a90af1db/docs/try_local_system.md?plain=1#L157,

Contain links to non existing section.

### Expected Behavior

I should be taken to the intended part of the documentation.

### Actual Behavior

Takes me to the top of the `try_local_system.md` page.

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Go to mentioned the lines mentioned above
2. Click on the link

### Context For The Bug

The proper target should be this:
https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#running-additional-services

### Environment

Not relevant.

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by gorakhnathy7** [comment]
Hey @vil02 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
