### ISSUE TITLE
[BUG] Do not use backticks in shell files

### ISSUE THREAD

**Issue by vil02** [juspay/hyperswitch#6271]
### Bug Description

These scripts:
- [`INSTALL_dependencies.sh`](https://github.com/juspay/hyperswitch/tree/535f2f12f825be384a17fba8628d8517027bb6c6/INSTALL_dependencies.sh),
- [`hyperswitch_aws_setup.sh`](https://github.com/juspay/hyperswitch/tree/535f2f12f825be384a17fba8628d8517027bb6c6/aws/hyperswitch_aws_setup.sh),
- [`hyperswitch_cleanup_setup.sh`](https://github.com/juspay/hyperswitch/tree/535f2f12f825be384a17fba8628d8517027bb6c6/aws/hyperswitch_cleanup_setup.sh),
- [`add_connector.sh`](https://github.com/juspay/hyperswitch/tree/535f2f12f825be384a17fba8628d8517027bb6c6/scripts/add_connector.sh),

use the _deprecated_ backticks notation (cf. [SC2006](https://www.shellcheck.net/wiki/SC2006)).

### Expected Behavior

These scripts should follow the recommended guidelines.

### Actual Behavior

Use legacy notation, which might cause some maintenance issues.

### Steps To Reproduce

Not relevant.

### Environment

Not relevant.

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by Sidharth-Singh10** [comment]
hey, I would like to work on this.

**Comment by shinigami-777** [comment]
@gorakhnathy7 I have opened a PR regarding this. Can you please review it.

**Comment by gorakhnathy7** [comment]
Hey @shinigami-777 This was assigned to @Sidharth-Singh10 and he has also submitted the PR.
Though we value time and effort you guys have given to this, But to maintain fairness we will move ahead with @Sidharth-Singh10's PR.
Kindly pick an un-assigned issue from [here](https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee).

**Comment by ravi-hash** [comment]
I would like to work on this. Can you assign it to me?

**Comment by ravi-hash** [comment]
I would like to work on this. Can you assign it to me?

**Comment by gorakhnathy7** [comment]
Hey @ravi-hash There is another PR already under review.
