### ISSUE TITLE
[BUG] Various errors in `rust_locker_open_api_spec.yml`

### ISSUE THREAD

**Issue by vil02** [juspay/hyperswitch#6321]
### Bug Description

The two identical files [`api-reference/rust_locker_open_api_spec.yml`](https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference/rust_locker_open_api_spec.yml) and [`api-reference-v2/rust_locker_open_api_spec.yml`](https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference-v2/rust_locker_open_api_spec.yml) contain some mistakes and errors.

### Expected Behavior

The documentation should be clear.

### Actual Behavior

The documentation contains some errors.

### Steps To Reproduce

Not relevant.

### Context For The Bug

Some examples:
https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference/rust_locker_open_api_spec.yml#L5
https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference/rust_locker_open_api_spec.yml#L12
https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference/rust_locker_open_api_spec.yml#L14
https://github.com/juspay/hyperswitch/blob/d06d19fc96e1a74d20e2fe3613f86d541947e0ae/api-reference/rust_locker_open_api_spec.yml#L42

### Environment

Not relevant.

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by vil02** [comment]
@Yashwanth-Chandrakumar: just to avoid any confusion, when I was creating this issue, I made a note that _I am willing to submit a PR_ and the pull-request is already there: #6322.

**Comment by ravi-hash** [comment]
I would like to work on this. Can you assign it to me?

**Comment by vil02** [comment]
@ravi-hash: please note that this is already done: #6322 waits for a review. Moreover, while creating this issue I selected "Yes, I am willing to submit a PR!".

**Comment by gorakhnathy7** [comment]
Hey @vil02 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.
