### ISSUE TITLE
[BUG] FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by Shark-Firewall** [juspay/hyperswitch#6577]
### Bug Description

Whenever hyperswitch-pg-1 sever running in docker-compose, it though an error " role "root" does not exist"

### Expected Behavior

Error should not come.

### Actual Behavior

![Screenshot from 2024-11-14 19-27-00](https://github.com/user-attachments/assets/fc92e35a-8b2f-4023-b155-73e28ae8cf98)

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. Open Docker Desktop
2. Run hyperswitch-pg-1 server
3. After some time, you will see the error

### Context For The Bug

While setting hyperswitch on my local machine, I came across this error.

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution: Ubuntu 24.04
2. Rust version (output of `rustc --version`): ``: rustc 1.82.0 (f6e511eec 2024-10-15)
3. App version (output of `cargo r --features vergen -- --version`): `` NA

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by SanchithHegde** [comment]
I think this is arising from the `healthcheck` command we've defined for the Postgres container. Although this should not affect the Docker Compose setup itself: everything should work as expected even if this message is being logged.

Could you try updating [this line](https://github.com/juspay/hyperswitch/blob/8cc5d3db9afb120b00115c6714be2e362951cc94/docker-compose.yml#L24) to the below line and try?

```yaml
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
```

**Comment by Shark-Firewall** [comment]
@SanchithHegde  After updating what you recommended, now it's not above error is coming in logs

**Comment by SanchithHegde** [comment]
@Shark-Firewall Cool, feel free to open a PR for the same. If you're opening the PR, please ensure you make the same change in the `docker-compose-development.yml` file as well.

**Comment by Shark-Firewall** [comment]
Hi @SanchithHegde 
I have raised the PR https://github.com/juspay/hyperswitch/pull/6582
Could you please review the PR?
