### ISSUE TITLE
[BUG] Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens.

### ISSUE THREAD

**Issue by Kamal-Moha** [juspay/hyperswitch#6866]
### Bug Description

I have been following the [docs](https://docs.hyperswitch.io/explore-hyperswitch/payment-flows-and-management/quickstart/connectors/test-a-payment-with-connector) to try a test payment in hyperswitch hosted with stripe connected. 

I have successfully connected stripe to hyperswitch, and then attempted to make a test payment with the test cards. I get the error "Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using".

I have implemented some suggestions from this similar issue #1723 
Tried to do the suggestion by @Abhicodes-crypto of enabling the "Handling of card information" in stripe settings;
![image](https://github.com/user-attachments/assets/9f40c242-9522-4563-9022-d82a88a895c1)

But as you can see from above, stripe doesn't let me enable that.

Now I would like to try the suggestion by stripe of using test tokens. But know I don't know how to pass the test tokens in hyperswitch when making the test payment. Please help. Thanks!

### Expected Behavior

My expectation was to have a successful test payment made in hyperswitch

### Actual Behavior

Test payment fails as seen here
![image](https://github.com/user-attachments/assets/6f84899e-3a89-4ba7-ad47-6bae61d032fe)

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

### Environment

Are you using hyperswitch hosted version? Yes
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by Vishvendra-Shukla** [comment]
Hello @Kamal-Moha, I was having the same issue until i reached their(Hyperswitch) documentation support for payments using stripe. They have explicitly mentioned `Enable handling raw card data for your Stripe account by sending a request to the stripe support`. Please review their [documentation](https://docs.hyperswitch.io/explore-hyperswitch/payment-flows-and-management/quickstart/connectors/available-connectors/stripe). I hope this helps.

**Comment by Kamal-Moha** [comment]
Thanks @Vishvendra-Shukla, I have reached out to stripe support and they have enabled the functionality of directly accepting card info in my account. Now I'm able to accept card payments through stripe in hyperswitch

**Comment by SanchithHegde** [comment]
@Vishvendra-Shukla Thanks for pitching in and responding here! Much appreciated.

Closing this as resolved.
