### ISSUE TITLE
[BUG] local deployment cannot be accessed via web login

### ISSUE THREAD

**Issue by knysfh** [juspay/hyperswitch#6915]
### Bug Description

The latest program installed via Docker cannot log in after registration. The web console shows a 401 error.

### Expected Behavior

The expected result is that the account should be able to log in normally.

### Actual Behavior

Unable to log in to the account.

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1. clone the latest code and install the related files using `docker compose`
```shell
git clone --depth 1 --branch latest https://github.com/juspay/hyperswitch
cd hyperswitch
docker compose --profile scheduler --profile olap --profile monitoring up -d
```
2. check the health port to ensure the program is running normally
```shell
❯ curl --head --request GET 'http://localhost:8080/health'
HTTP/1.1 200 OK
Content-Length: 14
Connection: keep-alive
Date: Sun, 22 Dec 2024 11:06:42 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Strict-Transport-Security: max-age=31536000
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Via: HyperSwitch
X-Hyperswitch-Version: v1.112.1-dirty
X-Request-Id: 0193ee0c-4919-7382-8c8f-798f741597c1

❯ curl http://localhost:8080/health/ready
{"database":true,"redis":true,"analytics":true,"opensearch":true,"outgoing_request":true,"grpc_health_check":{}}
```
3. open the [dashboard](http://localhost:9000) to register an account and log in

![image](https://github.com/user-attachments/assets/5606c5c4-2250-4d89-9d3e-79f73ec3cb61)

### Environment

If not (or if building/running locally), please provide the following details:
1. Linux distribution:
```shell
❯ neofetch
                   -`                    aka@laptop 
                  .o+`                   ----------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: ZhongYan U4 Version 1.0 
               `+oooooo:                 Kernel: 6.12.4-arch1-1 
               -+oooooo+:                Uptime: 6 hours, 9 mins 
             `/:-:++oooo+:               Packages: 1570 (pacman) 
            `/++++/+++++++:              Shell: fish 3.7.1 
           `/++++++++++++++:             Resolution: 3840x2160 
          `/+++ooooooooooooo/`           WM: sway 
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: foot 
      :osssssss/        osssso+++.       CPU: AMD Ryzen 7 7735HS with Radeon Graphics (16) @ 4.829GHz 
     /ossssssss/        +ssssooo/-       GPU: AMD ATI Radeon 680M 
   `/ossssso+/:-        -:/+osssso+-     Memory: 20382MiB / 27797MiB 
  `+sso+:-`                 `.-/+oso:    Disk (/): 586G / 934G (63%) 
 `++:.                           `-/+/
 .`                                 `/                           
                                                                 
```
2. Rust version (output of `rustc --version`): `docker rust:latest`
3. App version (output of `cargo r --features vergen -- --version`): `docker rust:latest`

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by apoorvdixit88** [comment]
Hey @knysfh 
It looks like the issue is related to the cookie feature that was recently enabled. To resolve it temporarily, please open `config/docker_compose.toml` and set `force_cookies = false` (which is currently set to `true`). After making this change, restart the hyperswitch_server_1 container. This should help until the issue is fully fixed.

**Comment by knysfh** [comment]
@apoorvdixit88 Thank you, this solved my problem.
