### ISSUE TITLE
[FEATURE]: add support for three letter and numeric country codes

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#804]
### Feature Description

We are currently using two_letter country codes internally since majority of connectors accept only two_letter codes, there may arise a situation where some connector will accept only three_letter country codes or numeric codes. There is a complete list of the mapping https://www.nationsonline.org/oneworld/country_code_list.htm. 

### Possible Implementation

We can have an enum `Country` which will be the actual country name and then provide mapping to two_letter, three_letter codes and even numeric_codes. All the variants map to same enum `Country`. This can be achieved by implementing a custom serializer and deserializer as shown above.

```rust
#[derive(Clone, Copy, Debug)]
pub enum Country {
    Afghanistan,
    Albania,
    // ...
}

#[derive(Clone, Copy, Debug)]
pub enum Alpha2CountryCode {
    AF,
    AL,
    // ...
}

impl Country {
    // Note the `const`. Similar implementation for `to_alpha2(&self)`.
    pub const fn from_alpha2(code: Alpha2CountryCode) -> Self {
        match code {
            Alpha2CountryCode::AF => Self::Afghanistan,
            Alpha2CountryCode::AL => Self::Albania,
            // ...
        }
    }
}

mod custom_serde {
    use super::*;

    pub mod alpha2_country_code {
        use super::*;

        pub fn serialize<S>(code: &Country, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            // Serialize country as Alpha-2 code
            Err(serde::ser::Error::custom("not implemented"))
        }

        pub fn deserialize<'a, D>(deserializer: D) -> Result<Country, D::Error>
        where
            D: serde::Deserializer<'a>,
        {   
            // Deserialize Alpha-2 code from string, then convert to country enum
            Err(serde::de::Error::custom("not implemented"))
        }
    }
}

#[derive(serde::Deserialize, serde::Serialize)]
struct Address {
    #[serde(with = "custom_serde::alpha2_country_code")]
    country: Country,
}
```

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Narayanbhat166** [comment]
Hi @nachiketkanore. That's great! 
You can have a look at [common_enums/enums.rs](https://github.com/juspay/hyperswitch/blob/main/crates/common_enums/src/enums.rs) file where the country enum is defined. Using this enum in any of the request/response types would restrict us to use the two letter code. Allowing us to accept country in various formats as specified [here](https://www.nationsonline.org/oneworld/country_code_list.htm), would add flexibility to accept ( deserialize )  a country as an an [alpha_2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) ( two letter code ), and send ( serialize ) it as an [alpha_3 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) ( three letter code ) to any connector. 

One possible implementation would be to have the mapping/conversions for all the available variants. This would be 
- alpha2 -> alpha3
- alpha2 -> numeric
- ...

This would be hard to maintain 

Instead a better solution would be to have an internal enum which would have the full country name, and all the other variants provide a mapping to, and from this enum to all other variants. Let's take `United states` for example
`US` / `USA` / `840` --> `UnitedStates`

Once we have deserialized the country code into this common enum `UnitedStates`, the same mapping can be reversed to get any other variant.
`UnitedStates` --> `US` / `USA` / `840`.

This behaviour can be achieved by providing implementation for custom `serialization` and `deserialization` using [serde](https:://serde.rs)

**Comment by nachiketkanore** [comment]
Could you check whether this is the intended approach? 
Also, Serializing and Deserializing enums (with custom serde) still involve the use of strings.
So, is this still the viable approach for the task you are trying to solve?

Also, I am unable to understand the use of serializing and deserializing between all types. Since, after getting some country code format from the request (2char, 3char, or numeric), why can't we use it as it is, with just two-way mapping?
```rust
#[derive(Clone, Copy, Debug)]
pub enum CountryAlpha2 {
    IN,
    AU,
    NZ,
    SA,
}
#[derive(Clone, Copy, Debug)]
pub enum CountryAlpha3 {
    IND,
    AUS,
    NEZ,
    SAF,
}

#[derive(Clone, Copy, Debug)]
pub enum Country {
    Australia,
    NewZealand,
    India,
    SouthAfrica,
}

impl Country {
    pub const fn from_alpha2(code: CountryAlpha2) -> Self {
        match code {
            CountryAlpha2::IN => Self::India,
            CountryAlpha2::AU => Self::Australia,
            CountryAlpha2::NZ => Self::NewZealand,
            CountryAlpha2::SA => Self::SouthAfrica,
        }
    }
    pub const fn to_alpha2(&self) -> CountryAlpha2 {
        match self {
            Country::Australia => CountryAlpha2::AU,
            Country::NewZealand => CountryAlpha2::NZ,
            Country::India => CountryAlpha2::IN,
            Country::SouthAfrica => CountryAlpha2::SA,
        }
    }
}

mod custom_serde {
    use super::*;

    pub mod alpha2_country_code {
        use std::fmt;

        use serde::de::Visitor;

        use super::*;

        pub fn serialize<S>(code: &Country, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            // Serialize country as Alpha-2 code
            let alpha2_code = code.to_alpha2();

            match alpha2_code {
                CountryAlpha2::IN => serializer.serialize_unit_variant("CountryAlpha2", 0, "IN"),
                CountryAlpha2::AU => serializer.serialize_unit_variant("CountryAlpha2", 1, "AU"),
                CountryAlpha2::NZ => serializer.serialize_unit_variant("CountryAlpha2", 2, "NZ"),
                CountryAlpha2::SA => serializer.serialize_unit_variant("CountryAlpha2", 3, "SA"),
            }
        }

        struct FieldVisitor;

        impl<'de> Visitor<'de> for FieldVisitor {
            type Value = CountryAlpha2;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("CountryAlpha2 as a string")
            }
        }

        pub fn deserialize<'a, D>(deserializer: D) -> Result<Country, D::Error>
        where
            D: serde::Deserializer<'a>,
        {
            // Deserialize Alpha-2 code from string, then convert to country enum
            // Err(serde::de::Error::custom("not implemented"))
            let country_alpha2 = deserializer
                .deserialize_enum("CountryAlpha2", &["IN", "AU", "NZ", "SA"], FieldVisitor)
                .unwrap();
            Ok(Country::from_alpha2(country_alpha2))
        }
    }
}

#[derive(serde::Deserialize, serde::Serialize)]
struct Address {
    #[serde(with = "custom_serde::alpha2_country_code")]
    country: Country,
}

```

**Comment by Narayanbhat166** [comment]
This looks good! I think `serialize` and `deserialize` can be derived on the `CountryAlpha2` `CountryAlpha3` which would handle the serialization and deserialization and reduce the boilerplate code written. 

- The serialization would change to
```rust
code.to_alpha2().serialize(serializer)
```
- The deserialization to `CountryAlpha2` would change to
```rust
deserializer.deserialize_str(FieldVisitor).map(Country::from_alpha2)
```

The use case would be something like this. Let's say we have a connector (gateway) X, which expects the country code in `alpha2` format, and another connector Y which expects the country code in `alpha3` format. Using the same country type, we should be able to `deserialize` it to any variant by changing the serializer. This would be a pluggable module which changes the behaviour as required.

```rust
#[derive(serde::Serialize)]
struct XRequest {
    #[serde(with = "custom_serde::alpha2_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize)]
struct YRequest {
    #[serde(with = "custom_serde::alpha3_country_code")]
    pub country: Country,
}
```

**Comment by nachiketkanore** [comment]
> The serialization would change to
> ```code.to_alpha2().serialize(serializer)```

This doesn't work. Or am I doing something wrong?
Serialization of enums requires to specify all unit variants in string form.

**Comment by Narayanbhat166** [comment]
Can you post the error message here? You would need to add `Serialize` to the `CountryAlpha2` enum.
```rust
#[derive(Clone, Copy, Debug, serde::Serialize)]
pub enum CountryAlpha2 {
    IN,
    AU,
    NZ,
    SA,
}
```

**Comment by nachiketkanore** [comment]
```

error[E0599]: no method named `serialize` found for enum `enums::CountryAlpha2` in the current scope
   --> crates/common_enums/src/enums.rs:115:30
    |
42  | pub enum CountryAlpha2 {
    | ---------------------- method `serialize` not found for this enum
...
115 |             code.to_alpha2().serialize(serializer)
    |                              ^^^^^^^^^ method not found in `CountryAlpha2`
```

**Comment by Narayanbhat166** [comment]
> Can you post the error message here? You would need to add `Serialize` to the `CountryAlpha2` enum.
> 
> ```rust
> #[derive(Clone, Copy, Debug, serde::Serialize)]
> pub enum CountryAlpha2 {
>     IN,
>     AU,
>     NZ,
>     SA,
> }
> ```

This should solve the error.

**Comment by nachiketkanore** [comment]
Already added that, `serialize` method is not available. Full code https://paste.rs/DAA.rs

**Comment by Narayanbhat166** [comment]
I have added few tests
```rust
#[derive(serde::Serialize)]
struct Alpha2Request {
    #[serde(with = "custom_serde::alpha2_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize)]
struct Alpha3Request {
    #[serde(with = "custom_serde::alpha3_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize)]
struct NumericRequest {
    #[serde(with = "custom_serde::numeric_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestAlpha2 {
    #[serde(with = "custom_serde::alpha2_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestAlpha3 {
    #[serde(with = "custom_serde::alpha3_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestNumeric {
    #[serde(with = "custom_serde::numeric_country_code")]
    pub country: Country,
}

fn main() {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_serialize_alpha2() {
        let x_request = Alpha2Request {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&x_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"IN"}"#)
    }

    #[test]
    fn test_serialize_alpha3() {
        let y_request = Alpha3Request {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"IND"}"#)
    }

    #[test]
    fn test_serialize_numeric() {
        let y_request = NumericRequest {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"356"}"#)
    }

    #[test]
    fn test_deserialize_alpha2() {
        let request_str = r#"{"country":"IN"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        assert_eq!(request.country, Country::India)
    }

    #[test]
    fn test_deserialize_alpha3() {
        let request_str = r#"{"country":"IND"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha3>(request_str).unwrap();
        assert_eq!(request.country, Country::India)
    }

    #[test]
    fn test_deserialize_numeric() {
        let request_str = r#"{"country":"356"}"#;
        let request = serde_json::from_str::<HyperswitchRequestNumeric>(request_str).unwrap();
        assert_eq!(request.country, Country::India)
    }

    #[test]
    fn test_deserialize_and_serialize() {
        // Deserialize the country as alpha2 code
        // Serialize the country as alpha3 code
        let request_str = r#"{"country":"IN"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        let alpha3_request = Alpha3Request {
            country: request.country,
        };
        let response = serde_json::to_string::<Alpha3Request>(&alpha3_request).unwrap();
        assert_eq!(response, r#"{"country":"IND"}"#)
    }
}
```

**Comment by Narayanbhat166** [comment]
> Already added that, `serialize` method is not available. Full code https://paste.rs/DAA.rs

add this import at the top
```rust
use serde::Serialize;
```

**Comment by nachiketkanore** [comment]
Somehow, the deserialization is not working. It is not able to deserialize the enums. Could you  please take a look into this: https://paste.rs/WtR.rs

**Comment by Narayanbhat166** [comment]
The deserialization should have been
```rust
CountryAlpha2::deserialize(deserializer).map(Country::from_alpha2)
```

This should work

**Comment by nachiketkanore** [comment]
Thanks. It is working now!
Regarding the `enum CountryNumeric`, do you have any ideas on how to implement it? Since enum variants cannot be raw integers.

**Comment by SanchithHegde** [comment]
Maybe we could have `Country::from_numeric_code(u16)` and `Country::to_numeric_code() -> u16` which perform the mapping instead of using enums for country codes?
