### ISSUE TITLE
[FEATURE] separate payments_session from payments core

### ISSUE THREAD

**Issue by Narayanbhat166** [juspay/hyperswitch#888]
### Feature Description

In the current implementation, the [payments_session](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/core/payments/operations/payment_session.rs) is a part of [payments core](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/core/payments.rs) logic. This was done to reuse certain parts of code which would avoid redundancy, this would also be maintained along with the payments core. The major anamoly from the core logic would be that multiple connectors would be called in parallel.

### Possible Implementation

As we have come a long way in our journey of integrating the connectors / gateways, we have not come across any connector / gateway, where the session token generation ( required to initiate the sdk ) logic, is tied to a payment flow. It would be better to have this logic separated from the core logic. This would help us in
- Deploying it separately since this will have many reads 
- Flexibility to add changes without any breaking changes to the payments logic.
- No routing support is required.

This can be implemented as a separate function as which would perform the required functionalities. This can be build in a similar way to [payment_method_list](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/core/payment_methods/cards.rs#L784) api. Additional step would be to call the connector whenever necessary.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by shubhanshu-mani** [comment]
Hi I would like to pick this up , need some clarifications though

1. Is payment_session an API ? 
2. Do you just want to move the existing implementation to another module ? 
3. Is payment_session's implementation is based on payment flow and you want the impl to be independent of it ??

**Comment by Narayanbhat166** [comment]
Hi @shubhanshu-mani. Thanks for showing interest. To clarify your doubts
- Yes `payments_session` is an api endpoint currently. It can be followed from request till response from [here](https://github.com/juspay/hyperswitch/blob/8eac8cb3709ccab8819aa25c34b64b01a6d43750/crates/router/src/routes/app.rs#L90)
- The existing functionality should be decopuled from [payments_core](https://github.com/juspay/hyperswitch/blob/8eac8cb3709ccab8819aa25c34b64b01a6d43750/crates/router/src/core/payments.rs#L175). Yes it can be moved to a separate module. 
- It shares only few functionalities like getting `payment_intent` and `customer_information` ( haven't come across any conenctors asking for customer information as of now ) to name a few. Yes the implementation should be independent of payments flow.

I will be assigning this issue to you.

**Comment by shubhanshu-mani** [comment]
@Narayanbhat166 Hi! need some more clarification I am pretty new to this .
I can see that payment_session is implemented using traits like 
`GetTracker | UpdateTracker | ValidateRequest | Domain` I think you want the implementation to not use this and just be a simple function call like it is done in payment_method API . 

What I am not sure about is that if payment_session API needs logic from all these traits or not like does it needs to update tracker tables or just be a stateless API to get the session info from connectors and give it back to the client ?

Thanks

**Comment by Narayanbhat166** [comment]
Yes, this implementation may opt out of those trait functionalities. It can follow the same flow as `payment_methods_list`. 
This should be a stateless api, which can only read the trackers ( only `payment_attempt` and `payment_intent`, and address tables ). It should not update the trackers.

**Comment by SanchithHegde** [comment]
I'll unassign @shubhanshu-mani from this issue, it's open for other contributors to pick up.

**Comment by aazam-gh** [comment]
Hello can I work on this issue

**Comment by deepanshu-iiitu** [comment]
Hey @aazam-gh , sure! I've assigned this to you. 

In case you have any queries, you can ask them on this issue thread, or on our [discord server](https://discord.com/invite/wJZ7DVW8mm), or on [slack](https://join.slack.com/t/hyperswitch-io/shared_invite/zt-1k6cz4lee-SAJzhz6bjmpp4jZCDOtOIg) whichever you are comfortable with

**Comment by aazam-gh** [comment]
@deepanshu-iiitu I was setting up the local development but I keep running into errors when running `cargo build`
My OS is Ubuntu 22.04 Jammy

![image](https://github.com/juspay/hyperswitch/assets/59562284/7674eed7-5362-4a2e-9637-0a212a55d309)

**Comment by SanchithHegde** [comment]
@aazam-gh Are you using the nightly toolchain to compile the codebase?

**Comment by aazam-gh** [comment]
@SanchithHegde I don't think so. I followed the instructions here https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md

**Comment by SanchithHegde** [comment]
@aazam-gh Could you please confirm the toolchain being used by running `cargo --version`?

**Comment by aazam-gh** [comment]
@SanchithHegde  I am using `cargo 1.75.0-nightly (d2f6a0485 2023-10-20)`

**Comment by aazam-gh** [comment]
@SanchithHegde  I did try running the command to set to the stable version. However the compilation goes smoothly until a few crates are left and it encounters this error

`error: could not compile `router` (lib)`

**Comment by SanchithHegde** [comment]
@aazam-gh I can't help you with just that information, will need the last few lines of the error message. We can move this discussion about setup/compilation errors to Discord, since this isn't exactly related to the issue.

**Comment by aazam-gh** [comment]
@SanchithHegde sure, I'll start a thread under the oss-contrib channel

**Comment by Narayanbhat166** [comment]
Will be closing this issue since things have changed and we want to keep this the way it is currently.
