### ISSUE TITLE
[ENHANCEMENT] Add connector_label field in error type

### ISSUE THREAD

**Issue by Abhicodes-crypto** [juspay/hyperswitch#899]
### Feature Description

A `DuplicateMerchantConnectorAccount` will occur when inserting a row in the `merchant_connector_account` table if there is a row that already exists with the same merchant_id and connector_label. The connector_label is created by Hyperswitch internally hence it is necessary to send back the connector_label is the error response so that the user has an idea of what the connector_label is.  

### Possible Implementation

add a field connector_label in the error message of `DuplicateMerchantConnectorAccount`.

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by eliKalter** [comment]
I am interested in collaborating with someone on their project so I can learn the language while they get a  sidekick.
Let me Know if this is something that could work for you.
I Would need you to explain and guide me through my first steps in the language (I already started learning) and set the standard for me in code reviews but after a short while I'm sure I'll become an asset to the project.
(I have some experience in Typescript and Java and have learned C a few years ago).

**Comment by EliKalter** [comment]
> I am interested in collaborating with someone on their project so I can learn the language while they get a sidekick. Let me Know if this is something that could work for you. I Would need you to explain and guide me through my first steps in the language (I already started learning) and set the standard for me in code reviews but after a short while I'm sure I'll become an asset to the project. (I have some experience in Typescript and Java and have learned C a few years ago).

I now looked more carefully at the description of this thread, I would like to take a serious look at the src code and see if I can solve this issue (I'm aware this is considered a simple issue but it might not be so simple for me...), Can I be assigned to it? I'll report back if I think it might be a good idea to let someone else take over.

**Comment by SanchithHegde** [comment]
Sure @EliKalter, I've assigned this to you.

**Comment by EliKalter** [comment]
> Sure @EliKalter, I've assigned this to you.

I have a few points I need to clarify in order to solve this issue:

1) I'm now reading the CONTRIBUTING.md file, I see commits need to be formatted in a specific way and every commit message also must be formatted to specification, all of this seems complicated and daunting for me as a complete novice, Is it ok for me to do things "wrong" to begin with and get help refactoring the commits stuff along the way? I'm sure I'll get the hang of it soon enough...
2) Can someone please help me locate the files in which the changes are needed?
3) Do I clone the project as it is or create a fork first?
4) How do I open a PR connected to this issue?
5) I see in the PULL_REQUEST_TEMPLATE.md file some things I'm not sure how to do similar to how I feel about the commits convention, can I do this with the freedom of getting it wrong at first?

As you can tell I'm a complete novice to all of this and need help in every step of the way, But I can assure you I will make a concerted effort to learn everything needed as quickly and as efficiently as possible.
I again apologize for not knowing so much of the basics and will understand if the code owners will not find me a good fit to contribute at this point in time.

**Comment by SanchithHegde** [comment]
> 1. I'm now reading the CONTRIBUTING.md file, I see commits need to be formatted in a specific way and every commit message also must be formatted to specification, all of this seems complicated and daunting for me as a complete novice, Is it ok for me to do things "wrong" to begin with and get help refactoring the commits stuff along the way? I'm sure I'll get the hang of it soon enough...

It's completely fine, you can worry about commit message format once you're done with the PR. Or if you feel it to be too many things to learn at once, you can ignore it for the first PR and consider it for the next.

> 2. Can someone please help me locate the files in which the changes are needed?

I'd suggest starting with the enum variant definition here:

https://github.com/juspay/hyperswitch/blob/22a5372481bbf854cffb8b683606cdf0644a5f54/crates/router/src/core/errors/api_error_response.rs#L121-L122

and updating the enum variant to be a struct variant with a `connector_label` field. Once that's done, you'd get errors from the Rust compiler that the `connector_label` field hasn't been passed in all places where the `DuplicateMerchantConnectorAccount` error is raised. You can proceed fixing the errors one by one.

> 3. Do I clone the project as it is or create a fork first?

I'd suggest forking our repository first, and then cloning your fork. This would reduce the amount of git setup required by a slightly.

> 4. How do I open a PR connected to this issue?

Once you are done with your feature, you can open a PR from your fork to our repository. Once the PR is opened, we can link it to this issue. Ignore it for now, let's worry about it later.

> 5. I see in the PULL_REQUEST_TEMPLATE.md file some things I'm not sure how to do similar to how I feel about the commits convention, can I do this with the freedom of getting it wrong at first?

If it's about the `cargo fmt` and `clippy` lints, yes, you can worry about them when your PR is almost done.

By the way, you can also join and ask queries on our Discord server if you'd prefer that, compared to GitHub.

**Comment by EliKalter** [comment]
> 

Amazing, thanks for the lengthy response, I feel much more comfortable starting work now!
By the way 2 is an incredibly fun and easy way to do things thanks to the infamous rust compiler that I'm starting to enjoy,
And lastly, I will join the discord server soon.

**Comment by EliKalter** [comment]
> 

Ok, I made the changes I think satisfy this issue in all relevant files, I now want to run the commands needed to check that the compiler does not raise a compilation error and do any addition  steps required by the community standards before PR, what  do I need to do?
When I try to run "cargo check" I get so many errors I'm sure I'm doing something wrong (do I need to add +nightly? if so how do I install it? should I only check a subdirectory of the project?)

**Comment by SanchithHegde** [comment]
> When I try to run "cargo check" I get so many errors I'm sure I'm doing something wrong (do I need to add +nightly? if so how do I install it? should I only check a subdirectory of the project?)

Nope, you don't need the `+nightly` for `cargo check`, it's only required as an argument for `cargo fmt`.

You can post a screenshot/logs of the error you're facing on Discord, and I'll help you out with resolving them.
