### ISSUE TITLE
[FEATURE] Refactor Stripe compatibility routes

### ISSUE THREAD

**Issue by Abhicodes-crypto** [juspay/hyperswitch#961]
### Feature Description

Use `web::resource` to specify the paths in [`/crates/router/src/compatibility/stripe/app.rs`](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/compatibility/stripe/app.rs)

### Possible Implementation

Refer this file https://github.com/juspay/hyperswitch/blob/main/crates/router/src/routes/app.rs

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by nachiketkanore** [comment]
I would like to take this!

**Comment by SanchithHegde** [comment]
Sure @nachiketkanore, I've assigned this to you.
