### ISSUE TITLE
[FEATURE] add a route that will invalidate cache

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch#995]
### Feature Description

Currently we don't have any way to manually invalidate cache that's stored in redis and in-memory, Add a route that given a key will invalidate both of redis and inmemory cache.

### Possible Implementation

So the in memory cache currently has `invalidate` function that will delete the entry in the cache, and in our redis interface we have `delete_key` function that will delete the entry from redis. You need to create a route in `app.rs` that will call this on `AdminApiKeyAuth`. 

### Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

None

**Comment by jeevaprakashdr** [comment]
@dracarys18 I would like to look at this. Please can you assign it to me?

**Comment by dracarys18** [comment]
Done @jeevaprakashdr
