### ISSUE TITLE
[FEATURE] Implement `ApiKeyInterface` for `MockDb`

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#996]
Spin out from #172. Please refer to that issue for more information.

**Comment by derekleverenz** [comment]
Hi, can I give this one a shot?

**Comment by SanchithHegde** [comment]
@derekleverenz Sure! I've assigned this to you.

**Comment by derekleverenz** [comment]
@SanchithHegde looking at this today, I think its pretty straightforward, but its simpler if I derive `Clone` for `ApiKey` and `HashedApiKey`. is that ok or do you want to avoid extra implementations like that?

**Comment by SanchithHegde** [comment]
> [...] I think its pretty straightforward, but its simpler if I derive `Clone` for `ApiKey` and `HashedApiKey`. is that ok or do you want to avoid extra implementations like that?

Yes, it should be okay to derive `Clone` for `ApiKey` and `HashedApiKey`.

**Comment by derekleverenz** [comment]
I have a branch up with the changes (https://github.com/juspay/hyperswitch/compare/main...derekleverenz:hyperswitch:fix-996-mockdb-apikeyinterface) but im not sure how best to test it. I can add some unit tests, or else is there a method you would prefer?

**Comment by SanchithHegde** [comment]
@derekleverenz It should be fine to add unit tests. I took a quick look at your code, it was quite well written, even though it was for a mock database only. Much appreciated!
